Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2019-08, with the labels that each got.

#40 Inject version to CSI binary for docker image
  cluster/images/csi/Dockerfile
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#41 Fix path to injected version
  cluster/images/csi/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#42 Honor GOPROXY for docker-in-docker builds.
  cluster/images/csi/Dockerfile
  hack/release.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#43 Create a base container image for CSI driver
  .gitignore
  Makefile
  cluster/images/csi/.gitignore
  hack/release.sh
  images/ci/Dockerfile
  images/ci/Makefile
  images/ci/README.md
  images/driver-base/Dockerfile
  images/driver-base/Makefile
  images/driver/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#44 Use new csi-driver-base image
  images/driver/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#45 Make building of ci/base images similar
  images/ci/Dockerfile
  images/ci/Makefile
  images/driver-base/Dockerfile
  images/driver-base/Makefile
  images/driver/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#47 Common library for CNS CSI driver
  .gitignore
  go.mod
  go.sum
  pkg/common/cns-lib/node/cache.go
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/common/cns-lib/vsphere/cns.go
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/cns-lib/vsphere/datastore.go
  pkg/common/cns-lib/vsphere/hostsystem.go
  pkg/common/cns-lib/vsphere/pbm.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/common/cns-lib/vsphere/virtualmachine.go
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/types.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/vsphereutil.go
  pkg/kubernetes/informers.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#53 Fix staticcheck script for CI
  hack/check-staticcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
