Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2019-05, with the labels that each got.

#8 Update manifests for K8s 1.14
  README.md
  docs/deploying_csi_vsphere_with_rbac.md
  manifests/1.13/vsphere-csi-controller-rbac.yaml
  manifests/1.13/vsphere-csi-controller-ss.yaml
  manifests/1.13/vsphere-csi-crd.yaml
  manifests/1.13/vsphere-csi-node-ds.yaml
  manifests/1.13/vsphere-csi-node-rbac.yaml
  manifests/1.14/deploy/vsphere-csi-attacher.yaml
  manifests/1.14/deploy/vsphere-csi-controller-ss.yaml
  manifests/1.14/deploy/vsphere-csi-node-ds.yaml
  manifests/1.14/deploy/vsphere-csi-provisioner.yaml
  manifests/1.14/rbac/attacher-rbac.yaml
  manifests/1.14/rbac/provisioner-rbac.yaml
  manifests/1.14/rbac/vsphere-csi-controller-rbac.yaml
  manifests/example-test-pod.yaml
  manifests/example-vsphere-pvc.yaml
  manifests/example-vsphere-sc.yaml
  manifests/vcsi-secret.yaml
  manifests/vsphere.conf
Labels: approved, cncf-cla: yes, lgtm, size/XL

#9 Enable topology gate for CSI driver
  manifests/1.14/deploy/vsphere-csi-provisioner.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#10 Add/create csi-ci testing image
  .gitignore
  Makefile
  hack/images/ci/Dockerfile
  hack/images/ci/Makefile
  hack/images/ci/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#12 Added resource type csinodes to clusterrole for storage.k8s.io API group for provisioning
  manifests/1.14/rbac/provisioner-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#13 add missing provisioner RBAC role
  manifests/1.14/rbac/provisioner-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#14 Deploy controller-related components on master nodes only
  manifests/1.13/vsphere-csi-controller-ss.yaml
  manifests/1.14/deploy/vsphere-csi-attacher.yaml
  manifests/1.14/deploy/vsphere-csi-controller-ss.yaml
  manifests/1.14/deploy/vsphere-csi-provisioner.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#16 Address clean up of files on node crash
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/service.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#18 Update deployment manifests to use v0.2.0
  manifests/1.13/vsphere-csi-controller-ss.yaml
  manifests/1.13/vsphere-csi-node-ds.yaml
  manifests/1.14/deploy/vsphere-csi-controller-ss.yaml
  manifests/1.14/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
