Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2019-09, with the labels that each got.

#52 CNS CSI Driver
  Makefile
  cmd/vsphere-csi/main.go
  example/example-pod.yaml
  example/example-pvc.yaml
  example/example-sc-WaitForFirstConsumer-With-Multiple-Zone-Region.yaml
  example/example-sc-WaitForFirstConsumer-with-topology.yaml
  example/example-sc-WaitForFirstConsumer.yaml
  example/example-sc-multiple-zones-regions.yaml
  example/example-sc-multiple-zones.yaml
  example/example-sc-zone.yaml
  example/example-sc.yaml
  go.mod
  go.sum
  images/driver/Dockerfile
  manifests/1.13/vsphere-csi-controller-rbac.yaml
  manifests/1.13/vsphere-csi-controller-ss.yaml
  manifests/1.13/vsphere-csi-crd.yaml
  manifests/1.13/vsphere-csi-node-ds.yaml
  manifests/1.13/vsphere-csi-node-rbac.yaml
  manifests/1.14/deploy/vsphere-csi-attacher.yaml
  manifests/1.14/deploy/vsphere-csi-controller-ss.yaml
  manifests/1.14/deploy/vsphere-csi-node-ds.yaml
  manifests/1.14/deploy/vsphere-csi-provisioner.yaml
  manifests/1.14/rbac/attacher-rbac.yaml
  manifests/1.14/rbac/provisioner-rbac.yaml
  manifests/1.14/rbac/vsphere-csi-controller-rbac.yaml
  manifests/example-test-pod.yaml
  manifests/example-vsphere-sc.yaml
  manifests/vcsi-secret.yaml
  manifests/vsphere.conf
  pkg/common/config/config.go
  pkg/csi/service/cns/controller.go
  pkg/csi/service/cns/controller_helper.go
  pkg/csi/service/cns/controller_test.go
  pkg/csi/service/cns/nodes.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/fcd/constants.go
  pkg/csi/service/fcd/controller.go
  pkg/csi/service/fcd/controller_test.go
  pkg/csi/service/fcd/vsphere_helper.go
  pkg/csi/service/fcd/vsphere_helper_test.go
  pkg/csi/service/identity.go
  pkg/csi/service/node.go
  pkg/csi/service/node_test.go
  pkg/csi/service/service.go
  pkg/csi/testing/plugin_startup_test.go
  pkg/csi/types/constants.go
  pkg/csi/types/envvars.go
  pkg/csi/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#54 Metadata Syncer for vsphere CSI Driver
  Makefile
  cmd/syncer/main.go
  go.mod
  go.sum
  hack/release.sh
  images/syncer/Dockerfile
  pkg/syncer/metadatasyncer.go
  pkg/syncer/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#61 Fullsync for vsphere CSI Driver
  go.mod
  go.sum
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#60 E2E tests for vsphere CSI driver
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/statefulset_with_topology.go
  tests/e2e/vsphere_shared_datastore.go
  tests/e2e/vsphere_volume_disksize.go
  tests/e2e/vsphere_volume_fstype.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#65 Update ENV variable name in syncer to match with the deployment yaml file
  manifests/1.14/deploy/vsphere-csi-controller-ss.yaml
  tests/e2e/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#67 Increase the timeout for the attacher and provisioner
  manifests/1.14/deploy/vsphere-csi-controller-ss.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
