Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2019-12, with the labels that each got.

#105 Fix images in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#96 Remove vsphere credentials from csi node daemonset
  pkg/common/config/config.go
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#88 Allow root CA to be configured
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/config/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#117 Remove Pending Status Check in PodDelete
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
