Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2020-12, with the labels that each got.

#514 Added doc to clarify that vSphere CSI and CNS does not currently support SDRS.
  docs/book/supported_features_matrix.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#509 Add valid vSphere volume check for update pod metadata
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/M

#482 Support NoMigration mode for vSAN direct disk decommission
  pkg/syncer/k8scloudoperator/placement.go
  pkg/syncer/storagepool/diskDecommissionController.go
  pkg/syncer/storagepool/intended_state.go
  pkg/syncer/storagepool/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#518 Cherry-pick from master: Add valid vsphere volume check for update pod metadata
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#510 remove temporary fix for detach and delete race
  go.mod
  go.sum
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#515 Assign full permissions for file volumes created in WCP
  pkg/common/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#521 Update the driver and syncer images in manifest YAMLs to latest changes
  manifests/latest/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/latest/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/latest/vsphere-7.0u1/vanilla/deploy/validatingwebhook.yaml
  manifests/latest/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#479 Retrieve datastoreURL from PlacementResults for topology support
  go.mod
  go.sum
  pkg/apis/migration/migration.go
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/syncer_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#512 Create file volumes in TKG clusters
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/csi/service/wcpguest/controller_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#496 Fix bug where all SNA StoragePools were deleted on PSOD on one host
  pkg/syncer/storagepool/intended_state.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#516 Fix for testcase "CSI - verify invalid fstype"
  tests/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#500 vcp to csi migration create and delete test cases
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_create_delete.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#525 Bumping up the golang version from go 1.13 to go 1.15.
  go.mod
  images/driver/Dockerfile
  images/syncer/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#504 update StoragePool capacity based on unbounded PVC from all namespaces in PE
  pkg/syncer/k8scloudoperator/placement.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#531 Avoid orphan volumes by storing createVolume taskInfo using in-memory map
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/cns/controller.go
  pkg/csi/service/cns/controller_test.go
  pkg/syncer/syncer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, v1.0.3

#534 Revert TKGS CSIDriver version from v1 to v1beta1
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#536 Introduce cnsfileaccessconfig API and create cnsfileaccessconfig CRD as part of CnsOperator Init
  cmd/syncer/main.go
  go.mod
  images/syncer/Dockerfile
  pkg/apis/cnsoperator/cnsfileaccessconfig/v1alpha1/cnsfileaccessconfig_types.go
  pkg/apis/cnsoperator/cnsfileaccessconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cnsoperator/config/cnsfileaccessconfig_crd.yaml
  pkg/apis/cnsoperator/register.go
  pkg/apis/cnsoperator/zz_generated.openapi.go
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#532 Add PV and VA listers in CSI controller to avoid deletion of volumes that exist in volume attachment spec
  manifests/deploy/vsphere-csi-controller-ss.yaml
  manifests/deploy/vsphere-csi-node-ds.yaml
  manifests/rbac/vsphere-csi-controller-rbac.yaml
  pkg/csi/service/cns/controller.go
  pkg/csi/service/cns/controller_test.go
  pkg/kubernetes/informers.go
  pkg/syncer/syncer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, v1.0.3

#537 Update v1.0.3-rc.1 images in driver deployment yaml files
  manifests/deploy/vsphere-csi-controller-ss.yaml
  manifests/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#539 Avoid volume deletion in syncer and remove caching of tasks for static provisioning
  pkg/common/cns-lib/volume/manager.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, size/M, v1.0.3

#547 Update v1.0.3-rc.2 images in driver deployment yaml files
  manifests/deploy/vsphere-csi-controller-ss.yaml
  manifests/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#541 Update RBAC and FSS info in manifests dev 7.0 and 6.7U3 folders
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-67u3/vanilla/rbac/vsphere-csi-node-rbac.yaml
  manifests/dev/vsphere-7.0/guestcluster/1.15/pvcsi.yaml
  manifests/dev/vsphere-7.0/guestcluster/1.16/pvcsi.yaml
  manifests/dev/vsphere-7.0/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0/vanilla/rbac/vsphere-csi-node-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#523 Definition for CnsFileVolumeClients resource.
  images/syncer/Dockerfile
  pkg/internal/cnsoperator/cnsfilevolumeclient/v1alpha1/cnsfilevolumeclient_types.go
  pkg/internal/cnsoperator/cnsfilevolumeclient/v1alpha1/groupversion_info.go
  pkg/internal/cnsoperator/cnsfilevolumeclient/v1alpha1/zz_generated.deepcopy.go
  pkg/internal/cnsoperator/config/cnsfilevolumeclient_crd.yaml
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#551 Update docs for vSAN stretch cluster supportability
  docs/book/compatiblity_matrix.md
  docs/book/supported_features_matrix.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#543 Enable online resize in dev 7.0U2 manifests
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.17/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.18/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.19/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#553 Remove subResource field in cnsfilevolumeclient and cnsfileaccessconfig crd
  pkg/apis/cnsoperator/config/cnsfileaccessconfig_crd.yaml
  pkg/internal/cnsoperator/config/cnsfilevolumeclient_crd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#528 pod gcr image fix
  tests/e2e/binding_modes_with_topology.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/e2e_common.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/labelupdates.go
  tests/e2e/operationstorm.go
  tests/e2e/partial_topology_values.go
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/storagepolicy.go
  tests/e2e/testing-manifests/statefulset/nginx/statefulset.yaml
  tests/e2e/util.go
  tests/e2e/volume_provisioning_with_topology.go
  tests/e2e/vsphere_file_volume_basic.go
  tests/e2e/vsphere_file_volume_basic_mount.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fstype.go
  tests/e2e/vsphere_volume_mount.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#556 changing images for v2.1.0 release
  manifests/v2.1.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.0/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.0/vsphere-7.0/guestcluster/1.15/pvcsi.yaml
  manifests/v2.1.0/vsphere-7.0/guestcluster/1.16/pvcsi.yaml
  manifests/v2.1.0/vsphere-7.0/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.0/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.0/vsphere-7.0u1/guestcluster/1.15/pvcsi.yaml
  manifests/v2.1.0/vsphere-7.0u1/guestcluster/1.16/pvcsi.yaml
  manifests/v2.1.0/vsphere-7.0u1/guestcluster/1.17/pvcsi.yaml
  manifests/v2.1.0/vsphere-7.0u1/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0u1/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.0/vsphere-7.0u1/supervisorcluster/k8s-1.16/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0u1/supervisorcluster/k8s-1.16/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.0/vsphere-7.0u1/vanilla/deploy/create-validation-webhook.sh
  manifests/v2.1.0/vsphere-7.0u1/vanilla/deploy/generate-signed-webhook-certs.sh
  manifests/v2.1.0/vsphere-7.0u1/vanilla/deploy/validatingwebhook.yaml
  manifests/v2.1.0/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.0/vsphere-7.0u1/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#555 doc changes for v2.1.0 release
  README.md
  docs/book/features/vsphere_csi_migration.md
  docs/book/supported_features_matrix.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#520 Add missing error check in storagepool service
  pkg/syncer/storagepool/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#554 Fix types in cnsregistervolume and cnsfileaccessconfig crd spec
  pkg/apis/cnsoperator/config/cnsfileaccessconfig_crd.yaml
  pkg/apis/cnsoperator/config/cnsregistervolume_crd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#546 Avoid task caching for static file volume and static block volume provisioning
  pkg/common/cns-lib/volume/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#511 file vol static provision basic test
  tests/e2e/csi_static_provisioning_file_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_create_delete.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#564 GCR pod image fix for file vol basic static prov test case
  tests/e2e/csi_static_provisioning_file_basic.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
