Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2020-09, with the labels that each got.

#331 Use correct format for logging
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/storagepool/intended_state.go
  pkg/syncer/storagepool/storageclasswatch.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#346 Update pod metadata in full sync only when pod status is running
  pkg/syncer/fullsync.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/XS

#345 static fileshare volume provisioning without fstype
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/S

#349 Remove device check in NodeGetVolumeStats
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/S

#342 Set feature state once before full sync operations
  cmd/syncer/main.go
  pkg/syncer/fullsync.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/M

#340 cherry picking fixes to StoragePool
  pkg/syncer/storagepool/intended_state.go
  pkg/syncer/storagepool/listener.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#351 upgrade sidecar containers
  manifests/latest/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#358 fail volume creation when unsupported VCP parameters are observed, instead of silently dropping them.
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/M

#355 Initialize CnsRegisterVolume CRD in CNS Operator init.
  pkg/apis/migration/migration.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/L

#321 Have automatic restart of property collector listener
  pkg/syncer/storagepool/intended_state.go
  pkg/syncer/storagepool/listener.go
  pkg/syncer/storagepool/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#369 fail creating file volume using VCP storageclass
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/XS

#368 Make corrections in log messages
  pkg/apis/migration/migration.go
  pkg/common/config/config.go
  pkg/csi/service/common/vsphereutil.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/S

#337 validating admission webhook for storageclass
  cmd/syncer/main.go
  manifests/latest/vsphere-7.0u1/vanilla/deploy/create-validation-webhook.sh
  manifests/latest/vsphere-7.0u1/vanilla/deploy/generate-signed-webhook-certs.sh
  manifests/latest/vsphere-7.0u1/vanilla/deploy/validatingwebhook.yaml
  pkg/common/config/config.go
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/admissionhandler/config.go
  pkg/syncer/admissionhandler/validatestorageclass.go
  pkg/syncer/admissionhandler/validatestorageclass_test.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/XL

#367 Update pod metadata for inline migrated volumes
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/M

#334 Document upstream attach/detach issue and workaround
  docs/book/known_issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#380 refactor volumeMigration.GetVolumeID to take VolumeSpec as pointer
  pkg/apis/migration/migration.go
  pkg/common/unittestcommon/types.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/M

#364 CSI migration: Init volume migration service in Syncer before performing operations
  pkg/apis/migration/migration.go
  pkg/csi/service/common/feature_state.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/L

#291 Add volume expansion documentation for 7.0U1 + some more improvements
  docs/book/README.md
  docs/book/features/block_volume.md
  docs/book/features/file_volume.md
  docs/book/features/volume_expansion.md
  docs/book/supported_features_matrix.md
  example/vanilla-k8s-block-driver/example-static-block-provisioning.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/L

#379 allow thin volume provisioning with vcp sc post migration
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/M

#312 vSphere CSI Migration doc
  docs/book/SUMMARY.md
  docs/book/driver-deployment/deploying_csi_with_zones.md
  docs/book/features/vsphere_csi_migration.md
  docs/book/known_issues.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-2.1.0-candidate, size/L

#386 Document datacenter name restrictions.
  docs/book/driver-deployment/installation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#382 Adding vSphere 7.0U2 CSI driver YAMLs
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0/guestcluster/1.15/pvcsi.yaml
  manifests/dev/vsphere-7.0/guestcluster/1.16/pvcsi.yaml
  manifests/dev/vsphere-7.0/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u1/guestcluster/1.15/pvcsi.yaml
  manifests/dev/vsphere-7.0u1/guestcluster/1.16/pvcsi.yaml
  manifests/dev/vsphere-7.0u1/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u1/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u1/supervisorcluster/k8s-1.16/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/supervisorcluster/k8s-1.16/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/create-validation-webhook.sh
  manifests/dev/vsphere-7.0u1/vanilla/deploy/generate-signed-webhook-certs.sh
  manifests/dev/vsphere-7.0u1/vanilla/deploy/validatingwebhook.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0u1/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.17/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.17/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.18/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.18/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.19/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.19/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/create-validation-webhook.sh
  manifests/dev/vsphere-7.0u2/vanilla/deploy/generate-signed-webhook-certs.sh
  manifests/dev/vsphere-7.0u2/vanilla/deploy/validatingwebhook.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0u2/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#389 adding QPS and BURST param for k8s client in volume migration service and other k8s clients in the system
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_test.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/M

#396 use correct env INCLUSTER_CLIENT_BURST
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/XS

#394 Add CnsRegisterVolume content to docs
  docs/book/features/block_volume.md
  docs/book/known_issues.md
  example/sv-block-driver/static-block-provisioning-fcd.yaml
  example/sv-block-driver/static-block-provisioning-vmdk.yaml
  example/vanilla-k8s-block-driver/example-cnsregistervolume.yaml
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/M

#381 disable Topology feature-gate on external-provisioner
  docs/book/driver-deployment/deploying_csi_with_zones.md
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v1.0.2/deploy/vsphere-csi-controller-ss.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/M
