Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2020-05, with the labels that each got.

#206 Update README.md
  docs/book/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#210 fix: add missing patch verb to persistentvolumes
  manifests/v2.0.0/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#213 Update overview.md
  docs/book/overview.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#216 Patch 1
  docs/book/known_issues.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#218 Minor editorial changes in compatiblity_matrix.md
  docs/book/compatiblity_matrix.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#110 Update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#222 correct unix domain socket path for CSI driver
  manifests/v1.0.2/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#224 Fix CreateVolume validation to raise error for invalid parameters
  pkg/csi/service/vanilla/controller_helper.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
