Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2020-04, with the labels that each got.

#150 upgrade base driver image
  images/driver-base/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#153 vSphere CSI driver documentation structure
  docs/README.md
  docs/book/README.md
  docs/book/SUMMARY.md
  docs/book/compatiblity_matrix.md
  docs/book/development.md
  docs/book/driver-deployment/deploying_csi_with_zones.md
  docs/book/driver-deployment/installation.md
  docs/book/driver-deployment/prerequisites.md
  docs/book/features/block_volume.md
  docs/book/features/file_volume.md
  docs/book/features/volume_expansion.md
  docs/book/features/volume_topology.md
  docs/book/glossary.md
  docs/book/known_issues.md
  docs/book/limits.md
  docs/book/overview.md
  docs/book/supported_features_matrix.md
  docs/book/testing.md
  docs/book/troubleshooting.md
  docs/book/upgrade_support_matrix.md
  docs/deploying_ccm_and_csi_with_multi_dc_vc_aka_zones.md
  docs/deploying_csi_vsphere_with_rbac.md
  docs/images/clusterbased.png
  docs/images/datacenterbased.png
  docs/images/pitfalls.png
  docs/images/vmware_logo.png
  docs/images/whichdatastore.png
  go.mod
  go.sum
  hack/build-gitbooks.sh
  netlify.toml
Labels: approved, cncf-cla: yes, lgtm, size/L

#158 Upgrade Support Matrix
  docs/book/upgrade_support_matrix.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#159 adding images for roles-and-privileges
  docs/images/CNS-DATASTORE-USAGE.png
  docs/images/CNS-SEARCH-AND-SPBM-USAGE.png
  docs/images/CNS-VM-USAGE.png
  docs/images/HOST-CONFIG-STORAGE-USAGE.png
  docs/images/READ-ONLY-USAGE.png
  docs/images/ROLE-CNS-DATASTORE.png
  docs/images/ROLE-CNS-HOST-CONFIG-STORAGE.png
  docs/images/ROLE-CNS-SEARCH-AND-SPBM.png
  docs/images/ROLE-CNS-VM.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#160 vsphere CSI driver prerequisites doc
  docs/book/driver-deployment/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#164 Volume Topology feature documentation
  docs/book/driver-deployment/deploying_csi_with_zones.md
  docs/book/features/volume_topology.md
  docs/images/REGION_AND_ZONES.png
Labels: approved, cncf-cla: yes, lgtm, size/XL

#170 fixed make test-e2e
  hack/run-e2e-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#172 Add to OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#175 Add doc for offline volume expansion
  docs/book/features/volume_expansion.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#174 Adding CNS introduction doc
  docs/book/README.md
  docs/images/CNS-Architecture.png
Labels: approved, cncf-cla: yes, lgtm, size/S

#177 Fix ginkgo parameter supply using GINKGO_OPTS
  hack/run-e2e-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#169 vSphere CSI driver development section in release document.
  docs/book/SUMMARY.md
  docs/book/development.md
  docs/book/testing.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#165 fix returning error after logging them
  pkg/csi/service/node.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#180 Fixed the link to the CNS architecture image.
  docs/book/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#181 remove mounting vsphere-config-secret in vsphere-csi-node daemonset
  manifests/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  pkg/common/config/config.go
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#184 Add --version flag and fix Dockerfile
  Makefile
  cmd/vsphere-csi/main.go
  docs/book/development.md
  images/driver/Dockerfile
  pkg/csi/service/identity.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#178 Adding the documentation for Block Volume
  docs/book/features/block_volume.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#171 Documentation for installation of vSphere CSI Driver
  docs/book/driver-deployment/installation.md
  docs/book/driver-deployment/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#179 putting back deployment manifest files for v1.0.2 and moving v2.0.0 yamls to manifests/v2.0.0
  manifests/v1.0.2/deploy/vsphere-csi-controller-ss.yaml
  manifests/v1.0.2/deploy/vsphere-csi-node-ds.yaml
  manifests/v1.0.2/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.0/vsphere-7.0/guestcluster/1.15/pvcsi.yaml
  manifests/v2.0.0/vsphere-7.0/guestcluster/1.16/pvcsi.yaml
  manifests/v2.0.0/vsphere-7.0/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#185 Update deployment guide with new manifest path
  docs/book/driver-deployment/installation.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#188 updating v2.0.0-rc.1 images in the deployment YAMLs
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#176 re-arranged content for volume topology feature
  docs/book/driver-deployment/deploying_csi_with_zones.md
  docs/book/features/volume_topology.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#182 Documentation for file volumes
  docs/book/features/file_volume.md
  example/vanilla-k8s-file-driver/example-pods.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#190 Adding known issues for CSI documentation
  docs/book/known_issues.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#194 Only check if vSAN file service is enabled when vSAN datastores are defined
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#192 adding doc for compatibility and supported features matrix and limits
  docs/book/compatiblity_matrix.md
  docs/book/limits.md
  docs/book/supported_features_matrix.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#198 updating README file of the repository
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#197 correcting cluster flavor name in the limit doc
  docs/book/limits.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#201 add support statement
  docs/book/SUMMARY.md
  docs/book/support.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#173 Add Overview and Troubleshooting docs
  docs/book/overview.md
  docs/book/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#205 cherry pick changes to release 2.0
  README.md
  docs/book/SUMMARY.md
  docs/book/compatiblity_matrix.md
  docs/book/driver-deployment/installation.md
  docs/book/driver-deployment/prerequisites.md
  docs/book/features/block_volume.md
  docs/book/features/file_volume.md
  docs/book/known_issues.md
  docs/book/limits.md
  docs/book/overview.md
  docs/book/support.md
  docs/book/supported_features_matrix.md
  docs/book/troubleshooting.md
  example/vanilla-k8s-file-driver/example-pods.yaml
  manifests/v1.0.2/deploy/vsphere-csi-controller-ss.yaml
  manifests/v1.0.2/deploy/vsphere-csi-node-ds.yaml
  manifests/v1.0.2/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.0/vsphere-7.0/guestcluster/1.15/pvcsi.yaml
  manifests/v2.0.0/vsphere-7.0/guestcluster/1.16/pvcsi.yaml
  manifests/v2.0.0/vsphere-7.0/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#207 updating release v2.0.0 images in deployment yamls
  README.md
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#208 upgrade syncer container image
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#212 fix: use the same images for both vSphere product
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
