Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2020-01, with the labels that each got.

#119 Update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#120 Add myself to owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#127 Hotfix compatibility issue on 7.0
  pkg/csi/service/common/vsphereutil.go
  pkg/syncer/syncer_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#102 Support for running controller outside of cluster
  go.mod
  pkg/csi/service/cns/nodes.go
  pkg/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#108 Implement GetNodeVolumeStats
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#132 Invoke node Update only for providerID changes
  pkg/csi/service/cns/nodes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#133 Updating README and YAMLs for v1.0.2
  README.md
  manifests/1.14/deploy/vsphere-csi-controller-ss.yaml
  manifests/1.14/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S
