Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2020-07, with the labels that each got.

#261 Fixed vcclient NotAuthenticated issue
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#262 print version in the log
  Makefile
  cmd/syncer/main.go
  cmd/vsphere-csi/main.go
  images/syncer/Dockerfile
  pkg/syncer/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#260 Updated feature matrix so it's easier to understand
  docs/book/supported_features_matrix.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#263 Handling PVC updates during csi migration
  pkg/csi/service/common/constants.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#264 Handling PV updates during csi migration
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#259 Handling Pod updates for csi migration support
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#252 CSI migration - Full sync modifications
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#272 Modify syncer util function to fetch only PV information for migrated volumes
  pkg/syncer/fullsync.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#273 Migrated inline volumes related changes
  pkg/syncer/fullsync.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#274 fixed golangci-lint issues and added golangci-lint check in the make check
  Makefile
  pkg/apis/migration/migration.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/e2e_common.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#280 fixing k8s prow golangci-lint error
  Makefile
  hack/check-golangci-lint.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#281 Update release-2.0 YAMLs
  README.md
  manifests/v1.0.2/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#283 Bump up govmomi
  go.mod
  go.sum
  tests/e2e/connection.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/S

#279 vSphere CSI driver deployment yaml files for 2.1.0
  manifests/latest/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/latest/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/latest/vsphere-7.0/guestcluster/1.15/pvcsi.yaml
  manifests/latest/vsphere-7.0/guestcluster/1.16/pvcsi.yaml
  manifests/latest/vsphere-7.0/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/latest/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/latest/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/latest/vsphere-7.0u1/guestcluster/1.15/pvcsi.yaml
  manifests/latest/vsphere-7.0u1/guestcluster/1.16/pvcsi.yaml
  manifests/latest/vsphere-7.0u1/guestcluster/1.17/pvcsi.yaml
  manifests/latest/vsphere-7.0u1/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0u1/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/latest/vsphere-7.0u1/supervisorcluster/k8s-1.16/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0u1/supervisorcluster/k8s-1.16/rbac/vsphere-csi-controller-rbac.yaml
  manifests/latest/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/latest/vsphere-7.0u1/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#286 Remove akutz from reviewers in OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#282 Use Common CO interface for Vanilla K8S to handle CSI migration feature switch
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/common/unittestcommon/types.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/L

#289 Check if migrated-to annotation exists in PV during full sync
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#270 Doc for Volume Health Feature.
  docs/book/SUMMARY.md
  docs/book/features/volume_health.md
  docs/book/known_issues.md
  docs/book/supported_features_matrix.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/L
