Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2020-10, with the labels that each got.

#395 Enhance log in fullsync.go.
  pkg/syncer/fullsync.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#332 TKGS: Initialize FSS config info when reading GC config
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  pkg/common/config/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/S

#415 Change default CnsRegisterVolume controller worker threads to 40
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#409 fix vsphere backward compatibility issue
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/M, v2.0.1

#407 Add known issues for 7.0U1 release
  docs/book/known_issues.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#391 CSI Support for VMC, part 1.
  go.mod
  go.sum
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#413 cherry-pick: vSAN SNA Storagepools - change2
  pkg/common/cns-lib/vsphere/hostsystem.go
  pkg/syncer/storagepool/intended_state.go
  pkg/syncer/storagepool/listener.go
  pkg/syncer/storagepool/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#417 [cherry-pick-to-release-2.0] - fix vsphere backward compatibility issue
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#399 CSI support for CNS telemetry
  go.mod
  go.sum
  pkg/apis/cnsoperator/cnsvolumemetadata/v1alpha1/cnsvolumemetadata_types.go
  pkg/apis/migration/migration.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/config/types.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/util.go
  pkg/syncer/cnsoperator/controller/cnsvolumemetadata/cnsvolumemetadata_controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#400 Migration of E2E test cases from GitLab
  go.mod
  go.sum
  tests/e2e/bootstrap.go
  tests/e2e/connection.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/docs/guest_cluster_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_full_sync.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/util.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_file_volume_basic.go
  tests/e2e/vsphere_file_volume_basic_without_datacenter.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_mount.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#418 cherry-pick commits to release 2.1 branch
  docs/book/SUMMARY.md
  docs/book/driver-deployment/deploying_csi_with_zones.md
  docs/book/driver-deployment/installation.md
  docs/book/features/block_volume.md
  docs/book/features/vsphere_csi_migration.md
  docs/book/known_issues.md
  example/sv-block-driver/static-block-provisioning-fcd.yaml
  example/sv-block-driver/static-block-provisioning-vmdk.yaml
  example/vanilla-k8s-block-driver/example-cnsregistervolume.yaml
  manifests/latest/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v1.0.2/deploy/vsphere-csi-controller-ss.yaml
  manifests/v2.0.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/common/config/config.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_test.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#434 Add validation for cluster id to not exceed 64 chars
  pkg/common/config/config.go
  pkg/common/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/S

#419 Modifying the FSS configmap name in vanilla to internal
  cmd/syncer/main.go
  docs/book/features/vsphere_csi_migration.md
  example/vanilla-k8s-block-driver/vsphere.conf
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/generate-signed-webhook-certs.sh
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/generate-signed-webhook-certs.sh
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator_test.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/admissionhandler/config.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/XL

#438 Fix volume Migration CRD List spec
  pkg/apis/migration/v1alpha1/register.go
  pkg/apis/migration/v1alpha1/types.go
  pkg/apis/migration/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/S

#403 deployment yaml files for v2.0.1 release
  manifests/v2.0.1/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.1/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.1/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.1/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.1/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.1/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL, v2.0.1

#412 Use double checked locking for volume migration service instantiation
  pkg/apis/migration/migration.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/L

#430 Stop creating vsan-sna StoragePools for remote vSAN datastore
  pkg/syncer/storagepool/intended_state.go
  pkg/syncer/storagepool/listener.go
  pkg/syncer/storagepool/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#442 Update known issues and README
  README.md
  docs/book/known_issues.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#426 Delete volume migration crd in syncer
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/S

#439 upgrade driver documentation
  docs/book/SUMMARY.md
  docs/book/driver-deployment/upgrade.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-2.1.0-candidate, size/M

#372 Static file volume test without specifying fstype
  tests/e2e/vsphere_file_volume_basic_mount.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#447 Add chethanv28 to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#436 Skip any stale policyIDs when watching StorageClasses
  pkg/syncer/storagepool/storageclasswatch.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#424 Add GetStorageVMotionPlan service to k8scloudoperator
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.pb.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.proto
  pkg/syncer/k8scloudoperator/placement.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#393 Address performance issues in existing volume health reconciler design
  pkg/syncer/metadatasyncer.go
  pkg/syncer/volume_health_reconciler.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#427 Add regex patterns for CnsRegisterVolume Spec params
  pkg/apis/cnsoperator/config/cnsregistervolume_crd.yaml
  pkg/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#416 Fix for Topology test cases
  tests/e2e/binding_modes_with_topology.go
  tests/e2e/invalid_topology_values.go
  tests/e2e/partial_topology_values.go
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/statefulset_with_topology.go
  tests/e2e/topology_aware_node_poweroff.go
  tests/e2e/volume_provisioning_with_topology.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#435 Truncate the volume name if the volume name is longer than 80 charact…
  pkg/common/cns-lib/volume/manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/M

#432 Allow multiple PV/PVC's to reference same volumeHandle
  docs/book/features/block_volume.md
  docs/book/features/file_volume.md
  pkg/syncer/fullsync.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/M

#443 Add volume migration crd cleanup go routine
  example/vanilla-k8s-block-driver/vsphere.conf
  pkg/apis/migration/migration.go
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/M

#425 Add vsanD disk decommission controller in syncer container
  go.mod
  go.sum
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.17/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.18/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.19/rbac/vsphere-csi-controller-rbac.yaml
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
  pkg/syncer/k8scloudoperator/placement.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/diskDecommissionController.go
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/storagepool/service.go
  pkg/syncer/storagepool/util.go
  pkg/syncer/types.go
  pkg/syncer/util.go
  pkg/syncer/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#457 Cherry pick recent commits to 2.1 branch
  docs/book/features/block_volume.md
  docs/book/features/file_volume.md
  example/vanilla-k8s-block-driver/vsphere.conf
  pkg/apis/migration/migration.go
  pkg/common/cns-lib/volume/manager.go
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#362 vSphere 7.0U2 feature - Online resize support for block volumes
  example/vanilla-k8s-block-driver/example-sc.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.19/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0u2/vanilla/rbac/vsphere-csi-node-rbac.yaml
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/identity.go
  pkg/csi/service/node.go
  pkg/csi/service/service.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#450 Handle volume creation failure in cnsregistervolume controller
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  tests/e2e/csi_static_provisioning_basic.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#421 Add validation for CnsRegisterVolume to check if storage policy belongs to namespace
  manifests/dev/vsphere-7.0/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u1/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u1/supervisorcluster/k8s-1.16/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.17/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.18/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.19/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.0/vsphere-7.0/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/util.go
  tests/e2e/csi_static_provisioning_basic.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#462 Make auth check interval configurable.
  example/vanilla-k8s-block-driver/vsphere.conf
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#460 Fix for vanilla file services solution in a VC deployment when there is no cluster available in a datacenter
  pkg/csi/service/common/vsphereutil.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/XS

#470 Upgrade the external-attacher to v2.0.0
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#469 add leaderElectionNamespace to syncer container
  cmd/syncer/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#471 Add default-fs parameter to provisioner args
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.1/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.1/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#474 Mitigate CVE-2020-15113 by upgrading etcd to 3.3.25
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#459 Add volume capabilities validation in Vanilla Create Volume Request
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  tests/e2e/vsphere_file_volume_basic.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#461 Update rules for customresourcedefinitions API
  manifests/dev/vsphere-7.0u2/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#475 Change the image prefix for external-attacher
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#476 cherry-pick commits to release 2.1 branch
  cmd/syncer/main.go
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  tests/e2e/vsphere_file_volume_basic.go
Labels: approved, cncf-cla: yes, lgtm, size/M
