Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2020-08, with the labels that each got.

#296 check migrated-to annotation before pushing vSphere volume's metadata to vCenter
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/L

#287 Set Storage Policy ID while registering migrated in-tree vSphere volume
  pkg/apis/migration/migration.go
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/cns-lib/vsphere/pbm.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/unittestcommon/types.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/L

#297 Make fss configmap configurable for Vanilla K8S
  example/vanilla-k8s-block-driver/vsphere.conf
  manifests/latest/vsphere-7.0/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/L

#304 Update rbac and deployment yamls
  manifests/latest/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/latest/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/latest/vsphere-7.0u1/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/M

#301 disable volume expansion for migrated volumes
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/M

#308 Check provisioner annotation for pvc/pv provisioned using in tree storage class
  pkg/csi/service/common/constants.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
  pkg/syncer/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.1.0-candidate, size/L

#310 vSphere CSI driver is not supported on Windows based vCenter Server
  docs/book/compatiblity_matrix.md
  docs/book/supported_features_matrix.md
  docs/book/upgrade_support_matrix.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#309 refactor vanilla controller operations workflows
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, release-2.1.0-candidate, size/L

#324 Added doc to clarify the max allowed characters for cluster-id
  docs/book/driver-deployment/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#329 Fix argument order to CreateCustomerResourceDefinition call
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#303 Consider storage-class annotation while fetching storage-class name from PVC
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
  pkg/syncer/k8scloudoperator/placement.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util.go
  pkg/syncer/util_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#335 Tidy go.mod file
  go.mod
  go.sum
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
