Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2021-10, with the labels that each got.

#1278 VMC TKG Upgrade Test scenario
  tests/e2e/docs/images/assign_policy_to_ns.png
  tests/e2e/docs/images/create_vmc_storage_policy.png
  tests/e2e/docs/vmc_tkg_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vmc_csi_deployments.go
  tests/e2e/vmc_upgrade_tkg.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1261 [e2e-test]: File volume tests automation for TKG
  tests/e2e/gc_rwx_reclaim_policy.go
  tests/e2e/util.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1283 [e2e-tests]: Adding automation tests for Statefulset using RWX for TKG
  tests/e2e/gc_rwx_statefulsets.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1307 Adding a feature switch to use service for placement engine prov and spec bump up
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1292 Added in memory idempotency support for CreateSnapshot by default
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1291 Metrics to track PVCSI Attach/Detach operations.
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1252 Increase QPS for csi-provisioner & csi-attacher in pvcsi yamls
  manifests/guestcluster/1.19/pvcsi.yaml
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes
