Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2021-08, with the labels that each got.

#1190 Use query async volume API in volume migration service
  pkg/apis/migration/migration.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1195 Update image tag to v2.3.0 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1204 Disable uuid checks on XFS
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1198 ListSnapshot implementation
  pkg/common/prometheus/metrics.go
  pkg/common/utils/utils.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
  pkg/csi/service/vanilla/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1212 Prevent volume expansion if snapshots are present
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1215 Use appropriate variable names for storage class creation in e2e tests
  tests/e2e/csi_cns_telemetry_statefulsets.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/labelupdates.go
  tests/e2e/statefulset_with_topology.go
  tests/e2e/statefulsets.go
  tests/e2e/topology_aware_node_poweroff.go
  tests/e2e/volume_health_test.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1221 Fix statefulsets cleanup in label updates test
  tests/e2e/csi_cns_telemetry_statefulsets.go
  tests/e2e/labelupdates.go
Labels: size/S, approved, cncf-cla: yes

#1211 Picked up the compatible datastore to create volume from snapshot if possible.
  pkg/common/utils/utils.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/vsphereutil.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1214 TKGS: Run node daemon set with hostNetwork set to true
  manifests/guestcluster/1.17/pvcsi.yaml
  manifests/guestcluster/1.18/pvcsi.yaml
  manifests/guestcluster/1.19/pvcsi.yaml
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1217 running vSphere CSI node daemonset pods with hostNetwork true
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes, release-2.3.0-candidate

#1218 [release-2.3] running vsphere-csi-node DaemonSet pod with hostNetwork true
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1223 tagging images for v2.3.0-rc.5 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1222 [release-2.2] Run vsphere-csi-node DaemonSet pod with hostNetwork true
  manifests/v2.2.2-rc.1/deploy/create-validation-webhook.sh
  manifests/v2.2.2-rc.1/deploy/generate-signed-webhook-certs.sh
  manifests/v2.2.2-rc.1/deploy/validatingwebhook.yaml
  manifests/v2.2.2-rc.1/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.2-rc.1/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.2-rc.1/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.2.2-rc.1/rbac/vsphere-csi-node-rbac.yaml
Labels: approved, lgtm, size/XL, cncf-cla: yes

#1225 [release-2.1] Run vsphere-csi-node DaemonSet pod with hostNetwork true
  manifests/v2.1.2.rc-1/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.2.rc-1/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.2.rc-1/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.2.rc-1/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.2.rc-1/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.2.rc-1/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.2.rc-1/vsphere-7.0u1/vanilla/deploy/create-validation-webhook.sh
  manifests/v2.1.2.rc-1/vsphere-7.0u1/vanilla/deploy/generate-signed-webhook-certs.sh
  manifests/v2.1.2.rc-1/vsphere-7.0u1/vanilla/deploy/validatingwebhook.yaml
  manifests/v2.1.2.rc-1/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.2.rc-1/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.2.rc-1/vsphere-7.0u1/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#1224 Added the limit check on number of snapshots per block volume when create snapshot
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/common/utils/utils.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1202 Introduce topologyCategories in vSphere config secret
  pkg/common/cns-lib/vsphere/virtualmachine.go
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1234 Update manifest folder name & image tag names to use the correct versioning scheme -2.1.2-rc.1
  manifests/v2.1.2-rc.1/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.2-rc.1/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.2-rc.1/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.2-rc.1/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.2-rc.1/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.2-rc.1/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.2-rc.1/vsphere-7.0u1/vanilla/deploy/create-validation-webhook.sh
  manifests/v2.1.2-rc.1/vsphere-7.0u1/vanilla/deploy/generate-signed-webhook-certs.sh
  manifests/v2.1.2-rc.1/vsphere-7.0u1/vanilla/deploy/validatingwebhook.yaml
  manifests/v2.1.2-rc.1/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.2-rc.1/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.2-rc.1/vsphere-7.0u1/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1236 Add hostNetwork=true and set dnsPolicy to ClusterFirstWithHostNet for Node DaemonSet in CSI 2.0
  manifests/v2.0.2-rc.1/vsphere-67u3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.2-rc.1/vsphere-67u3/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.2-rc.1/vsphere-67u3/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.2-rc.1/vsphere-7.0/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.2-rc.1/vsphere-7.0/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.2-rc.1/vsphere-7.0/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, lgtm, size/XL, cncf-cla: yes

#1231 Fix the format error for static pv example
  example/vanilla-k8s-block-driver/example-static-block-provisioning.yaml
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#1235 Revert back GA topology labels to beta when improved volume topology is disabled
  pkg/csi/service/node.go
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#1237 Cherry-pick PR (#1043) to 2.3 release
  pkg/common/cns-lib/volume/manager.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1238 tagging images for v2.3.0-rc.6 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1239 Tagging images as v2.3.0
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1240 v2.3.0 doc updates
  README.md
  docs/book/SUMMARY.md
  docs/book/compatiblity_matrix.md
  docs/book/driver-deployment/installation.md
  docs/book/driver-deployment/prerequisites.md
  docs/book/features/raw_block_volume.md
  docs/book/releases/v2.0.0.md
  docs/book/releases/v2.0.1.md
  docs/book/releases/v2.1.0.md
  docs/book/releases/v2.1.1.md
  docs/book/releases/v2.2.0.md
  docs/book/releases/v2.2.1.md
  docs/book/releases/v2.3.0.md
  docs/book/supported_features_matrix.md
Labels: kind/documentation, size/L, approved, lgtm, cncf-cla: yes

#1187 Update VCP to CSI migration documentation
  docs/book/features/vsphere_csi_migration.md
Labels: kind/documentation, approved, lgtm, size/M, cncf-cla: yes

#1220 publish workaround for RWM volumes becoming inaccessible after node daemonset pod restarts
  docs/book/driver-deployment/upgrade.md
Labels: kind/documentation, size/L, approved, lgtm, cncf-cla: yes

#1124 [e2e-tkg-rmx]: Rename ginkgo focus tag for rwx test for tkg
  tests/e2e/gc_rwx_basic.go
  tests/e2e/gc_rwx_readonly.go
  tests/e2e/gc_rwx_static_provision.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1253 Log that CSI Conf file can't be found when failing stat
  pkg/common/config/config.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1251 Fix sleep time in cns csi telemetry test case to wait for secret to be updated in the CSI containers
  tests/e2e/util.go
Labels: size/XS, approved, cncf-cla: yes

#1248 Add the idempotency support for CreateSnapshot and DeleteSnapshot
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller_test.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1078 [e2e-test]: Adding an automation test for Statically Provisioned ReadOnlyMany access Volume
  tests/e2e/gc_rwx_readonly.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1255 fixing base image tag and adding git commit to the base image
  images/driver-base/Dockerfile
  images/driver-base/Makefile
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1206 [e2e-test]: StatefulSet application using File volumes
  tests/e2e/file_volume_statefulsets.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1207 Create TKC in VMC Environment using Devops user
  tests/e2e/config.go
  tests/e2e/e2e_common.go
  tests/e2e/testing-manifests/tkg/tkg.yaml
  tests/e2e/util.go
  tests/e2e/vmc_create_gc.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes
