Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2021-03, with the labels that each got.

#661 updating documentation
  README.md
  docs/book/compatiblity_matrix.md
  docs/book/driver-deployment/prerequisites.md
  docs/book/limits.md
  docs/book/releases/v1.0.2.md
  docs/book/releases/v1.0.3.md
  docs/book/releases/v2.0.0.md
  docs/book/releases/v2.0.1.md
  docs/book/releases/v2.1.0.md
  docs/book/releases/v2.1.1.md
  docs/book/supported_features_matrix.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#662 [Part 1] Add TriggerCsiFullSync API
  cmd/syncer/main.go
  images/syncer/Dockerfile
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.17/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.18/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.19/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  pkg/csi/service/common/constants.go
  pkg/internal/cnsoperator/cnsfilevolumeclient/v1alpha1/groupversion_info.go
  pkg/internalapis/cnsoperator/apis.go
  pkg/internalapis/cnsoperator/cnsfilevolumeclient/cnsfilevolumeclient.go
  pkg/internalapis/cnsoperator/cnsfilevolumeclient/v1alpha1/cnsfilevolumeclient_types.go
  pkg/internalapis/cnsoperator/cnsfilevolumeclient/v1alpha1/zz_generated.deepcopy.go
  pkg/internalapis/cnsoperator/config/cnsfilevolumeclient_crd.yaml
  pkg/internalapis/cnsoperator/config/triggercsifullsync_crd.yaml
  pkg/internalapis/cnsoperator/register.go
  pkg/internalapis/cnsoperator/triggercsifullsync/v1alpha1/triggercsifullsync_types.go
  pkg/internalapis/cnsoperator/triggercsifullsync/v1alpha1/zz_generated.deepcopy.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#677 Removed QueryAllVolume in DeleteVolume workflow.
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/M

#672 Online resize documentation
  docs/book/README.md
  docs/book/features/volume_expansion.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/L

#682 Removed QueryAll in DeleteVolume.
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#671 Fix issue that fullsync returns with error 'Duplicated entity for each entity type in one cluster is found'
  docs/book/releases/v2.1.0.md
  docs/book/releases/v2.1.1.md
  pkg/syncer/fullsync.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/M

#688 Online resize documentation for vSphere 7.0U2/CSI 2.2
  docs/book/README.md
  docs/book/features/volume_expansion.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#690 Prevent GetVsanDatastores from throwing an error if a DC does not have datastores
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/XS

#689 Cherrypick fix of fullsync bug that CNS returns `Duplicated entity for each entity` to release-2.2 branch
  docs/book/releases/v2.1.0.md
  docs/book/releases/v2.1.1.md
  pkg/syncer/fullsync.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#693 updating go.mod dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, release-2.2.0-candidate, size/M

#691 [release-2.2 cherry-pick] Prevent GetVsanDatastores from throwing an error if a DC does not have datastores
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#697 Govmomi bump
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/XS

#694 Add empty datacenter issue to known issues for current 2.1.x releases
  docs/book/releases/v2.1.0.md
  docs/book/releases/v2.1.1.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#696 [cherry-pick-to 2.2] updating go.mod dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#702 [Cherry-pick] Add empty datacenter issue to known issues for current 2.1.x releases
  docs/book/releases/v2.1.0.md
  docs/book/releases/v2.1.1.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#695 Change YAML file to enable CSI on VMC support. Add doc for CSI on VMC support.
  docs/book/SUMMARY.md
  docs/book/features/vsphere_csi_vmc.md
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/M

#706 Modify document to describe CSI on VMC support.
  docs/book/features/vsphere_csi_vmc.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/XS

#708 Cherry-pick changes to enable CSI on VMC and document changes for CSI on VMC.
  docs/book/SUMMARY.md
  docs/book/features/vsphere_csi_vmc.md
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#683 Corrects incorrect fix in PR 664
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/labelupdates.go
  tests/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#659 svc-onlineVolumeExpansion-1
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#658 WCP Offline Volume Expansion Tests (First Set)
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#646 Add PVC name and namespace in the logs of csiGetVolumeHealthStatus method
  pkg/syncer/volume_health.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#705 Enhance create volume logging in pvCSI create volume
  pkg/csi/service/wcpguest/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#710 Update pvcsi yamls
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.20/pvcsi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#522 Avoid unnecessary warning messages in Syncer container for update pod metadata
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#712 Fvt prs for 2.2 12 mar21
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/labelupdates.go
  tests/e2e/util.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#699 TriggerCsiFullSync API and Controller Implementation
  cmd/syncer/main.go
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.20/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.17/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.18/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.19/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  pkg/apis/cnsoperator/register.go
  pkg/csi/service/common/constants.go
  pkg/internalapis/cnsoperator/config/triggercsifullsync_crd.yaml
  pkg/internalapis/cnsoperator/triggercsifullsync/v1alpha1/triggercsifullsync_types.go
  pkg/syncer/cnsoperator/controller/add_triggercsifullsync.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsvolumemetadata/cnsvolumemetadata_controller.go
  pkg/syncer/cnsoperator/controller/controller.go
  pkg/syncer/cnsoperator/controller/triggercsifullsync/triggercsifullsync_controller.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/pvcsi_fullsync.go
  pkg/syncer/syncer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#703 Cherry pick govmomi
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#707 Add documentation for cluster-distribution parameter in csi-vsphere.conf
  docs/book/SUMMARY.md
  docs/book/driver-deployment/installation.md
  docs/book/features/cns_telemetry.md
Labels: approved, cncf-cla: yes, lgtm, release-2.2.0-candidate, size/M

#711 Logout existing VC client if we encounter error while connecting to other components in VC
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/XS

#684 Add new field /status/capacity/allocatableSpace in Storage Pool CRD
  pkg/apis/storagepool/cns/v1alpha1/storagepool_types.go
  pkg/apis/storagepool/config/cns.vmware.com_storagepools.yaml
  pkg/syncer/k8scloudoperator/placement.go
  pkg/syncer/storagepool/intended_state.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#715 [Cherry-pick] Logout VC client if we encounter error while connecting
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#716 Update rbac yamls for vSphere 7.0u1
  manifests/dev/vsphere-7.0u1/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.0/vsphere-7.0u1/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/XS

#719 fixed rc images tag
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/validatingwebhook.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/validatingwebhook.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#720 Resolve inconsistencies in the vanilla YAMLs for different vSphere versions
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0u1/rbac/vsphere-csi-node-rbac.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#722 Add volume health timestamp in GC.
  pkg/syncer/volume_health_reconciler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#615 Ensure VMware CSI resources are deployed on an exclusive namespace `vmware-system-csi`
  example/vanilla-k8s-block-driver/example-sc-volume-expansion.yaml
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-67u3/vanilla/namespace.yaml
  manifests/dev/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-67u3/vanilla/rbac/vsphere-csi-node-rbac.yaml
  manifests/dev/vsphere-67u3/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0/vanilla/namespace.yaml
  manifests/dev/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0/vanilla/rbac/vsphere-csi-node-rbac.yaml
  manifests/dev/vsphere-7.0/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0u1/vanilla/create-validation-webhook.sh
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0u1/vanilla/generate-signed-webhook-certs.sh
  manifests/dev/vsphere-7.0u1/vanilla/namespace.yaml
  manifests/dev/vsphere-7.0u1/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u1/vanilla/validatingwebhook.yaml
  manifests/dev/vsphere-7.0u1/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0u2/vanilla/create-validation-webhook.sh
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0u2/vanilla/generate-signed-webhook-certs.sh
  manifests/dev/vsphere-7.0u2/vanilla/namespace.yaml
  manifests/dev/vsphere-7.0u2/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/vanilla/rbac/vsphere-csi-node-rbac.yaml
  manifests/dev/vsphere-7.0u2/vanilla/validatingwebhook.yaml
  manifests/dev/vsphere-7.0u2/vanilla/vsphere-csi-driver.yaml
  pkg/common/config/config.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator_test.go
  pkg/csi/service/common/commonco/utils.go
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/multi_master_k8s.go
  tests/e2e/vsphere_file_volume_basic_without_datacenter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#725 Fix typo in the error message formatting
  pkg/syncer/cnsoperator/controller/triggercsifullsync/triggercsifullsync_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#726 fix ginkgo focus tags for tests in vsphere_volume_disksize.go
  tests/e2e/vsphere_volume_disksize.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#724 Not run auth manager for file volumes if vSAN file services is not enabled
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/L

#704 fail volume creation when unable to retrieve AccessibleTopology of the volume
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/S

#727 Handling not found error for CnsFileAccessConfig in pvCSI ControllerUnPublishVolume
  pkg/csi/service/wcpguest/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#731 Enable CSI auth check in vSphere 67U3 and 7.0 manifests
  manifests/dev/vsphere-67u3/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0/vanilla/vsphere-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/XS

#734 [cherry-pick-to-2.2] fail volume creation when unable to retrieve AccessibleTopology of the volume
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#735 [Cherrypick] Not run auth manager for file volumes if vSAN file services is not enabled
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0/deploy/vsphere-csi-controller-deployment.yaml
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#730 Upgrade govmomi to v0.24.1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/XS

#737 Upgrade govmomi to v0.24.1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#736 Do not populate volumemanager for TKG as part of CnsOperator Init
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#721 define CnsCsiSvFeatureStatesSpec
  pkg/internalapis/apis.go
  pkg/internalapis/cnsoperator/cnsfilevolumeclient/cnsfilevolumeclient.go
  pkg/internalapis/featurestates/v1alpha1/types.go
  pkg/internalapis/featurestates/v1alpha1/zz_generated.deepcopy.go
  pkg/internalapis/register.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#746 Add CRD permissions for TKG and Vanilla CSI drivers
  manifests/dev/vsphere-67u3/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.20/pvcsi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#750 Fix typo in vSphere 7.0 Vanilla CSI YAML
  manifests/dev/vsphere-7.0/vanilla/vsphere-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#747 Assign clusterflavor to TriggerCsiFullSyncReconciler
  pkg/syncer/cnsoperator/controller/triggercsifullsync/triggercsifullsync_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#742 Refactor VMC related document.
  docs/book/SUMMARY.md
  docs/book/driver-deployment/installation.md
  docs/book/driver-deployment/prerequisites.md
  docs/book/features/vsphere_csi_vmc.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-2.2.0-candidate, size/M

#751 Cherry pick change "Refactor VMC related document" to release-2.2 branch.
  docs/book/SUMMARY.md
  docs/book/driver-deployment/installation.md
  docs/book/driver-deployment/prerequisites.md
  docs/book/features/vsphere_csi_vmc.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#740 Retry reloading vCenter secret config operation
  cmd/syncer/main.go
  go.mod
  go.sum
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/common/config/types.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/util.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsvolumemetadata/cnsvolumemetadata_controller.go
  pkg/syncer/cnsoperator/controller/controller.go
  pkg/syncer/cnsoperator/controller/triggercsifullsync/triggercsifullsync_controller.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/service.go
  pkg/syncer/syncer_test.go
  pkg/syncer/types.go
  pkg/syncer/types/commontypes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/L

#753 [cherry-pick-to-release-2.2] re-try reload config operation
  cmd/syncer/main.go
  go.mod
  go.sum
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/common/config/types.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/util.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsvolumemetadata/cnsvolumemetadata_controller.go
  pkg/syncer/cnsoperator/controller/controller.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/service.go
  pkg/syncer/syncer_test.go
  pkg/syncer/types.go
  pkg/syncer/types/commontypes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#743 vCenter version check to enable online volume expansion feature
  manifests/dev/vsphere-67u3/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0u1/vanilla/vsphere-csi-driver.yaml
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/M

#754 Fail gracefully if volume expansion is attempted on vSphere 6.7U3
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/S

#755 Cherry-pick resize PRs and create RC2 images
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/validatingwebhook.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/validatingwebhook.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/vsphere-csi-node-ds.yaml
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#739 Updated documentation for cluster-distribution in csi-vsphere.conf
  docs/book/SUMMARY.md
  docs/book/driver-deployment/installation.md
  docs/book/features/cns_telemetry.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-2.2.0-candidate, size/M

#741 publish nfsv4 datastore is not supported
  docs/book/compatiblity_matrix.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-2.2.0-candidate, size/XS

#758 Replacing the usage of CNS Query with QueryAll(with selection) to avoid SPBM workflows.
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.2.0-candidate, size/M

#718 Automation tests for CSI support for CNS Telemetry
  tests/e2e/config.go
  tests/e2e/csi_cns_telemetry.go
  tests/e2e/e2e_common.go
  tests/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#762 Replacing the usage of CNS Query with QueryAll(with selection) to avoid SPBM workflows
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#763 update images tag to v2.2.0-rc.3
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/validatingwebhook.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/validatingwebhook.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#756 Remove optional tag from cluster-distribution docs
  docs/book/driver-deployment/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#701 Add registerDisk & retrieveVStorageObject methods to support CSI migration on vsphere 67p04 and 7.0
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/cns-lib/vsphere/vslm.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
