Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2021-04, with the labels that each got.

#771 Fix fake attach error when PVC gets deleted before detach completes in WCP
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator_helper.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#761 Update driver manifests to indicate api version for CSIDriver based on k8s version
  manifests/dev/vsphere-67u3/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0/vanilla/vsphere-csi-driver.yaml
  manifests/v2.1.1/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.1/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#770 disable X_CSI_DEBUG on vsphere-csi-node container
  manifests/dev/vsphere-67u3/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0u1/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0u2/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#738 CSI migration support on vSphere67u3p04 and 7.0
  manifests/dev/vsphere-67u3/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0/vanilla/vsphere-csi-driver.yaml
  pkg/apis/migration/migration.go
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/common_controller_helper_test.go
  pkg/csi/service/common/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#764 supervisor feature switch states replications on workload namespaces
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.17/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.18/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.19/cns-csi.yaml
  pkg/csi/service/common/constants.go
  pkg/internalapis/featurestates/featurestates.go
  pkg/kubernetes/informers.go
  pkg/kubernetes/types.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#782 Fix fetch certificate file step in validation-webhook creation script
  manifests/dev/vsphere-7.0u1/vanilla/create-validation-webhook.sh
  manifests/dev/vsphere-7.0u2/vanilla/create-validation-webhook.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#776 add retry logic and refactor ReloadConfiguration for wcp and gc
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#777 Remove broken URLs and update installation documentation to make it generic across releases
  docs/book/driver-deployment/deploying_csi_with_zones.md
  docs/book/driver-deployment/installation.md
  docs/book/driver-deployment/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#781 Handle virtualmachine not found errors during pvcsi detach operation
  pkg/csi/service/wcpguest/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#779 e2e test - Create a Pod with securityContext and fsGroup
  tests/e2e/util.go
  tests/e2e/vsphere_volume_fsgroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#745 Reduced Poll timeout to check host status
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/volume_health_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#786 Add priority class for pvcsi deployment and daemon sets
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.20/pvcsi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#788 Add default fstype to pvcsi and cns-csi manifests
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.20/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.17/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.18/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.19/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.20/cns-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#792 keep single deployment for all vsphere releases for v2.2.0 release
  manifests/v2.2.0/deploy/create-validation-webhook.sh
  manifests/v2.2.0/deploy/generate-signed-webhook-certs.sh
  manifests/v2.2.0/deploy/validatingwebhook.yaml
  manifests/v2.2.0/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.2.0/rbac/vsphere-csi-node-rbac.yaml
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-67u3/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-67u3/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.2.0/vsphere-7.0/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.2.0/vsphere-7.0/rbac/vsphere-csi-node-rbac.yaml
  manifests/v2.2.0/vsphere-7.0u1/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0u1/rbac/vsphere-csi-node-rbac.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/create-validation-webhook.sh
  manifests/v2.2.0/vsphere-7.0u2/deploy/generate-signed-webhook-certs.sh
  manifests/v2.2.0/vsphere-7.0u2/deploy/validatingwebhook.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.0/vsphere-7.0u2/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.0/vsphere-7.0u2/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.2.0/vsphere-7.0u2/rbac/vsphere-csi-node-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#769 v2.2.0 release doc and removal of Supervisor and TKG Features
  README.md
  docs/book/SUMMARY.md
  docs/book/compatiblity_matrix.md
  docs/book/features/block_volume.md
  docs/book/features/file_volume.md
  docs/book/features/volume_expansion.md
  docs/book/features/volume_health.md
  docs/book/features/vsphere_csi_migration.md
  docs/book/known_issues.md
  docs/book/limits.md
  docs/book/overview.md
  docs/book/releases/v2.0.0.md
  docs/book/releases/v2.0.1.md
  docs/book/releases/v2.1.0.md
  docs/book/releases/v2.1.1.md
  docs/book/releases/v2.2.0.md
  docs/book/supported_features_matrix.md
  docs/book/troubleshooting.md
  example/sv-block-driver/static-block-provisioning-fcd.yaml
  example/sv-block-driver/static-block-provisioning-vmdk.yaml
  example/vanilla-k8s-file-driver/example-static-fileshare-provisioning.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-2.2.0-candidate, size/XL

#785 e2e-test - fix fsgroup pod test for wcp
  tests/e2e/vsphere_volume_fsgroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#791 Change leader-election flags
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.20/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.17/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.18/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.19/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.20/cns-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#795 Migration doc updates
  docs/book/features/vsphere_csi_migration.md
  manifests/dev/vsphere-7.0u2/vanilla/create-validation-webhook.sh
  manifests/v2.1.0/vsphere-7.0u1/deploy/create-validation-webhook.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#797 SV FSS Replication - Fix logging, Update RBAC for 1.20, and honor workloadnamespace label removal
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.20/cns-csi.yaml
  pkg/internalapis/featurestates/featurestates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#784 Use locks for virtualmachine updates in pvCSI attach & detach
  pkg/csi/service/wcpguest/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#798 update csi driver installation doc
  docs/book/driver-deployment/installation.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#783 FSS replication changes for GC
  cmd/syncer/main.go
  cmd/vsphere-csi/main.go
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.20/pvcsi.yaml
  pkg/apis/migration/migration.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/utils.go
  pkg/kubernetes/dynamicInformers.go
  pkg/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#760 Filter datastores for file volume creation in WCP
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/config/types.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#799 watch on cnscsisvfeaturestates deletion and add back cnscsisvfeaturestates CR in the namespace
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.17/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.18/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.19/cns-csi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.20/cns-csi.yaml
  pkg/internalapis/featurestates/featurestates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#803 Ignore supervisor FSS configmap updates in nodes
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#806 updating owners and security contacts
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#766 vcp2csi syncer tests first set and added migration verification for PV with ext3 FS
  go.sum
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_create_delete.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/vcp_utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#805 Fix for WCP test issues
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#809 Compare FSS data on an update event in k8sorchestrator before updating the cache
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/internalapis/featurestates/featurestates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#807 consolidate deployment yaml files for vanilla k8s
  manifests/dev/vanilla/create-validation-webhook.sh
  manifests/dev/vanilla/generate-signed-webhook-certs.sh
  manifests/dev/vanilla/namespace.yaml
  manifests/dev/vanilla/validatingwebhook.yaml
  manifests/dev/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-67u3/vanilla/namespace.yaml
  manifests/dev/vsphere-67u3/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0/vanilla/namespace.yaml
  manifests/dev/vsphere-7.0/vanilla/vsphere-csi-driver.yaml
  manifests/dev/vsphere-7.0u1/vanilla/create-validation-webhook.sh
  manifests/dev/vsphere-7.0u1/vanilla/generate-signed-webhook-certs.sh
  manifests/dev/vsphere-7.0u1/vanilla/namespace.yaml
  manifests/dev/vsphere-7.0u1/vanilla/validatingwebhook.yaml
  manifests/dev/vsphere-7.0u1/vanilla/vsphere-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#801 Disable X_CSI_SPEC_DISABLE_LEN_CHECK for CSI controller
  manifests/dev/vanilla/vsphere-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#789 Refactor isFileServiceEnabled workflow to avoid multiple calls to List Datacenters
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#819 Bump up attacher and provisioner sidecar containers
  manifests/dev/vanilla/vsphere-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#749 Bump Kubernetes and controller-runtime version.
  go.mod
  go.sum
  pkg/csi/service/node.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsvolumemetadata/cnsvolumemetadata_controller.go
  pkg/syncer/cnsoperator/controller/triggercsifullsync/triggercsifullsync_controller.go
  tests/e2e/binding_modes_with_topology.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/csi_static_provisioning_file_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/fullsync_test_for_file_volume.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/multi_master_k8s.go
  tests/e2e/operationstorm.go
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/util.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#828 fix run-e2e-test.sh
  hack/run-e2e-test.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#829 GC VolumeExpansion Testcase Fix
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#812 GC test fix in gc_block_volume_expansion.go
  tests/e2e/gc_block_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#835 fixed linter issues
  cnsctl/cmd/ov/cleanup.go
  cnsctl/cmd/ov/ls.go
  cnsctl/cmd/ov/ov.go
  cnsctl/cmd/ov/rm.go
  cnsctl/cmd/ova/cleanup.go
  cnsctl/cmd/ova/ls.go
  cnsctl/cmd/ova/ova.go
  cnsctl/cmd/root.go
  cnsctl/main.go
  hack/check-format.sh
  hack/check-golangci-lint.sh
  hack/check-lint.sh
  hack/check-staticcheck.sh
  pkg/common/cns-lib/volume/util.go
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/nodes.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/util.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/cnsoperator/util/util.go
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/svmotion_detached_volume.go
  tests/e2e/util.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_volume_disksize.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
