Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2021-02, with the labels that each got.

#625 Elaborate on file volume DNS setup step in documentation and add few Info logs for better debugging experience
  docs/book/features/file_volume.md
  docs/images/LOCATE-FILE-SERVICE-FQDN.png
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#610 Exposed create and delete volume metrices from WCP CSI controller.
  go.sum
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.17/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.18/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.19/vsphere-csi-controller.yaml
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#623 Implement GetClientVmsFromIPList for FileVolumeClient interface
  pkg/internal/cnsoperator/cnsfilevolumeclient/cnsfilevolumeclient.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#613 Configure ACLs for file volumes
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#636 add retries to deleteFCD() calls which follow PV delete call
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/labelupdates.go
  tests/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#601 Vanilla Online Volume resize test cases (First set)
  tests/e2e/util.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#639 Volume health status [Inaccessible] test cases
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/volume_health_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#648 removing duplicate row from Compatibility Matrix table
  docs/book/compatiblity_matrix.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#643 Identify datastore name from full datastore path
  docs/book/releases/v2.1.0.md
  pkg/apis/migration/migration.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#614 Refactoring cnsfileaccessconfig controller to configure net permissions for file volumes
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#651 Remove finalizer and invoke update on CnsFileAccessConfig CR when deletionTimeStamp is set
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#652 Fixed this message during build - package cnsctl is not in GOROOT
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#649 Exposed prometheus metrics for create, delete, attach and detach API s in vanilla CSI controller.
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  pkg/csi/service/common/prometheus/metrics.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#584 Prevent concurrent map write error in StoragePool Controller
  pkg/syncer/storagepool/intended_state.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#653 Amend volume resize known issues documentation. Also add missing env var in topology aware setup instructions
  docs/book/driver-deployment/deploying_csi_with_zones.md
  docs/book/features/volume_topology.md
  docs/book/releases/v2.0.0.md
  docs/book/releases/v2.0.1.md
  docs/book/releases/v2.1.0.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#624 vanilla vcreboot test
  tests/e2e/fullsync_test_for_file_volume.go
  tests/e2e/vc_reboot_volume_lifecycle.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#638 Added vanilla online resize test cases (2nd set)
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#656 Exposed CNS operation metrics.
  go.mod
  go.sum
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/common/prometheus/metrics.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#664 Ignore - The object or item referred to could not be found; err in deleteFcdWithRetriesForSpecificErr()
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/labelupdates.go
  tests/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#647 removing privileged securityContext from node-driver-registrar
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0/guestcluster/1.15/pvcsi.yaml
  manifests/dev/vsphere-7.0/guestcluster/1.16/pvcsi.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0u1/guestcluster/1.15/pvcsi.yaml
  manifests/dev/vsphere-7.0u1/guestcluster/1.16/pvcsi.yaml
  manifests/dev/vsphere-7.0u1/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#668 Add gocsi lock contention timeout in with new patch release
  manifests/v2.1.1/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.1/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.1/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.1/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.1/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.1/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.1/vsphere-7.0u1/vanilla/deploy/create-validation-webhook.sh
  manifests/v2.1.1/vsphere-7.0u1/vanilla/deploy/generate-signed-webhook-certs.sh
  manifests/v2.1.1/vsphere-7.0u1/vanilla/deploy/validatingwebhook.yaml
  manifests/v2.1.1/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.1/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.1/vsphere-7.0u1/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#640 Increase the Default Resource quota limit
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_full_sync.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/storagepolicy.go
  tests/e2e/util.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere_volume_disksize.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#650 using single instance of tagmanager for getting shared datastores in the topology
  pkg/common/cns-lib/vsphere/virtualmachine.go
  pkg/csi/service/node.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/vanilla/nodes.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#660 Revert "Assign full permissions for file volumes created in WCP"
  pkg/common/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#665 Add env variable for gocsi lock contention
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#642 Set cluster distribution in full sync for volumes created before upgrade
  go.mod
  go.sum
  pkg/syncer/fullsync.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#669 Disable root squash and perform hard mount for file volumes in TKGS
  pkg/csi/service/node.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#666 Running a http server in syncer container to expose prometheus metrics.
  cmd/syncer/main.go
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.17/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.18/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.19/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  pkg/common/cns-lib/volume/manager.go
  pkg/common/prometheus/metrics.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#675 Update images to v2.1.1
  manifests/v2.1.1/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.1/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.1/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.1/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.1/vsphere-7.0u1/vanilla/deploy/validatingwebhook.yaml
  manifests/v2.1.1/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.1/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#678 Copying YAMLs for v2.1.1 from release branch
  manifests/v2.1.1/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.1/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.1/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.1/vsphere-7.0u1/vanilla/deploy/create-validation-webhook.sh
  manifests/v2.1.1/vsphere-7.0u1/vanilla/deploy/generate-signed-webhook-certs.sh
  manifests/v2.1.1/vsphere-7.0u1/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
