Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2021-01, with the labels that each got.

#560 fix csi controller pod tolerations
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/supervisorcluster/k8s-1.16/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/validatingwebhook.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.17/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.18/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.19/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/validatingwebhook.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#557 Fix incorrect stamping of placement error on PVC
  pkg/syncer/k8scloudoperator/placement.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#568 Prevent physical volume deletion from syncer
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#574 Delete volume in syncer with delete disk set to false
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, size/M, v1.0.3

#578 Update driver deployment files with latest rc images
  manifests/deploy/vsphere-csi-controller-ss.yaml
  manifests/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#544 Add fake attach implementation in WCP controller
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.17/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.18/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.19/deploy/vsphere-csi-controller-deployment.yaml
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator_helper.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/util.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/types.go
  pkg/syncer/volume_health.go
  pkg/syncer/volume_health_reconciler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#567 Skip non-exisistent policies when refreshing storage class cache
  pkg/common/cns-lib/vsphere/pbm.go
  pkg/syncer/storagepool/storageclasswatch.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#499 add thumprint support for vsphere csi driver
  docs/book/driver-deployment/installation.md
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/config/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#571 Move node annotation listener initialization to InitStoragePoolService function
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#566 Fix static provisioning of PV in metadatasyncer
  docs/book/features/block_volume.md
  pkg/syncer/metadatasyncer.go
  pkg/syncer/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#576 Add vsphere-csi-controller yaml for SVC
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.17/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.18/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.19/vsphere-csi-controller.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.17/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.17/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.18/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.18/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.19/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/supervisorcluster/k8s-1.19/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#586 fixing 2.1.0 yaml files in release-2.1 branch
  manifests/v2.1.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#588 correcting args for csi-provisioner and csi-resizer and rbac rules
  manifests/v2.1.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#569 Enhance placement engine to honor node-affinity annotation
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
  pkg/syncer/k8scloudoperator/placement.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#589 adding default fstype ext4 for upgraded csi-provisioner
  manifests/v2.1.0/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#558 adding known issues for each release
  README.md
  docs/book/SUMMARY.md
  docs/book/known_issues.md
  docs/book/releases/v1.0.1.md
  docs/book/releases/v1.0.2.md
  docs/book/releases/v2.0.0.md
  docs/book/releases/v2.0.1.md
  docs/book/releases/v2.1.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#572 fix block mode volume stuck in termination (issue #338)
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#592 updating migration doc and adding installation steps for CPI
  docs/book/driver-deployment/prerequisites.md
  docs/book/features/vsphere_csi_migration.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#593 Update image for release-1.0.3
  manifests/deploy/vsphere-csi-controller-ss.yaml
  manifests/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS, v1.0.3

#594 Add release docs and manifest file for CSI release v1.0.3
  docs/book/SUMMARY.md
  docs/book/releases/v1.0.3.md
  manifests/v1.0.3/deploy/vsphere-csi-controller-ss.yaml
  manifests/v1.0.3/deploy/vsphere-csi-node-ds.yaml
  manifests/v1.0.3/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#595 Update the manifest file and Docs
  README.md
  docs/book/releases/v2.1.0.md
  manifests/v2.0.0/vsphere-67u3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-67u3/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-67u3/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.0/vsphere-7.0/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.0/vsphere-7.0/guestcluster/1.15/pvcsi.yaml
  manifests/v2.0.0/vsphere-7.0/guestcluster/1.16/pvcsi.yaml
  manifests/v2.0.0/vsphere-7.0/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.0/vsphere-7.0/supervisorcluster/k8s-1.15/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.0/vsphere-7.0/supervisorcluster/k8s-1.15/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.1/vsphere-67u3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.1/vsphere-67u3/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.1/vsphere-67u3/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.0.1/vsphere-7.0/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.0.1/vsphere-7.0/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.0.1/vsphere-7.0/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.0/vsphere-67u3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-67u3/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.0/vsphere-67u3/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.0/vsphere-7.0/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.0/vsphere-7.0/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.1.0/vsphere-7.0u1/deploy/create-validation-webhook.sh
  manifests/v2.1.0/vsphere-7.0u1/deploy/generate-signed-webhook-certs.sh
  manifests/v2.1.0/vsphere-7.0u1/deploy/validatingwebhook.yaml
  manifests/v2.1.0/vsphere-7.0u1/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.1.0/vsphere-7.0u1/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.1.0/vsphere-7.0u1/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#535 ControllerPublish volume for file volumes in pvCSI
  pkg/csi/service/wcpguest/controller.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#582 upgrading csi sidecar containers
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-67u3/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-67u3/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0/vanilla/rbac/vsphere-csi-controller-rbac.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u1/vanilla/deploy/vsphere-csi-node-ds.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-controller-deployment.yaml
  manifests/dev/vsphere-7.0u2/vanilla/deploy/vsphere-csi-node-ds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#559 ControllerUnPublishVolume for file volumes in TKGS
  pkg/csi/service/wcpguest/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#562 Cnsfileaccessconfig controller implementation
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.19/vsphere-csi-controller.yaml
  pkg/apis/cnsoperator/config/cnsfileaccessconfig_crd.yaml
  pkg/syncer/cnsoperator/controller/add_cnsfileaccessconfig.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/util.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#590 Determine external facing IP address of TKG VM NSX-T networking configuration
  pkg/syncer/cnsoperator/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#501 Handle WaitForCacheSync errors
  pkg/syncer/metadatasyncer.go
  pkg/syncer/resize_reconciler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#600 updating doc for compatibility, feature matrix and upgrade support
  docs/book/book.json
  docs/book/compatiblity_matrix.md
  docs/book/driver-deployment/upgrade.md
  docs/book/supported_features_matrix.md
  docs/book/upgrade_support_matrix.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#550 Implementation of CnsFileVolumeClient functions.
  pkg/apis/migration/migration.go
  pkg/internal/cnsoperator/cnsfilevolumeclient/cnsfilevolumeclient.go
  pkg/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#608 marking topology feature as beta and adding support statement
  docs/book/driver-deployment/deploying_csi_with_zones.md
  docs/book/features/volume_topology.md
  docs/book/supported_features_matrix.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#606 Adding infrastructure for buidling cnsctl tool, also adding commands and sub commands with empty implementation.
  Makefile
  cnsctl/cmd/ov/cleanup.go
  cnsctl/cmd/ov/ls.go
  cnsctl/cmd/ov/ov.go
  cnsctl/cmd/ov/rm.go
  cnsctl/cmd/ova/cleanup.go
  cnsctl/cmd/ova/ls.go
  cnsctl/cmd/ova/ova.go
  cnsctl/cmd/root.go
  cnsctl/main.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#603 Determine external facing IP address of TKG VM in vDS setups
  pkg/syncer/cnsoperator/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#605 Exposed prometheus metrics for create/delete volume operations in PVCSI
  go.mod
  go.sum
  manifests/dev/vsphere-7.0u2/guestcluster/1.17/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.18/pvcsi.yaml
  manifests/dev/vsphere-7.0u2/guestcluster/1.19/pvcsi.yaml
  pkg/csi/service/common/prometheus/metrics.go
  pkg/csi/service/service.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#616 Fix nil pointer dereference in volume health reconciler
  pkg/syncer/volume_health_reconciler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#602 Bump up govmomi to v0.24.1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#620 Revert "Use latest version of govmomi"
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#621 Bump up govmomi to v0.24.1
  go.mod
  go.sum
  tests/e2e/vsphere.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#619 Add utility method to get network provider from networking configmap in WCP
  pkg/syncer/cnsoperator/util/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#617 Add FSS checks for CnsFileAccessConfig controller init
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S
