Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2021-05, with the labels that each got.

#838 fix registering types to help initialize CNS operator
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#824 Exposed CSI attach, detach and expand volume metrics in CNS CSI and PVCSI
  pkg/common/prometheus/metrics.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#840 fixed detach volume error handling
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#790 e2e-test: Test for CSI-CNS Telemetry - Part2
  tests/e2e/csi_cns_telemetry.go
  tests/e2e/csi_cns_telemetry_statefulsets.go
  tests/e2e/csi_cns_telemetry_vc_reboot.go
  tests/e2e/e2e_common.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#818 wcp offline and online volume resize testcases
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#856 moving v1.0.2 and v1.0.3 yamls from master to release 1.0 branch
  manifests/v1.0.2/deploy/vsphere-csi-controller-ss.yaml
  manifests/v1.0.2/deploy/vsphere-csi-node-ds.yaml
  manifests/v1.0.2/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v1.0.3/deploy/vsphere-csi-controller-ss.yaml
  manifests/v1.0.3/deploy/vsphere-csi-node-ds.yaml
  manifests/v1.0.3/rbac/vsphere-csi-controller-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#859 Add k8s 1.21 yaml for Supervisor cluster
  manifests/dev/vsphere-7.0u2/supervisorcluster/1.21/cns-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#843 Spec for CnsVolumeOperationRequest Custom Resource
  pkg/internalapis/cnsvolumeoperationrequest/v1alpha1/cnsvolumeoperationrequest_types.go
  pkg/internalapis/cnsvolumeoperationrequest/v1alpha1/register.go
  pkg/internalapis/cnsvolumeoperationrequest/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#860 remove v1.0.1 references
  README.md
  docs/book/SUMMARY.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#847 set max volumes per node
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#850 fixed nil pointer access in volume health reconciler
  pkg/syncer/volume_health_reconciler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#864 Remove duplicate configmaps in 1.15 and 1.16 csi yamls for SVC
  manifests/supervisorcluster/1.15/cns-csi.yaml
  manifests/supervisorcluster/1.16/cns-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#852 Set health annotation to Inaccessible when it is not set
  pkg/csi/service/common/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#830 Support for CnsQueryAsyncVolume
  go.mod
  go.sum
  manifests/supervisorcluster/1.17/cns-csi.yaml
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/utils/utils.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
  pkg/syncer/volume_health.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#863 Create CnsVolumeOperationRequest definiton on API server and define VolumeOperationRequest interface
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/constants.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
  pkg/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#865 fixed misspell reported by golangci-lint
  pkg/syncer/k8scloudoperator/placement.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_create_delete.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_file_volume_basic_mount.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#874 Clean up logger.go
  pkg/csi/service/logger/logger.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#861 upgrading ci golang image
  images/ci/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#866 upgrading photon to 4.0
  images/driver-base/Dockerfile
  images/driver/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#878 Remove namespace creation from cns-csi yaml
  manifests/supervisorcluster/1.15/cns-csi.yaml
  manifests/supervisorcluster/1.16/cns-csi.yaml
  manifests/supervisorcluster/1.17/cns-csi.yaml
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#876 Clean up comments in pkg/kubernetes
  pkg/kubernetes/dynamicInformers.go
  pkg/kubernetes/informers.go
  pkg/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#839 vcp2csi migration tests syncer pod name update tests for statefulset and deployment
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_syncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#872 Simple cleanups for service.go
  pkg/csi/service/logger/logger.go
  pkg/csi/service/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#868 Watch ca file rotation in supervisor cluster and re-establish VC connection
  pkg/common/config/config.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#886 remove CPI installation requirement for topology feature
  docs/book/driver-deployment/deploying_csi_with_zones.md
  docs/book/driver-deployment/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#867 Cherry pick PR-840 to 2.2 branch
  hack/run-e2e-test.sh
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#879 Refactor code to remove redundant function calls and dependencies between packages
  pkg/apis/cnsoperator/register.go
  pkg/apis/migration/migration.go
  pkg/common/cns-lib/vsphere/virtualmachine.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/vanilla/nodes.go
  pkg/internalapis/cnsoperator/triggercsifullsync/v1alpha1/triggercsifullsync_types.go
  pkg/internalapis/featurestates/featurestates.go
  pkg/kubernetes/dynamicInformers.go
  pkg/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#875 operationRequestStore implementation of VolumeOperationRequest interface
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
  pkg/internalapis/cnsvolumeoperationrequest/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#887 Add a "Testing done" section in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#885 Clean up comments in vanilla controller
  pkg/csi/service/vanilla/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#882 clean up comments in nodes.go
  pkg/csi/service/vanilla/nodes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#888 Doc updates
  docs/book/compatiblity_matrix.md
  docs/book/driver-deployment/prerequisites.md
  docs/book/overview.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#895 Clean up server.go
  pkg/csi/service/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#889 Clean up comments in authmanager
  pkg/csi/service/common/authmanager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#902 Fix disk decomm failure due to password rotation
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/storagepool/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#851 Statically provision VMDK used by a PV provisioned by VCP using CSI
  go.mod
  go.sum
  hack/check-lint.sh
  tests/e2e/e2e_common.go
  tests/e2e/vcp_to_csi_create_delete.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#880 Verify in-line volume creation on the migrated node
  tests/e2e/vcp_to_csi_syncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#834 Added GC online volume resize test cases
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#903 ginkgo bump to 1.16.2
  go.mod
  go.sum
  tests/e2e/docs/vanilla_cluster_setup.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#901 Use appropriate query volume API in full sync and other places
  pkg/common/utils/utils.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/volume_health.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#891 using logger.GetNewContextWithLogger and removed unnecessary context creation.
  go.mod
  go.sum
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/internalapis/featurestates/featurestates.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsvolumemetadata/cnsvolumemetadata_controller.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#907 GC Testcase fix
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_metadata_syncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#900 Clean up manager.go
  pkg/common/cns-lib/volume/manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#894 Clean up long lines in nodes.go
  pkg/csi/service/vanilla/nodes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#896 Clean up virtualcenter.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#911 clean up long lines in informers.go
  pkg/kubernetes/informers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#915 Clean up pbm.go
  pkg/common/cns-lib/vsphere/pbm.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#912 Clean up cnsctl
  cnsctl/cmd/ov/cleanup.go
  cnsctl/cmd/ov/ls.go
  cnsctl/cmd/ov/ov.go
  cnsctl/cmd/ov/rm.go
  cnsctl/cmd/ova/cleanup.go
  cnsctl/cmd/ova/ls.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#906 Add methods to log and return an error
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/logger/logger.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#909 use fixed versions for linter check tools
  Makefile
  docs/book/development.md
  hack/check-format.sh
  hack/check-golangci-lint.sh
  hack/check-lint.sh
  hack/check-staticcheck.sh
  hack/run-e2e-test.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#918 clean up authmanager.go
  pkg/csi/service/common/authmanager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#922 Remove file path check from reload config event
  pkg/csi/service/wcp/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#897 Modify Volume Manager to handle idempotency
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/vanilla/nodes.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
  pkg/internalapis/cnsvolumeoperationrequest/util.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/diskDecommissionController.go
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/syncer_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#921 Clean up white spaces in common_controller_helper.go
  pkg/csi/service/common/common_controller_helper.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#927 Upgrade sidecars in WCP
  manifests/supervisorcluster/1.17/cns-csi.yaml
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#928 Add default fstype parameter to cns-csi yamls
  manifests/supervisorcluster/1.17/cns-csi.yaml
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
