Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2021-06, with the labels that each got.

#923 Use LogNewErrorCodef for syncer util.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#871 Volume health timestamp annotation
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/volume_health_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#914 Clean up white spaces in vsphere/utils.go
  pkg/common/cns-lib/vsphere/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#916 Add a few request validations for node RPCs
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#920 Use LogNewErrorCodef in node.go
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#934 Clean up white spaces in config.go
  pkg/common/config/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#946 Fix trivial typo in comments for config.go
  pkg/common/config/config.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#926 Updated logger info, Added Polling waits and handled cleanup routine in label update and static provisioning tests
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/labelupdates.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#898 Create volume implementation with idempotency handling
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/common/unittestcommon/types.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#904 Delete Volume implementation with idempotency handling
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#953 Add permissions for cnsvolumeoperationrequest instances
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/constants.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#936 Use LogNewErrorCodef in utils
  pkg/common/unittestcommon/utils.go
  pkg/common/utils/utils.go
  pkg/csi/service/common/authmanager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#947 Introduce CSINodeTopology CRD
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/constants.go
  pkg/internalapis/csinodetopology/csinodetopology.go
  pkg/internalapis/csinodetopology/v1alpha1/csinodetopology_types.go
  pkg/internalapis/csinodetopology/v1alpha1/register.go
  pkg/internalapis/csinodetopology/v1alpha1/zz_generated.deepcopy.go
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#945 Clean up white spaces in fullsync.go
  pkg/syncer/fullsync.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#957 Continue using gocsi in vanilla flavor for 2.3
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#944 Set volume health to inaccessible when PVC not found in CNS
  pkg/syncer/types.go
  pkg/syncer/volume_health.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#960 Add pvcsi 1.21 yaml
  manifests/guestcluster/1.21/pvcsi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#917 environment configuration *.md files for running e2e tests updated
  tests/e2e/docs/guest_cluster_setup.md
  tests/e2e/docs/supervisor_cluster_setup.md
  tests/e2e/docs/vanilla_cluster_setup.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#908 GC onlineVolumeResize on statically provisioned PVC
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/util.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#932 Update Aftereach() to restore vsan-health/sps services even if test fails
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/fullsync_test_for_file_volume.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/volume_health_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#952 Clean up white spaces in placement
  pkg/syncer/k8scloudoperator/placement.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#951 Cleanup of stale CnsVolumeOperationRequest CRD instances
  example/vanilla-k8s-block-driver/vsphere.conf
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#935 Extend volume implementation with idempotency handling
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#963 Enhance log in k8scloudoperator.go.
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#938 Use LogNewErrorCodef in node.go - 2/2
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#940 Use LogNewError in migration.go
  pkg/apis/migration/migration.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#965 Changes to pvcsi full sync to push cluster-distribution if it doesnt match
  pkg/syncer/pvcsi_fullsync.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#941 Fix for GC Test Cases
  tests/e2e/data_persistence.go
  tests/e2e/util.go
  tests/e2e/volume_health_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#970 deployment yamls for v2.2.1 release
  manifests/v2.2.1/deploy/create-validation-webhook.sh
  manifests/v2.2.1/deploy/generate-signed-webhook-certs.sh
  manifests/v2.2.1/deploy/validatingwebhook.yaml
  manifests/v2.2.1/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.1/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.1/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.2.1/rbac/vsphere-csi-node-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#973 v2.2.1 documentation
  README.md
  docs/book/SUMMARY.md
  docs/book/compatiblity_matrix.md
  docs/book/releases/v2.2.1.md
  docs/book/supported_features_matrix.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#929 SVC - Online resize test cases (set4)
  tests/e2e/docs/supervisor_cluster_setup.md
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#899 Update dependencies for k8s v1.21.1 support
  go.mod
  go.sum
  hack/run-e2e-test.sh
  pkg/csi/service/node.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/csi_static_provisioning_file_basic.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/labelupdates.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#967 Fix VC Config init in Syncer
  pkg/csi/service/wcp/controller.go
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#961 External snapshot validation webhook yaml file
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#978 Modify CSI image tag and revert changes to manifest files that are not needed for 2.3 release.
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#950 Clean up white spaces in k8scloudoperator.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#971 Use LogNewErrorCodef in wcp controller
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#985 Start with a lower case letter for error messages
  pkg/common/utils/utils.go
  pkg/csi/service/node.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#948 CSI Snapshot FSS and expose snapshot capability.
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#954 Script to deploy VolumeSnapshot CRDs, snapshot-controller and external snapshot validation webhook
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#972 Add support for Snapshot configuration
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/config/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#987 Updated vmware/govmomi in go.mod to take the go bindings of latest CNS snapshot APIs
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#988 Clean up white space in cnsoperator/util/util.go
  pkg/syncer/cnsoperator/util/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#983 Change PKS to TKGI in readme and installation guide
  docs/book/README.md
  docs/book/driver-deployment/installation.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#979 raw block volume
  docs/book/SUMMARY.md
  docs/book/features/raw_block_volume.md
  example/vanilla-k8s-block-driver/example-raw-block-pod.yaml
  example/vanilla-k8s-block-driver/example-raw-block-pvc.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-2.3.0-candidate, size/M

#968 use self-signed certificate for validation webhook
  manifests/vanilla/create-validation-webhook.sh
  manifests/vanilla/deploy-vsphere-csi-validation-webhook.sh
  manifests/vanilla/generate-signed-webhook-certs.sh
  manifests/vanilla/validatingwebhook.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#981 Print "GuestClusterID" when reconcile cnsvolumemetadata CR.
  pkg/syncer/cnsoperator/controller/cnsvolumemetadata/cnsvolumemetadata_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#993 update username requirements
  docs/book/driver-deployment/installation.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm

#989 misspell fixes on the repository
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#986 Log volumeId string instead of Cns VolumeID struct in create volume call
  pkg/common/cns-lib/volume/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#994 enable misspell golangci-linter on the repository
  .golangci.yml
  pkg/common/cns-lib/vsphere/utils.go
  tests/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#998 Update GC E2E Test Readme File
  tests/e2e/docs/guest_cluster_setup.md
  tests/e2e/docs/images/raid_0_policy.png
  tests/e2e/docs/images/thick_policy.png
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#873 e2e-test: Adding test for "Delete Namespace" usecase & Static provision of PV by same name twice
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/operationstorm.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1001 Clean up white spaces in apis
  pkg/apis/cnsoperator/cnsregistervolume/v1alpha1/cnsregistervolume_types.go
  pkg/apis/cnsoperator/cnsvolumemetadata/v1alpha1/cnsvolumemetadata_types.go
  pkg/apis/storagepool/apis.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#964 NodeGetInfo and RBAC changes for topology feature improvement
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/node.go
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
  pkg/internalapis/csinodetopology/csinodetopology.go
  pkg/kubernetes/kubernetes.go
  pkg/kubernetes/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#977 Bump up golang version to 1.16
  go.mod
  images/ci/Dockerfile
  images/driver/Dockerfile
  images/syncer/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1011 Add CallerSkip option for logger wrappers
  pkg/csi/service/logger/logger.go
  pkg/csi/service/logger/logger_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.3.0-candidate, size/M

#997 [e2e]: File volume support for TKG - Part1, basic utilities
  tests/e2e/e2e_common.go
  tests/e2e/gc_rmx_static_provision.go
  tests/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1012 [cherry-pick-2.3] Add CallerSkip option for logger wrappers (#1011)
  pkg/csi/service/logger/logger.go
  pkg/csi/service/logger/logger_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1013 Add check for CSI volume spec in PVUpdated method
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-2.3.0-candidate, size/XS

#1015 Cherry-pick PR (#1013) to rel 2.3 - Add check for CSI volume spec in PVUpdated method
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1009 Clean up white spaces in utils.go
  pkg/common/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1002 Clean white spaces in triggercsifullsync_controller.go
  pkg/syncer/cnsoperator/controller/triggercsifullsync/triggercsifullsync_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1006 Clean up white spaces in cns-lib
  pkg/common/cns-lib/volume/util.go
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/cns-lib/vsphere/virtualmachine.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1007 Clean up white spaces in migration.go
  pkg/apis/migration/migration.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#969 Introduce controller for CSINodeTopology CR
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/cnsoperator/controller/add_csinodetopology.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1014 Add benchmarks for LogNewError methods
  pkg/csi/service/logger/logger_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1021 Clean white spaces in cnsvolumemetadata_controller
  pkg/syncer/cnsoperator/controller/cnsvolumemetadata/cnsvolumemetadata_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1019 Bump up govmomi to 0.26.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1020 Update CSI images to rc.2
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1024 [e2e-test]: RWX automation - Adding utilities for CnsFileAccessConfig CRD creation and deletion
  tests/e2e/e2e_common.go
  tests/e2e/gc_rwx_static_provision.go
  tests/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1026 Set QPS and burst for external attacher in supervisor
  manifests/supervisorcluster/1.17/cns-csi.yaml
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1008 Enable csi-auth-check and file-volume features in supervisor
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1022 Clean up white spaces in cnsregistervolume
  pkg/syncer/cnsoperator/controller/cnsregistervolume/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#931 Script to Create and Delete PVCs Synchronously
  tests/e2e/e2e_common.go
  tests/e2e/scale.go
  tests/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1030 Clean up white spaces in cnsfilevolumeclient
  pkg/internalapis/cnsoperator/cnsfilevolumeclient/cnsfilevolumeclient.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1018 Clean up white spaces in featurestates
  pkg/internalapis/featurestates/featurestates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1027 Clean up white spaces in metadatasyncer
  pkg/syncer/metadatasyncer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1035 Clean up white spaces under vsphere
  pkg/common/cns-lib/vsphere/hostsystem.go
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1036 Clean up white spaces in node
  pkg/csi/service/node.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1037 Clean white spaces in kubernetes
  pkg/kubernetes/dynamicInformers.go
  pkg/kubernetes/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1041 Clean up white spaces in vanilla helper
  pkg/csi/service/vanilla/controller_helper.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1044 Clean up white spaces in admissionhandler
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/admissionhandler/validatestorageclass.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#996 Use LogNewErrorf in wcp/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1042 Clean up white spaces in csi_cns_telemetry
  tests/e2e/csi_cns_telemetry.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1043 Reset Volume Manager during reload config & ca file rotation
  pkg/common/cns-lib/volume/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1032 [e2e-test]: Basic RWX volume provisioning automation tests
  tests/e2e/gc_rwx_basic.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1034 [e2e-test]: RWX Automation - ReadOnlyMany usecase
  tests/e2e/gc_rwx_readonly.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1054 Enable file volume feature for TKG clusters
  manifests/guestcluster/1.17/pvcsi.yaml
  manifests/guestcluster/1.18/pvcsi.yaml
  manifests/guestcluster/1.19/pvcsi.yaml
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1053 Clean up white spaces in cnsnodevmattachment
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#982 Detect Homless Pod Error
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  pkg/csi/service/common/constants.go
  pkg/syncer/k8scloudoperator/placement.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
