Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2022-07, with the labels that each got.

#1832 [Cherry-pick to release-2.6] Remove the option to use gocsi
  cmd/vsphere-csi/main.go
  go.mod
  go.sum
  manifests/guestcluster/1.18/pvcsi.yaml
  manifests/guestcluster/1.19/pvcsi.yaml
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/provider/provider.go
  pkg/csi/service/driver.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1831 Check datastore compatibility before considering preference in topology
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/types/types.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes, release-2.6.0-candidate

#1834 Cherry-pick 1831: Check datastore compatibility before considering preference in topology
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/types/types.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1820 Update cert-manager.io API version from v1alpha3 to v1
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1837 Avoid duplicate datastores in CNS CreateVolume Spec
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1838 [Cherry-pick #1837]: Avoid duplicate datastores in CNS CreateVolume Spec
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1836 Tag RC2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1839 Enhance error logging before reporting metrics to Prometheus
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1842 bump CSI provisioner to v3.2.1
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: approved, lgtm, cncf-cla: yes, release-2.6.0-candidate

#1840 Framework 1.23 update for 2.6 branch
  go.mod
  go.sum
  pkg/csi/service/mounter/mounter_windows.go
  pkg/syncer/storagepool/util.go
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_rwx_destructive.go
  tests/e2e/gc_rwx_statefulsets.go
  tests/e2e/gc_rwx_tkg_scale.go
  tests/e2e/nodes_scaleup_scaledown.go
  tests/e2e/statefulsets.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1844 [Cherry-pick to release-2.6] bump CSI provisioner to v3.2.1 (#1842)
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1845 [Cherry-pick to release-2.6] Connect to Pbm client before invoking pbm methods
  pkg/common/cns-lib/vsphere/pbm.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1843 Fix volume provisioning issue with SC with no storage policy parameter
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes, release-2.6.0-candidate

#1846 [Cherry-pick 2.6] Fix volume provisioning issue with SC with no storage policy parameter
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1835 Change function "ListDataCenters" to add logic to connect to VC
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-2.6.0-candidate

#1847 [Cherry-pick 2.6] Fix issue in ListDatacenters and filterDatastores
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1848 Tag rc3 images for 2.6 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1849 Correct the improper image tag
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1854 migrate pre-provisioned in-tree vsphere volumes
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
  pkg/syncer/util_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1858 Fix bug in fetching VC instance in preferential deployment feature
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-2.6.0-candidate

#1860 [Cherry-pick #1858] Fix bug in fetching VC instance in preferential deployment feature
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1855 fix minor yaml lint issue
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-2.6.0-candidate

#1862 (Cherry-pick #1855) fix minor yaml lint issue
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1861 Tag RC4 images for 2.6 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1865 tag v2.6.0 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1866 Enable FSS for preferential deployment feature
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-2.6.0-candidate

#1867 (Cherry-pick #1866) Enable FSS for preferential deployment feature
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1868 [e2e-test]: Add new test for snapshot delete when it does not exists
  tests/e2e/csi_snapshot_basic.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1806 pvCSI support for uTKGS
  pkg/apis/cnsoperator/cnsvolumemetadata/v1alpha1/cnsvolumemetadata_types.go
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/syncer/cnsoperator/types/types.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1870 Collecting csi pod logs before restart of daemonset
  tests/e2e/file_volume_statefulsets.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1869 Topology L2 - Code fix for checking actual and expected error message
  tests/e2e/volume_provisioning_with_topology.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1876 Explicitly set the min TLS version to 1.2
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1878 update owners
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1877 set priorityclass for CSI controller and increased timeout for liveness probe
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1874 [Snapshot-e2e]: Adding mini-scale test for snapshot feature
  tests/e2e/csi_snapshot_basic.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1822 Return success for DetachVolume when nodeName in PodSpec is not same as nodeName in DetachVolume request
  pkg/common/fault/constants.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/wcp/controller.go
Labels: approved, size/M, cncf-cla: yes

#1841 vol allocation tests part 2
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/util.go
  tests/e2e/vsphere.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1882 [e2e-test]: Initialize full sync wait time variable in Idempotency test
  tests/e2e/improved_csi_idempotency.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1824 Return resource conflict fault for Update operation failure on API server
  pkg/common/fault/constants.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: approved, size/M, cncf-cla: yes

#1873 CreateSnapshot and DeleteSnapshot implementation on Supervisor
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator_helper.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/util.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcp/controller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1879 mark volume detach as success when Node vm is deleted from vcenter
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1851 Fix list-volume feature null pointer exception
  pkg/csi/service/wcp/controller_helper.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1886 Volume health test fix
  tests/e2e/volume_health_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1884 post vsan-health/sps svc start wait for all VASA providers to be online
  tests/e2e/connection.go
  tests/e2e/csi_cns_telemetry_vc_reboot.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/fullsync_test_for_file_volume.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/gc_rwx_service_down.go
  tests/e2e/gc_rwx_syncer.go
  tests/e2e/gc_rwx_volume_health.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/util.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_full_sync.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#1891 handle pv not found error during pv cleanup after snapshot deletion
  tests/e2e/csi_snapshot_basic.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1897 remove usage of deprecated io/ioutil package
  pkg/common/cns-lib/node/nodes.go
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/config/config.go
  pkg/common/fault/constants.go
  pkg/common/unittestcommon/utils.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/driver.go
  pkg/csi/service/osutils/linux_os_utils.go
  pkg/csi/service/osutils/os_utils_test.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller_test.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
  pkg/syncer/storagepool/storageclasswatch.go
  pkg/syncer/storagepool/util.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util_test.go
  tests/e2e/connection.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/gc_rwx_destructive.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_syncer.go
  tests/e2e/gc_rwx_tkg_scale.go
  tests/e2e/gc_rwx_volume_health.go
  tests/e2e/nimbus_utils.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/storage_policy_utils.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_full_sync.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_volume_expansion.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1893 add a connect() after service restart
  tests/e2e/util.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1888 ListSnapshot implementation on Supervisor
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcp/controller_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#1890 Report CSI Snapshot capabilities on Supervisor
  pkg/csi/service/wcp/controller.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1889 CreateVolume from Snapshot implementation on Supervisor
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1887 Prevent Volume Deletion and Expansion if it has Snapshots on Supervisor
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes
