Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2022-12, with the labels that each got.

#2087 CSI full sync in a multi VC setup
  pkg/syncer/cnsoperator/controller/triggercsifullsync/triggercsifullsync_controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2114 set max 5 vcenter server limit for multi vCenter deployment
  pkg/common/config/config.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2106 Config secret - Verifying vol attachment by updating config secret with different testuser credentials
  tests/e2e/config_secret.go
  tests/e2e/config_secret_utils.go
  tests/e2e/e2e_common.go
  tests/e2e/util.go
Labels: needs-ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#2116 remove printing vc credentials in the error log
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2113 Changes to fix GC TestCase Intermittent Issues
  tests/e2e/gc_block_volume_expansion.go
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#2120 Preferential topology code fix for verifying pv node affinity details when shared datastore is chosen for preference
  tests/e2e/preferential_topology.go
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#2099 Enable list volumes FSS in vanilla and WCP
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2119 Full Sync volumeInfo CRs
  pkg/internalapis/cnsvolumeinfo/cnsvolumeinfoservice.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2123 Map volumeID to correct nodeUUID, in multi-VC configuration with duplicate VM reference values across different VCs
  pkg/csi/service/vanilla/controller_helper.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2121 Fix a bug by checking whether the type of fault is nil or not
  pkg/common/cns-lib/volume/util.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2126 fix getBlockVolumeIDToNodeUUIDMap for multi vCenter deployment
  pkg/csi/service/vanilla/controller_helper.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2124 Update csi liveness probe to 2.8.0
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2125 Update csi-spec to 1.7.0
  go.mod
  go.sum
  pkg/common/cns-lib/node/manager.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2115 remove cnsctl tool
  Makefile
  cnsctl/cmd/ov/cleanup.go
  cnsctl/cmd/ov/ls.go
  cnsctl/cmd/ov/ov.go
  cnsctl/cmd/ov/rm.go
  cnsctl/cmd/ova/cleanup.go
  cnsctl/cmd/ova/ls.go
  cnsctl/cmd/ova/ova.go
  cnsctl/cmd/root.go
  cnsctl/main.go
  go.mod
  go.sum
  hack/check-format.sh
Labels: approved, lgtm, size/XL, cncf-cla: yes

#2130 Add k8s 1.24 support to 1.24/pvcsi.yaml
  manifests/guestcluster/1.24/pvcsi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2133 update govmomi to latest version [v0.30.0]
  go.mod
  go.sum
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2136 Added unit test job in the pipeline.
  .gitlab-ci.yml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2137 Removed rule to trigger the pipeline on all commits and not just on merge request events.
  .gitlab-ci.yml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2138 Added build-images job to build the driver and syncer images.
  .gitlab-ci.yml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2134 support non-topology single vCenter deployment when multi-vcenter-csi-topology enabled
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/vanilla/controller.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2139 updated error message
  tests/e2e/storagepolicy.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes
