Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2022-09, with the labels that each got.

#1956 Tag v2.5.3-rc.2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1955 Tag v2.6.1-rc.2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1957 Tag v2.4.3-rc.2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1958 Return correct faultype in cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1939 snapshot tests for topology
  tests/e2e/topology_snapshot.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1912 Volume allocation tests PART-2
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/vcp_to_csi_syncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1907 TKGS HA Automation PART-2
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/util.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#1961 Container kill code fix for different k8s version
  tests/e2e/topology_multi_replica.go
  tests/e2e/topology_operation_strom_cases.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#1966 fall back to look up the node by name
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1945 Enable Suspend Volume Provisioning on datastore FSS
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, needs-ok-to-test, approved, lgtm, cncf-cla: yes

#1965 Fixing list-volumes to use supervisorID instead of clusterID in cnsQueryFilter
  pkg/csi/service/wcp/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1968 Return proper error message when nodes are not ready in topology environment
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1972 tag v2.4.3 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#1971 fix node discovery when nodes are not upgraded to v2.5.0
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1975 Revert "cns-csi.yaml changes for k8s 1.24 (#1875)"
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1977 tag v2.5.3 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1802 Relocate volume tests using cnsRelocateVolume API
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/storage_policy_utils.go
  tests/e2e/svmotion_detached_volume.go
  tests/e2e/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1980 upgraded k8s dependencies to latest version
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1978 tag images for v2.6.1 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1984 Add env variable to accept SHA1 certificates with Go1.18+
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1985 tag v2.5.4-rc.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1986 tag v2.6.2-rc.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1982 [cherry pick 1971 to release 2.6] fix node discovery when nodes are not upgraded (#1971)
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1983 [cherry pick 1971 to release 2.5] fix node discovery when nodes are not upgraded (#1971)
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1987 enable max-pvscsi-targets-per-vm feature
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1989 fix make check error: rm deprecated grpc usage, update golangci-lint to 1.49.0
  .golangci.yml
  hack/check-golangci-lint.sh
  pkg/csi/service/wcp/controller_helper.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1990 [cherry pick 1989 into release-2.7] fix make check error
  .golangci.yml
  hack/check-golangci-lint.sh
  pkg/csi/service/wcp/controller_helper.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1976 Replace QueryVolume API with QueryVolumeUtil API(with selection), wherever applicable
  go.mod
  go.sum
  pkg/common/utils/utils.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1988 Updating the driver and syncer images to v2.7.0-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1735 Volume health check testcases - code fix when injecting psod on esxi hosts
  tests/e2e/util.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, lifecycle/rotten

#1996 fix GetSystemUUID to return correct VM UUID for Windows Nodes
  pkg/csi/service/osutils/windows_os_utils.go
Labels: size/S, approved, lgtm, cncf-cla: yes, release-2.7.0-candidate

#1998 Eliminate use of problematic url.Parse()
  pkg/csi/service/server.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-2.7.0-candidate

#2003 Add SHA1 fix and enable cnsmgr-suspend-create-volume FSS in 1.24 cns-csi
  manifests/supervisorcluster/1.24/cns-csi.yaml
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#2005 Cherry pick windows support fixes to release 2.7
  pkg/csi/service/osutils/windows_os_utils.go
  pkg/csi/service/server.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2006 Cherry-pick windows support fixes from #1996 and #1998
  hack/check-golangci-lint.sh
  pkg/csi/service/osutils/windows_os_utils.go
  pkg/csi/service/server.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2008 update driver and syncer images to tag v2.6.2-rc.2
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2007 Cherrypick release-2.5: fix GetSystemUUID to return correct VM UUID for Windows Nodes (#1996)
  hack/check-golangci-lint.sh
  pkg/csi/service/osutils/windows_os_utils.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2009 update driver and syncer images to tag v2.5.4-rc.2
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2011 [cherry-pick 2.5] fall back to look up node by name (#1966)
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, cncf-cla: yes

#2010 [cherry-pick 2.6]fall back to look up node by name (#1966)
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, cncf-cla: yes

#2012 tag v2.6.2-rc.3 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#2013 tag v2.5.4-rc.3 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#2015 tag driver and syncer images to v2.7.0-rc.2
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2017 add multi-vcenter-csi-topology feature gate
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/constants.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2001 Password change for k8s vm
  tests/e2e/e2e_common.go
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#2021 Cherry-pick Enable Suspend Volume Provisioning on datastore FSS (#1945)
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2020 Cherry-pick Enable Suspend Volume Provisioning on datastore FSS (#1945)
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes
