Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2022-04, with the labels that each got.

#1552 Adding wcp related functions for listVolume API
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1681 Bump up sidecars & configure leader election args to avoid too many restarts
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/S, approved, cncf-cla: yes

#1686 Bump up sidecars for wcp 1.22 & 1.21
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: approved, size/M, cncf-cla: yes

#1687 Bump up liveness-probe for WCP
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/XS, approved, cncf-cla: yes

#1617 Error message fix for online volume expansion when sps service is down
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1688 Code fix for Topology automation test scenario
  tests/e2e/volume_provisioning_with_level5_topology.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1682 replace cluster-id with new supervisor-id with CSI full sync
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/util.go
  pkg/syncer/cnsoperator/controller/cnsvolumemetadata/cnsvolumemetadata_controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/pv_to_backingdiskobjectid_mapping.go
  pkg/syncer/volume_health.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1640 Stretched cluster tests PART 7
  tests/e2e/e2e_common.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1697 fix syncer crash
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1645 E2E automation tests for snapshot provisioning with deletion policy set to "Retain"
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/util.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1657 Update CNS-CSI to 3 replica deployment in YAML
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1701 set maxUnavailable to 1 to enable RollingUpdate for CSI Node DaemonSet
  manifests/guestcluster/1.17/pvcsi.yaml
  manifests/guestcluster/1.18/pvcsi.yaml
  manifests/guestcluster/1.19/pvcsi.yaml
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1702 Check if vm and disk association exists in detach volume for supervisor
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcp/controller.go
Labels: size/L, approved, cncf-cla: yes

#1684 Topology automation disruptive testcases part4
  tests/e2e/e2e_common.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/topology_site_down_cases.go
  tests/e2e/util.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#1706 Update golang.org/x/crypto for CVE-2022-27191
  go.mod
  go.sum
Labels: size/S, approved, lgtm, cncf-cla: yes

#1708 Validate storageTopologyType in GC
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1689 [TKGs-HA] Change clusterComputeResourceMoId from string to slice in AZ CR
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/util.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1690 Fix GetNodesForVolumes to return a map of volumeID to nodeNames
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1704 prefix supervisor ID with `vSphereSupervisorID-`
  pkg/common/config/config.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1566 Stretched cluster tests part 4
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1573 [e2e-snapshot-test]: Adding destructive automation tests for snapshot operation
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/util.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#1696 bump up maxAllowedBlockVolumesPerNode to 255 for vSphere 8.0
  pkg/csi/service/node.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1699 [E2E-Test] Adding snapshot automation test - part 4
  tests/e2e/csi_snapshot_basic.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1713 update csi-node-driver-registrar config for Guest Cluster
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1700 Set the internal disk decommission FSS to true
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1716 Removing resource limits on webhook as it is crashing in high scale environments
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1710 Removed CNS_NEW_SYNC FSS logic from online volume expansion testcode
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vsphere_volume_expansion.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1666 Topology testcases when invalid topology labels specified
  tests/e2e/e2e_common.go
  tests/e2e/topology_new_node_with_different_labels.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1717 get feature-gates status during webhook server initialization
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/validatepvc.go
  pkg/syncer/admissionhandler/validatepvc_test.go
  pkg/syncer/admissionhandler/validatestorageclass.go
  pkg/syncer/admissionhandler/validatestorageclass_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1718 Return NotFound grpc error code for podVM not found
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
Labels: size/S, approved, ok-to-test, cncf-cla: yes

#1677 Stretched tests PART 9
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1722 Topology automation testcode fix for password rotation and full sync
  tests/e2e/topology_multi_replica.go
  tests/e2e/volume_provisioning_with_level5_topology.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1725 Change honnef staticcheck version from master to 2022.1.1
  hack/check-staticcheck.sh
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1724 Remove deprecated --health-port from csi node driver registrar container args
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1340 Fix metadata syncer for static PV
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1726 [TKGs-HA] Handle case where WCP CreateVolume response is returned by idempotency feature
  pkg/common/utils/utils.go
  pkg/csi/service/wcp/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1728 Handle ManagedObjectNotFound errors during CreateSnapshot
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/csi/service/vanilla/controller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1729 Fix duplicate volume additions to VirtualMachine Custom Resource
  pkg/csi/service/wcpguest/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1727 use correct context instead of context.TODO()
  cmd/syncer/main.go
  pkg/common/cns-lib/node/manager.go
Labels: size/XS, approved, lgtm, cncf-cla: yes
