Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2022-02, with the labels that each got.

#1499 Topology testcases for 2 level topology enabled testbed
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/statefulset_with_topology.go
  tests/e2e/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1503 TKGS-HA Supervisor CreateVolume workflow
  manifests/supervisorcluster/1.22/cns-csi.yaml
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/types/types.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/util.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1490 Polling-changes for GC tests
  tests/e2e/csi_cns_telemetry_vc_reboot.go
  tests/e2e/e2e_common.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/util.go
  tests/e2e/vc_reboot_volume_lifecycle.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1456 [e2e-test]: Add test for PVC claiming the available resource in parallel
  tests/e2e/gc_rwx_parallel_claim.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1487 fetch node VM uuid from csinode when use-csinode-id FSS is enabled
  tests/e2e/binding_modes_with_topology.go
  tests/e2e/csi_cns_telemetry_vc_reboot.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/labelupdates.go
  tests/e2e/multi_master_k8s.go
  tests/e2e/operationstorm.go
  tests/e2e/partial_topology_values.go
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/statefulsets.go
  tests/e2e/storagepolicy.go
  tests/e2e/topology_aware_node_poweroff.go
  tests/e2e/util.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/volume_provisioning_with_topology.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_shared_datastore.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
  tests/e2e/vsphere_volume_fstype.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1519 fix volume expand issue with improved-Idempotency feature and add vSphere 8.0 support
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, lgtm, size/M, cncf-cla: yes, release-2.5.0-candidate

#1521 Cherry-pick #1519 to release 2.5 branch
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1520 Update CSI driver and syncer images to 2.5.0 rc1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1518 Update the error type check of NotFound in DeleteSnapshot
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/utils.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1528 Avoid setting provisioner annotation
  pkg/csi/service/wcpguest/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1530 Update the error type check of NotFound in DeleteSnapshot
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/utils.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-2.5.0-candidate

#1535 Support storage-provisioner GA annotation for k8s 1.23
  pkg/syncer/util.go
  pkg/syncer/util_test.go
Labels: approved, lgtm, cncf-cla: yes, release-2.5.0-candidate

#1536 Cherry-pick PR #1535 to release-2.5 branch
  pkg/syncer/util.go
  pkg/syncer/util_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1527 Bump up sidecar containers in vanilla manifest YAML
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, needs-ok-to-test, approved, lgtm, cncf-cla: yes, release-2.5.0-candidate

#1496 Add the FSS for ListVolume API
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/constants.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1537 Cherry pick PR #1527 to release-2.5 branch
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, needs-ok-to-test, approved, lgtm, cncf-cla: yes

#1494 Added tests for vsan-stretched cluster testing - PART 1
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1542 Fix image tag and commit for release branches
  hack/release.sh
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-2.5.0-candidate

#1545 Prevent filevolume creation on a stretched cluster setup
  pkg/csi/service/wcp/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1534 Fixed the VC login failure in CSI during WCP password rotation
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/csi/service/wcp/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1546 Update restrictions on filevolume creation in a tkgs ha setup
  pkg/csi/service/wcpguest/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1547 Cherry pick PR #1542 to release-2.5 branch
  hack/release.sh
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1524 Automation test-cases for Topology Table2
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/volume_provisioning_with_level5_topology.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#1551 Improve csi snapshot deployment script
  manifests/vanilla/deploy-csi-snapshot-components.sh
Labels: size/S, approved, lgtm, cncf-cla: yes

#1516 Pv to BackingDiskObjectId mapping
  go.mod
  go.sum
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/constants.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/pv_to_backingdiskobjectid_mapping.go
  pkg/syncer/types.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, release-2.5.0-candidate

#1553 [Crossport]Improve csi snapshot deployment script (#1551)
  manifests/vanilla/deploy-csi-snapshot-components.sh
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1560 Cherry pick PR #1516 to release-2.5 branch
  go.mod
  go.sum
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/constants.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/pv_to_backingdiskobjectid_mapping.go
  pkg/syncer/types.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1561 Specify QPS and Burst for csi-snapshotter
  manifests/vanilla/deploy-csi-snapshot-components.sh
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1563 Crossport PR 1554: Fix in DeleteSnapshot to handle ManagedObjectNotFound error properly
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/csi/service/vanilla/controller_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1564 update image tags with v2.5.0-rc.2
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#1555 support oidc
  hack/check-format.sh
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/labelupdates.go
  tests/e2e/storagepolicy.go
  tests/e2e/vsphere_volume_expansion.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1517 remove dependency on driver packages from e2e tests - part1
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/e2e_common.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/gc_rwx_destructive.go
  tests/e2e/gc_rwx_multi_gc.go
  tests/e2e/gc_rwx_multi_ns_gc.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_service_down.go
  tests/e2e/suite_test.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_create_delete.go
  tests/e2e/vmc_delete_tkg.go
  tests/e2e/volume_health_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1568 change PVC annotation keys for TKGS HA
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcpguest/controller_helper.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1529 Add arg to disable gocsi in SV and pvcsi yamls
  manifests/guestcluster/1.18/pvcsi.yaml
  manifests/guestcluster/1.19/pvcsi.yaml
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1569 Fix linter error introduced from PR 1516
  pkg/csi/service/common/common_controller_helper.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/pv_to_backingdiskobjectid_mapping.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes, release-2.5.0-candidate

#1572 Cherry pick for fix linter error introduced from PR 1516 (#1569)
  pkg/csi/service/common/common_controller_helper.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/pv_to_backingdiskobjectid_mapping.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1580 bump up CSI provisioner for TKGS HA
  manifests/supervisorcluster/1.22/cns-csi.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1510 Vsphere conf changes for ListVolume API change
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/config/config.go
  pkg/common/config/types.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1583 CSI snapshot deployment script improvements
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
Labels: size/L, approved, lgtm, cncf-cla: yes

#1585 Always report CREATE_DELETE_SNAPSHOT and LIST_SNAPSHOTS capabilities
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1586 [Cherry-pick]CSI snapshot deployment script improvements (#1583)
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
Labels: size/L, approved, lgtm, cncf-cla: yes

#1581 Add docs for PV to BackingDiskObjectId mapping
  docs/book/features/pv_to_backingdiskobjectid_mapping.md
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1582 Driver packages dependency removal from e2e topology code
  tests/e2e/volume_provisioning_with_level5_topology.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1587 [Cherry-pick]Always report snapshot capabilities (#1585)
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1589 [Cherry pick] Add docs for PV to BackingDiskObjectId mapping (#1581)
  docs/book/features/pv_to_backingdiskobjectid_mapping.md
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1594 update image tags with v2.5.0-rc.3
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1549 Filter out datastores that are in suspended mode
  go.mod
  go.sum
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/cns-lib/vsphere/datastore.go
  pkg/common/cns-lib/vsphere/hostsystem.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/utils_test.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/utils/utils.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/syncer_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1595 Cherry-pick - Add a check for custom attributes to filter out datastores which are suspended
  go.mod
  go.sum
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/cns-lib/vsphere/datastore.go
  pkg/common/cns-lib/vsphere/hostsystem.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/utils_test.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/utils/utils.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/syncer_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1591 Bump up external provisioner version
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1601 Enable Decouple CSI from CPI feature
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-2.5.0-candidate

#1602 Cherry-pick request to enable Decouple CSI from CPI feature
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1603 Update image tags with v2.5.0-rc.4
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, needs-ok-to-test, approved, lgtm, cncf-cla: yes

#1607 Perform snapshot queries only on Block volumes during delete
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1608 [Cherry-pick]Perform snapshot queries only on Block volumes during delete (#1607)
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1609 Add volumetype check for pv to backingdiskobject mapping to fix type casting error
  pkg/syncer/pv_to_backingdiskobjectid_mapping.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1610 [Cherry-pick] Add volumetype check for pv to backingdiskobject mapping (#1609)
  pkg/syncer/pv_to_backingdiskobjectid_mapping.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1613 Cherry pick PR 1487 1550 1517 to 2.5
  tests/e2e/binding_modes_with_topology.go
  tests/e2e/csi_cns_telemetry_vc_reboot.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/gc_rwx_destructive.go
  tests/e2e/gc_rwx_multi_gc.go
  tests/e2e/gc_rwx_multi_ns_gc.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_service_down.go
  tests/e2e/labelupdates.go
  tests/e2e/multi_master_k8s.go
  tests/e2e/operationstorm.go
  tests/e2e/partial_topology_values.go
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/statefulsets.go
  tests/e2e/storagepolicy.go
  tests/e2e/suite_test.go
  tests/e2e/topology_aware_node_poweroff.go
  tests/e2e/util.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_create_delete.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/vmc_delete_tkg.go
  tests/e2e/volume_health_test.go
  tests/e2e/volume_provisioning_with_topology.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_shared_datastore.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
  tests/e2e/vsphere_volume_fstype.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1508 VMC VC Cert rotate scenario
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vmc_vc_cert_rotate.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1575 Enable block-volume-snapshot FSS in vanilla
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1618 [Crossport] Enable block-volume-snapshot FSS in vanilla and Patch CSI snapshotter sidecar
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, needs-ok-to-test, approved, lgtm, cncf-cla: yes
