Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2022-11, with the labels that each got.

#2002 Fix NewInformer() to return Informer instance with appropriate client associated
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/internalapis/featurestates/featurestates.go
  pkg/kubernetes/informers.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/service.go
  pkg/syncer/syncer_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2069 add VCenterServer to OperationDetails for improved idempotency
  pkg/common/cns-lib/volume/manager.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
  pkg/internalapis/cnsvolumeoperationrequest/config/cns.vmware.com_cnsvolumeoperationrequests.yaml
  pkg/internalapis/cnsvolumeoperationrequest/util.go
  pkg/internalapis/cnsvolumeoperationrequest/v1alpha1/cnsvolumeoperationrequest_types.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/diskDecommissionController.go
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/syncer_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2046 Set worker threads to 25 for csi-attacher to process high volume of concurrent attach-detach operations
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
Labels: size/XS, approved, cncf-cla: yes

#2063 Update snapshot validation webhook deployment
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
Labels: approved, lgtm, size/M, cncf-cla: yes

#2071 supervisor: upgrade provisioner, attacher, and resizer sidecars
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2077 ListVolume bug fix introduced in PR-2051
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2050 Multi VC support - PV delete metadatasyncer changes,
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2080 Don't resize volume if already correct size.
  pkg/csi/service/osutils/windows_os_utils.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2076 Fix issue in getting vCenter with MultiVCenterCSITopology FSS enabled in single VC config
  pkg/csi/service/vanilla/controller_helper.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2070 Metadata syncer changes for pod updates to support multi-VC config
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2075 [File volume] skip datastore computations for improved idempotency feature if task for registered VC is persisted in the idempotency CR
  pkg/csi/service/vanilla/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2079 Fix the pagination logic for list volumes
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2065 Fix tests for staging env
  tests/e2e/staging_env_basic.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#2078 updating latest ngnix and busybox pod images
  tests/e2e/e2e_common.go
  tests/e2e/testing-manifests/statefulset/nginx/statefulset.yaml
  tests/e2e/vmc_csi_deployments.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1760 Config secret - Util methods along with testcase - updating vsphere conf file with different testuser credentials
  tests/e2e/config_secret.go
  tests/e2e/config_secret_utils.go
  tests/e2e/e2e_common.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2073 Preferential Topology disruptive testcases - Putting Preferred datastore in suspended,power off or in MM mode state
  tests/e2e/e2e_common.go
  tests/e2e/nimbus_utils.go
  tests/e2e/preferential_topology_disruptive.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/util.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2086 CreateSnapshot and DeleteSnapshot changes to support multi-vCenter CSI topology
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2024 Add validation to check compatible datastore accessible from all vms
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/utils_test.go
  pkg/common/fault/constants.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2082 Initialize CSI migration service correctly for single-VC setup when multi-vc-csi-topology FSS enabled.
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2081 Add lock to protect FSS values in K8Sorchestrator instance
  pkg/common/unittestcommon/types.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2045 Bug Fix for device is already deleted while unmount volume
  pkg/csi/service/osutils/linux_os_utils.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2094 Changes to fix TC failure: Create volume when CNS goes down - idempotency
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2102 syncer: fix nil pointer dereference in log message
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2092 disable ComputeFSEnabledClustersToDsMap service in authmanager for multivCenter
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2101 Log improvement for CSI Authorization Service to identify log for specific vCenter server
  pkg/csi/service/common/authmanager.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2100 CreateVolume changes for multi-VC
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/nodes.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualmachine.go
  pkg/common/unittestcommon/utils.go
  pkg/common/utils/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/common/placementengine/types.go
  pkg/csi/service/common/topology.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/internalapis/cnsvolumeinfo/cnsvolumeinfoservice.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/metadatasyncer.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#2104 GC Testcases Fix
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/util.go
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#2105 Fix initialisation of vCenterInstances map for multi VC deployment
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2108 Collect final errors while iterating over VCs in a multi-VC CreateVolume call
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2088 Create file volume return non-storage fault when vSAN file service is disabled
  pkg/common/fault/constants.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1949 fss(disabled): use govmomi listview to wait for CNS tasks
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/listview_if.go
  pkg/common/cns-lib/volume/listview_test.go
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/manager_test.go
  pkg/common/cns-lib/volume/taskmap.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/diskDecommissionController.go
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/syncer_test.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#2095 ListSnapshots changes to support multi-VC configuration
  pkg/csi/service/vanilla/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2109 create volume on single vc with multivCenterCSITopologyEnabled
  pkg/csi/service/vanilla/controller.go
Labels: size/L, approved, lgtm, cncf-cla: yes
