Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2022-08, with the labels that each got.

#1900 Revert PR 1884
  tests/e2e/connection.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/util.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_volume_expansion.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1871 Code fixes for Level-5 topology testcases
  tests/e2e/topology_multi_replica.go
  tests/e2e/util.go
  tests/e2e/volume_provisioning_with_level5_topology.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1903 Add env variable to accept SHA1 certificates with Go1.18
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1899 Adding kavyashree-r to reviewers and approvers lists for tests/e2e fo…
  tests/e2e/OWNERS
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1905 Update replica count to 3 in SV 1.21 YAML
  manifests/supervisorcluster/1.21/cns-csi.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1898 Adding disk health checks
  pkg/common/cns-lib/vsphere/hostsystem.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1908 Fix YAML indentation in SVC 1.21
  manifests/supervisorcluster/1.21/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1909 enabled csi-migration feature
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1906 Prevent reconciliation if CSINodeTopology instance is already at Success state
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1901 CreateSnapshot and DeleteSnapshot implementation on Guest
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/kubernetes/kubernetes.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1902 Report CSI Snapshot capabilities on Guest if block-volume-snapshot FSS is enabled
  pkg/csi/service/wcpguest/controller.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1856 policy based vol allocation tests part 3
  tests/e2e/policy_driven_vol_allocation.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1859 fix for nil user session
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1918 fix linter issues
  pkg/common/cns-lib/node/nodes.go
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/config/config.go
  pkg/common/fault/constants.go
  pkg/common/unittestcommon/utils.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/driver.go
  pkg/csi/service/osutils/linux_os_utils.go
  pkg/csi/service/osutils/os_utils_test.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller_test.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
  pkg/syncer/storagepool/storageclasswatch.go
  pkg/syncer/storagepool/util.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util_test.go
  tests/e2e/connection.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/gc_rwx_destructive.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_syncer.go
  tests/e2e/gc_rwx_tkg_scale.go
  tests/e2e/gc_rwx_volume_health.go
  tests/e2e/nimbus_utils.go
  tests/e2e/storage_policy_utils.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_full_sync.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_volume_expansion.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1910 [Cherry-pick 2.6 #1906] Prevent reconciliation if CSINodeTopology instance is already at Success state
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1917 [Cherry-pick 2.6 #1879] mark volume detach as success when Node vm is deleted from vcenter
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1921 linter fixes in release-2.5
  pkg/common/cns-lib/node/nodes.go
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/config/config.go
  pkg/common/fault/constants.go
  pkg/common/unittestcommon/utils.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/driver.go
  pkg/csi/service/osutils/linux_os_utils.go
  pkg/csi/service/osutils/os_utils_test.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller_test.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
  pkg/syncer/storagepool/storageclasswatch.go
  pkg/syncer/storagepool/util.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util_test.go
  tests/e2e/connection.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/gc_rwx_destructive.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_syncer.go
  tests/e2e/gc_rwx_tkg_scale.go
  tests/e2e/gc_rwx_volume_health.go
  tests/e2e/nimbus_utils.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_full_sync.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_volume_expansion.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1922 linter fixes in release-2.4
  pkg/common/cns-lib/node/nodes.go
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/config/config.go
  pkg/common/fault/constants.go
  pkg/common/unittestcommon/utils.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/driver.go
  pkg/csi/service/osutils/linux_os_utils.go
  pkg/csi/service/osutils/os_utils_test.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller_test.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
  pkg/syncer/storagepool/storageclasswatch.go
  pkg/syncer/storagepool/util.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util_test.go
  tests/e2e/connection.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_full_sync.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_volume_expansion.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1924 [Cherry-pick 2.5 #1879] mark volume detach as success when Node vm is deleted from vcenter
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1920 Check for cns finalizer using the most recent pvc object
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: size/XS, approved, cncf-cla: yes

#1925 [Cherry-pick 2.5 #1906] Prevent reconciliation if CSINodeTopology instance is already at Success state
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1927 tag v2.5.3-rc.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1929 tag v2.6.1-rc.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1928 tag 2.4.3-rc.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1914 CreateVolumeFromSnapshot implementation in Guest
  pkg/csi/service/wcpguest/controller.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1915 ListSnapshot implementation for Guest
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1931 tag v2.4.3-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#1934 Initialize volumeIDToNameMap and enable operations on the map
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: approved, size/M, cncf-cla: yes

#1880 TKG HA automation - PART 1
  tests/e2e/e2e_common.go
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/util.go
Labels: needs-ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#1943 Improve logs in authmanager.
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1933 Update Go to 1.19
  go.mod
  hack/release.sh
  images/ci/Dockerfile
  images/driver/.dockerignore
  images/driver/Dockerfile
  images/syncer/Dockerfile
  images/windows/driver/Dockerfile
Labels: size/S, approved, lgtm, cncf-cla: yes

#1938 Change vcenter port environment variable name
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/common/config/config.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1944 Improve the code by removing the for loop in processQueryResultsListVolumes
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1763 Relocate volume tests for policy driven volume allocation
  tests/e2e/e2e_common.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vsphere.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#1946 Pick CSI namespace from environment variable in idempotency feature
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1951 [2.6 Cherry-pick 1946] Pick CSI namespace from environment in idempotency feature
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1952 [2.5 Cherry-pick 1946] Pick CSI namespace from environment in idempotency feature
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1953 [2.4 Cherry-pick 1946] Pick CSI namespace from environment in idempotency feature
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes
