Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2022-03, with the labels that each got.

#1596 Add 1.23 pvcsi yaml
  manifests/guestcluster/1.23/pvcsi.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#1606 set timeout for GetPodVMUUIDAnnotation to 4 minutes
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1620 Cherry-pick : Add 1.23 pvcsi yaml
  manifests/guestcluster/1.23/pvcsi.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#1622 Release vSphere CSI driver v2.5.0
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1619 Add 1.23 yaml for SV
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#1489 Vsan stretched cluster tests [PART-2]
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1604 VMC Test to Create CNSRegister Volume on Management datastore
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/docs/vmc_tkg_setup.md
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1599 Add example for Grafana dashboard for CSI.
  grafana-dashboard/CSI-CNS-Dashboard-v1.0.json
  grafana-dashboard/CSI-Dashboard-v1.0.json
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#1614 static provisioning - import VMDK testFix
  tests/e2e/csi_static_provisioning_basic.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1598 Change scope of TriggerCsiFullSync CRD from Namespaced to Cluster
  pkg/internalapis/cnsoperator/config/triggercsifullsync_crd.yaml
  pkg/syncer/cnsoperator/manager/init.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1624 Code fix for ClusterDistributionValue for Guest Cluster
  tests/e2e/csi_cns_telemetry_statefulsets.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1540 Add volumeAttachement listeners
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator_test.go
  pkg/kubernetes/informers.go
  pkg/kubernetes/types.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1633 Optional custom repository support for golang docker builder image
  hack/release.sh
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1635 unbound variable fix
  hack/release.sh
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1592 Stretched tests Part 5
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1562 Set disk online before filesystem resize
  pkg/csi/service/mounter/mounter_windows.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1637 Read UUID from product_serial in node daemonset instead of product_uuid file
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/node.go
  pkg/csi/service/osutils/linux_os_utils.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1643 Cherry-pick : Read UUID from product_serial in node daemonset (#1637)
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/node.go
  pkg/csi/service/osutils/linux_os_utils.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1623 Retry the logic to identify the pod mapped to a volume in case of failure
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
Labels: approved, ok-to-test, size/M, cncf-cla: yes

#1648 Create 2.5.1 RC1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1625 Add non storage fault for CSI attach and handle vm not found in CSI Attach for WCP
  go.mod
  pkg/common/fault/constants.go
  pkg/common/prometheus/metrics.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
Labels: size/L, approved, cncf-cla: yes

#1647 stretched Test fix for leader change scenarios
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1650 Optional custom repository support for golang docker builder image
  hack/release.sh
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1626 Add CSI webhook in Supervisor and add validating handler for TKGS HA
  manifests/supervisorcluster/1.22/cns-csi.yaml
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/validatepvcannotation.go
  pkg/syncer/admissionhandler/validatepvcannotation_test.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1636 fix inline in-tree vsphere volume registration
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1649 Optional custom repository support for golang docker builder image
  hack/release.sh
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1654 tag v2.2.3 release
  manifests/v2.2.3/deploy/validatingwebhook.yaml
  manifests/v2.2.3/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.3/deploy/vsphere-csi-node-ds.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1652 Handle NotFound fault for UpdateVolumeMetadata method in CnsVolumeMetadata controller
  pkg/syncer/cnsoperator/controller/cnsvolumemetadata/cnsvolumemetadata_controller.go
Labels: size/XS, approved, cncf-cla: yes

#1664 staticcheck fixes
  Makefile
  hack/check-staticcheck.sh
  hack/run-e2e-test.sh
  pkg/csi/service/vanilla/controller_test.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1630 Stretched cluster tests PART 6
  tests/e2e/e2e_common.go
  tests/e2e/vsan_stretched_cluster.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1669 fail volume creation when zones labels not found in volume accessibilityRequirements on stretched supervisor cluster
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1632 Remove FSS guard for online volume expansion feature
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/node.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1646 Topology multi replica test cases
  tests/e2e/config.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/util.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#1675 allow option to skip building and pushing windows images
  hack/release.sh
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1678 Add privileges for Administrator group users on CnsRegisterVolume/PVC…
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1672 Remove namespace label from CsiControlOpsHistVec
  pkg/common/prometheus/metrics.go
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#1676 Reduce number of histogram buckets for CSI metrics
  pkg/common/prometheus/metrics.go
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes
