Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2022-06, with the labels that each got.

#1761 add feature-gate for 256 volumes per node feature
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/constants.go
  pkg/csi/service/node.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#1767 [cherry-pick-release-2.3] protect migrated volume from vm deletion (#1762)
  Makefile
  go.mod
  go.sum
  hack/check-format.sh
  hack/check-staticcheck.sh
  pkg/apis/migration/migration.go
  pkg/apis/migration/v1alpha1/types.go
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1769 upgrade golang to 1.17 for release 2.3 branch
  go.mod
  go.sum
  images/ci/Dockerfile
  images/driver/Dockerfile
  images/syncer/Dockerfile
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1771 change image tags to v2.3.2-rc.1 for v2.3.2-rc.1 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1776 [Fix-dot-import]: Fixing dot import for the importing the e2e module into cns-manager repo
  tests/e2e/suite_test.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1775 [e2e-tests]: test fix for the panic issue during e2e test execution
  tests/e2e/vsphere_file_volume_basic.go
  tests/e2e/vsphere_file_volume_basic_without_datacenter.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1780 Modify VC version check for new vSphere 8.0 releases
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/common_controller_helper_test.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1770 enable tkgs-ha feature gate
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#1778 Revert "Remove FSS guard for online volume expansion feature (#1632)"
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/constants.go
  pkg/csi/service/node.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1785 Disable tkgs-ha fss to false
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1783 Publish the list volumes Controller Capabilities only when the FSS for list-volumes is enabled
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1765 [cherry-pick-release-2.4] protect migrated volume from vm deletion (#1762)
  Makefile
  go.mod
  go.sum
  hack/check-staticcheck.sh
  pkg/apis/migration/config/cns.vmware.com_cnsvspherevolumemigrations.yaml
  pkg/apis/migration/migration.go
  pkg/apis/migration/v1alpha1/types.go
  pkg/apis/storagepool/config/cns.vmware.com_storagepools.yaml
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1766 [cherry-pick-release-2.5] protect migrated volume from vm deletion (#1762)
  go.mod
  go.sum
  pkg/apis/migration/config/cns.vmware.com_cnsvspherevolumemigrations.yaml
  pkg/apis/migration/migration.go
  pkg/apis/migration/v1alpha1/types.go
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1768 [cherry-pick-release-2.2] protect migrated volume from vm deletion (#1762)
  Makefile
  go.mod
  go.sum
  hack/check-format.sh
  hack/check-lint.sh
  hack/check-staticcheck.sh
  hack/run-e2e-test.sh
  pkg/apis/migration/migration.go
  pkg/apis/migration/v1alpha1/types.go
  pkg/apis/storagepool/config/cns.vmware.com_storagepools.yaml
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/cns-lib/vsphere/vslm.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1779 Update sidecars with new released versions for Vanilla
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#1790 [release-2.4] upgrade go to 1.17 and tag manifests for v2.4.2-rc.1
  go.mod
  go.sum
  images/ci/Dockerfile
  images/driver/Dockerfile
  images/syncer/Dockerfile
  images/windows/driver/Dockerfile
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/L, approved, cncf-cla: yes

#1788 [release-2.2] upgrade go to 1.17 and create manifests for v2.2.4-rc.1
  go.mod
  go.sum
  images/ci/Dockerfile
  images/driver/Dockerfile
  images/syncer/Dockerfile
  manifests/v2.2.4/deploy/create-validation-webhook.sh
  manifests/v2.2.4/deploy/generate-signed-webhook-certs.sh
  manifests/v2.2.4/deploy/validatingwebhook.yaml
  manifests/v2.2.4/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.4/deploy/vsphere-csi-node-ds.yaml
  manifests/v2.2.4/rbac/vsphere-csi-controller-rbac.yaml
  manifests/v2.2.4/rbac/vsphere-csi-node-rbac.yaml
  pkg/apis/storagepool/config/cns.vmware.com_storagepools.yaml
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#1789 [release-2.5] upgrade go to 1.17 and tag manifests for v2.5.2-rc.1
  go.mod
  images/ci/Dockerfile
  images/driver/Dockerfile
  images/syncer/Dockerfile
  images/windows/driver/Dockerfile
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#1791 [release-2.4] revert storagepool yaml changes
  pkg/apis/storagepool/config/cns.vmware.com_storagepools.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#1792 enable tkgs-ha feature gate
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1794 [Cherry-pick to release-2.4] Fixed parsing of /proc/self/mountinfo with spaces (#1468)
  pkg/csi/service/osutils/linux_os_utils.go
  pkg/csi/service/osutils/linux_os_utils_test.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1795 [Cherry-pick to release-2.2] Fixed parsing of /proc/self/mountinfo with spaces (#1468)
  pkg/csi/service/node.go
  pkg/csi/service/node_test.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1793 [Cherry-pick to release-2.3] Fixed parsing of /proc/self/mountinfo with spaces (#1468)
  pkg/csi/service/node.go
  pkg/csi/service/node_test.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#1799 tag v2.2.4 rc.2 images
  manifests/v2.2.4/deploy/validatingwebhook.yaml
  manifests/v2.2.4/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.4/deploy/vsphere-csi-node-ds.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1797 tag v2.3.2-rc.2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1798 tag v2.4.2-rc.2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1750 Code fix for static sleep while checking csi pods running state
  tests/e2e/file_volume_statefulsets.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1800 Handle PV name NotFound in PVC spec errors in CnsNodeVMAttachment controller
  pkg/common/fault/constants.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: size/S, approved, cncf-cla: yes

#1803 Rollback csi-snapshotter sidecar to v5.0.1
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1804 Updating the driver and syncer images to v2.6.0-rc.1 images.
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1784 Adding test to create/restore snapshot on vvol and vmfs datastore
  tests/e2e/csi_snapshot_basic.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1801 Enhance ControllerUnpublishVolume to be no-op when pod is rescheduled on to a different worker node
  pkg/csi/service/wcp/controller.go
Labels: size/S, approved, cncf-cla: yes

#1805 unescape taret for IsTargetInMounts
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
  pkg/csi/service/node.go
  pkg/csi/service/node_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1807 tag v2.3.2-rc.3 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, cncf-cla: yes

#1808 unescape target for IsTargetInMounts
  manifests/v2.2.4/deploy/validatingwebhook.yaml
  manifests/v2.2.4/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.4/deploy/vsphere-csi-node-ds.yaml
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
  pkg/csi/service/node.go
  pkg/csi/service/node_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1810 tag release v2.3.2
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, cncf-cla: yes

#1709 Topology automation operation strom testcases - part5
  tests/e2e/e2e_common.go
  tests/e2e/topology_operation_strom_cases.go
  tests/e2e/topology_site_down_cases.go
  tests/e2e/util.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1817 tag v2.2.4 release images
  manifests/v2.2.4/deploy/validatingwebhook.yaml
  manifests/v2.2.4/deploy/vsphere-csi-controller-deployment.yaml
  manifests/v2.2.4/deploy/vsphere-csi-node-ds.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1819 tag v2.5.2 release images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1812 Update sidecar containers to latest releases
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes, release-2.6.0-candidate

#1815 Fix for syncer crash - Connect to Pbm client before invoking pbm methods
  pkg/common/cns-lib/vsphere/pbm.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#1821 update csi-node-driver-registrar config for PVCSI (#1713)
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1811 Add snapshot related permissions to vsphere-csi-controller-role
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1816 Remove the option to use gocsi
  cmd/vsphere-csi/main.go
  go.mod
  go.sum
  manifests/guestcluster/1.18/pvcsi.yaml
  manifests/guestcluster/1.19/pvcsi.yaml
  manifests/guestcluster/1.20/pvcsi.yaml
  manifests/guestcluster/1.21/pvcsi.yaml
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/provider/provider.go
  pkg/csi/service/driver.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1813 Enhancements for running tests when csi controller is on a different k8s cluster - 1
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/util.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#1829 add rbac rules for tkgs-ha feature for k8s supervisor 1.21
  manifests/supervisorcluster/1.21/cns-csi.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1830 Swap variables in the detach volume success logs
  pkg/common/cns-lib/volume/manager.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#1825 Update go to 1.18
  go.mod
  hack/check-golangci-lint.sh
  hack/check-staticcheck.sh
  hack/release.sh
  images/ci/Dockerfile
  images/driver/Dockerfile
  images/syncer/Dockerfile
  images/windows/driver/Dockerfile
Labels: size/S, approved, lgtm, cncf-cla: yes

#1665 Stretched tests PART 8
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes
