Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2022-10, with the labels that each got.

#2023 Tag v2.6.2-rc.4 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2022 Tag v2.5.4-rc.4 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#1992 Remove redundant topology related code and enable improved-volume-topology FSS by default
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/constants.go
  pkg/csi/service/driver.go
  pkg/csi/service/node.go
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/cnsoperator/manager/init.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2019 CSI vanilla controller Init changes for multi vCenter support
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/config/config.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/types.go
  pkg/csi/service/common/util.go
  pkg/csi/service/vanilla/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#1979 Preferential automation - Part1
  tests/e2e/config.go
  tests/e2e/e2e_common.go
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/util.go
  tests/e2e/vsphere.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#1940 TKGs HA PART3
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/util.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#1974 Prevent duplicate cluster IDs in vSphere CSI driver
  cmd/syncer/main.go
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/common/config/config.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/util.go
  pkg/csi/service/driver.go
  pkg/csi/types/envvars.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2027 initialize volumemanagers for multiple vCenter servers for syncer
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/types.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1954 TKG HA Multi replica tests
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/util.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2031 Preferential automation - Part2
  tests/e2e/preferential_topology.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2029 adding node-role.kubernetes.io/master tolerations to 1.24 yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2033 fixed windows node daemonset pod spec
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2034 tag v2.5.4 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2035 tag v2.6.2 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2032 cnsvolumeinfo service for multi vCenter CSI topology feature
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/util.go
  pkg/csi/service/vanilla/controller.go
  pkg/internalapis/cnsvolumeinfo/cnsvolumeinfoservice.go
  pkg/internalapis/cnsvolumeinfo/config/cns.vmware.com_cnsvolumeinfoes.yaml
  pkg/internalapis/cnsvolumeinfo/config/config.go
  pkg/internalapis/cnsvolumeinfo/v1alpha1/cnsvolumeinfo_types.go
  pkg/internalapis/cnsvolumeinfo/v1alpha1/register.go
  pkg/internalapis/cnsvolumeinfo/v1alpha1/zz_generated.deepcopy.go
  pkg/kubernetes/kubernetes.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2000 Add priority class for vsphere csi driver deployment and daemon set
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, cncf-cla: yes

#1999 Upgrade CSI Provisioner Attacher Resizer & Snapshotter sidecars
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2014 Update for tolerations compatible with Kubernetes 1.24
  manifests/guestcluster/1.24/pvcsi.yaml
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1904 [Snapshot-webhook]: Fix delete snapshot usecase to consider the webhook validations
  tests/e2e/csi_snapshot_basic.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2041 ControllerPublishVolume and ControllerUnpublishVolume changes for multi-vc CSI topology
  pkg/common/config/config.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
  pkg/csi/service/wcp/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2004 Be more thorough when deciding whether a volume is mounted or not.
  pkg/csi/service/osutils/windows_os_utils.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2042 Enable improved idempotency feature by default for Vanilla deployments
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1962 TKG HA multi replica PART 2
  tests/e2e/e2e_common.go
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_site_down.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2044 DeleteVolume changes for multi-VC CSI topology
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
  pkg/csi/service/wcp/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2043 Multi-VC: Node topology discovery
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2049 TKG HA site down testcases automation
  tests/e2e/e2e_common.go
  tests/e2e/tkgs_ha_site_down.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2057 Add cns-csi.yaml for supervisor 1.25
  manifests/supervisorcluster/1.25/cns-csi.yaml
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#1916 Changes for VCP to CSI migration tests since migration is always on in k8s 1.25
  go.mod
  go.sum
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_create_delete.go
  tests/e2e/vcp_to_csi_full_sync.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/vcp_utils.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2058 tag 2.7 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2052 Update documentation for raw block volume to reflect that is is supported only on linux
  docs/book/features/raw_block_volume.md
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2053 ExpandVolume changes to support multi-VC CSI topology
  pkg/csi/service/common/util.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2048 Preferential automation part4
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/preferential_topology_utils.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2056 Updgrade k8s mount dependency
  go.mod
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2047 nerdctl cmd execution code fix
  tests/e2e/topology_operation_strom_cases.go
Labels: size/S, needs-ok-to-test, approved, lgtm, cncf-cla: yes

#2038 Multi VC support - PVC delete/update in metadatasyncer
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2054 Create topology label to VC map in syncer
  cmd/syncer/main.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/syncer_test.go
  pkg/syncer/types.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2061 initialize volume managers for multi vCenter servers
  pkg/common/cns-lib/volume/manager.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/diskDecommissionController.go
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/syncer_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2040 [Block volumes] Skip shared datastore computations if CNS task for CreateVolume is persisted in the idempotency CR
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/vanilla/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2060 Preferential testcase code fix
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/preferential_topology_utils.go
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#2051 ListVolumes changes for multi-VC CSI topology
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes
