Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-03, with the labels that each got.

#2250 Switch from k8s.gcr.io to registry.k8s.io
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
  tests/e2e/vmc_csi_deployments.go
Labels: size/S, approved, cncf-cla: yes

#2194 Support PVC resize for migrated PVC
  pkg/csi/service/vanilla/controller.go
  pkg/syncer/admissionhandler/validatestorageclass.go
  pkg/syncer/admissionhandler/validatestorageclass_test.go
Labels: approved, size/M, cncf-cla: yes

#2258 Enable multi-vcenter-support fss
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, cncf-cla: yes

#2252 Acquire lock in public Connect method
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.0.0-candidate

#2259 Cherrypick Pull requests 2252 & 2258
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: size/XS, approved, cncf-cla: yes

#2261 Update CSI images to 3.0-rc.2
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#2245 TC to check volume snapshot creation and restoration workflow with xfs filesystem
  tests/e2e/csi_snapshot_basic.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2268 Add volumeMode in restore PVC example for raw block volume
  example/vanilla-k8s-RWO-Block-Volumes/example-raw-block-restore.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2147 fix: return appropriate error message to gc pvc from supervisor
  pkg/csi/service/wcpguest/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2249 ListVolumes optimizations
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2263 TCs to verify online and offline volume expansion workflow with xfs filesystem
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/vsphere_volume_expansion.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2253 Add VCP-to-CSI migration and Volume expansion testcases for Raw Block Volume
  tests/e2e/raw_block_volume.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2281 fss: disable listview-tasks feature for vanilla
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.0.0-candidate

#2282 fss: disable listview-tasks feature for vanilla (#2281)
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2283 tag-v3.0.0-rc.3-images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#2025 spbm policy driven vol alloc tests - part 4
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/storage_policy_utils.go
  tests/e2e/util.go
  tests/e2e/vsphere.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#2285 [CSI-CICD] Export missing NONSHARED_VSPHERE_DATASTORE_URL
  pipeline/deploy.sh
  pipeline/e2e-tests.sh
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#2267 Add snapshot restore testcase for raw block volume and fix bug for vcp-csi migration tc of raw block volume
  pkg/csi/service/common/util_test.go
  tests/e2e/raw_block_volume.go
  tests/e2e/vcp_to_csi_syncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2288 fixes to couple of volume allocation related tests
  tests/e2e/policy_driven_vol_allocation.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2276 Optimize vanilla list-volumes
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2289 Tag CSI images for 3.0 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2290 Fix minor logging
  pkg/syncer/fullsync.go
Labels: size/XS, approved, cncf-cla: yes

#2196 Code fixes for Topology testcases
  tests/e2e/config_secret.go
  tests/e2e/invalid_topology_values.go
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/statefulset_with_topology.go
  tests/e2e/topology_aware_node_poweroff.go
  tests/e2e/topology_operation_strom_cases.go
  tests/e2e/topology_site_down_cases.go
  tests/e2e/volume_provisioning_with_topology.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2294 Adding verification for CNS Volume Delete Check
  tests/e2e/vc_reboot_volume_lifecycle.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2205 Prevent duplicate cluster id tc1
  tests/e2e/config_secret.go
  tests/e2e/config_secret_utils.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/csi_static_provisioning_file_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/nodes_scaleup_scaledown.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/prevent_duplicate_cluster_ids.go
  tests/e2e/raw_block_volume.go
  tests/e2e/staging_env_basic.go
  tests/e2e/statefulset_xfs.go
  tests/e2e/statefulsets.go
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/topology_operation_strom_cases.go
  tests/e2e/topology_site_down_cases.go
  tests/e2e/topology_snapshot.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_create_delete.go
  tests/e2e/vcp_to_csi_full_sync.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/volume_health_test.go
  tests/e2e/volume_provisioning_with_level5_topology.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2297 Implemented the deploy-images-staging and patch-prod-images jobs in the pipeline.
  .gitlab-ci.yml
  pipeline/deploy-staging.sh
  pipeline/patch-prod.sh
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2299 Return successful controllerUnpublishForBlockVolume in pvcsi when a block volume is not found in the virtual machine status field
  pkg/csi/service/wcpguest/controller.go
Labels: size/L, approved, cncf-cla: yes

#2295 Add PVC validation handling for snapshots during ExpandVolume and DeleteVolume operation in WCP
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/validatepvc.go
  pkg/syncer/admissionhandler/validatepvc_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2298 Update external-snapshotter client version from v4 to v6
  go.mod
  go.sum
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/admissionhandler/validatepvc.go
  pkg/syncer/admissionhandler/validatepvc_test.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_file_volume.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/raw_block_volume.go
  tests/e2e/topology_snapshot.go
  tests/e2e/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2304 Update sidecar versions and cve fixes
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2312 Tag 2.7.1-rc.1 Update driver and syncer images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2305 Allow NTFS fsType to be uppercase
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2296 Changes to disable snapshot operations directly initiated from the Supervisor cluster
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/validatesnapshotoperationsupervisorrequest.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2310 Return successful controllerUnpublishForBlockVolume in pvcsi when a block volume is not found in the virtual machine status field
  hack/check-staticcheck.sh
  pkg/csi/service/wcpguest/controller.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/svmotion_detached_volume.go
  tests/e2e/tkgs_ha.go
  tests/e2e/vsan_stretched_cluster.go
Labels: size/L, approved, cncf-cla: yes

#2315 fix incorrect yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes
