Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-11, with the labels that each got.

#2632 CVE-2023-45142: bump k8s and opentelemetry
  go.mod
  go.sum
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2633 Add cns-csi.yaml for Supervisor 1.28
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.28/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2634 Resolve linter errors to support K8s 1.26 version
  pkg/apis/migration/migration.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/internalapis/featurestates/featurestates.go
  pkg/kubernetes/informers.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/resize_reconciler.go
  pkg/syncer/storagepool/nodeannotationlistener.go
  pkg/syncer/volume_health_reconciler.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/csi_static_provisioning_file_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_rwx_basic.go
  tests/e2e/gc_rwx_multi_gc.go
  tests/e2e/gc_rwx_multi_ns_gc.go
  tests/e2e/gc_rwx_operation_storm.go
  tests/e2e/gc_rwx_readonly.go
  tests/e2e/gc_rwx_reclaim_policy.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_static_provision.go
  tests/e2e/gc_rwx_syncer.go
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/operationstorm.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/staging_env_basic.go
  tests/e2e/statefulset_xfs.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere_file_volume_basic_mount.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
  tests/e2e/vsphere_volume_fstype.go
  tests/e2e/vsphere_volume_mount.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2599 Static volume provisioning for file volumes in multi VC
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2631 Validate vCenter username and crash CSI driver if username is not a fully qualified domain name
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/syncer_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2629 Validate vCenter username and crash CSI driver if username is not a fully qualified domain name
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/syncer_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2627 Validate vCenter username and crash CSI driver if username is not a fully qualified domain name
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/syncer_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2611 Create CSINodes in WCP cluster when appropriate annotation is present
  manifests/supervisorcluster/1.27/cns-csi.yaml
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/wcp_node.go
  pkg/csi/service/common/constants.go
  pkg/kubernetes/informers.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2637 tag v3.1.2-rc.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2608 Full sync changes for RWX volumes on topology
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2640 Add flag "--extra-create-metadata" to PVCSI csi-snapshotter sidecar to pass required parameters
  manifests/guestcluster/1.24/pvcsi.yaml
  manifests/guestcluster/1.25/pvcsi.yaml
  manifests/guestcluster/1.26/pvcsi.yaml
  manifests/guestcluster/1.27/pvcsi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2579 Add support for RWX volumes on topology aware deployments
  pkg/common/cns-lib/vsphere/hostsystem.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2643 Add PVCSI yaml for K8S version 1.28
  manifests/guestcluster/1.28/pvcsi.yaml
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2635 Bump up Go to 1.21
  go.mod
  hack/release.sh
  images/ci/Dockerfile
  images/driver/Dockerfile
  images/syncer/Dockerfile
  images/windows/driver/Dockerfile
  tests/e2e/docs/supervisor_cluster_setup.md
Labels: size/S, approved, lgtm, cncf-cla: yes

#2636 Bump up CSI spec to 1.9.0 and it's dependencies
  go.mod
  go.sum
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2641 Update govmomi to v0.33
  go.mod
  go.sum
  pkg/common/cns-lib/volume/listview.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2628 Assigning ginkgo_Labels to wcp and ListVolume tests
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/e2e_common.go
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/labelupdates.go
  tests/e2e/statefulsets.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2646 Tag CSI Images as 2.6.4-rc.1 to prepare for v2.6.4 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2639 Bumping up kubernetes version to 1.25.13 for release-3.0
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2642 Bumping up kubernetes version to 1.26.8 for release-3.1
  go.mod
  go.sum
  pkg/apis/migration/migration.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/mounter/mounter_windows.go
  pkg/csi/service/osutils/linux_os_utils.go
  pkg/internalapis/featurestates/featurestates.go
  pkg/kubernetes/informers.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/resize_reconciler.go
  pkg/syncer/volume_health_reconciler.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/csi_static_provisioning_file_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_rwx_basic.go
  tests/e2e/gc_rwx_multi_gc.go
  tests/e2e/gc_rwx_multi_ns_gc.go
  tests/e2e/gc_rwx_operation_storm.go
  tests/e2e/gc_rwx_readonly.go
  tests/e2e/gc_rwx_reclaim_policy.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_static_provision.go
  tests/e2e/gc_rwx_syncer.go
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/operationstorm.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/staging_env_basic.go
  tests/e2e/statefulset_xfs.go
  tests/e2e/statefulsets.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere_file_volume_basic_mount.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
  tests/e2e/vsphere_volume_fstype.go
  tests/e2e/vsphere_volume_mount.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#2648 Tag CSI Images as 3.0.4-rc.1 to prepare for v3.0.4 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2650 Tag CSI Images as 3.1.2-rc.2 to prepare for v3.1.2 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2654 Formatting test names
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/labelupdates.go
  tests/e2e/statefulsets.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2657 Storage Quota APIs
  pkg/apis/cnsoperator/config/cns.vmware.com_storagepolicyquotas.yaml
  pkg/apis/cnsoperator/config/cns.vmware.com_storagepolicyusages.yaml
  pkg/apis/cnsoperator/config/config.go
  pkg/apis/cnsoperator/register.go
  pkg/apis/cnsoperator/storagepolicy/v1alpha1/doc.go
  pkg/apis/cnsoperator/storagepolicy/v1alpha1/storagepolicyquota_types.go
  pkg/apis/cnsoperator/storagepolicy/v1alpha1/storagepolicyusage_types.go
  pkg/apis/cnsoperator/storagepolicy/v1alpha1/zz_generated.deepcopy.go
  pkg/internalapis/cnsvolumeoperationrequest/config/cns.vmware.com_cnsvolumeoperationrequests.yaml
  pkg/internalapis/cnsvolumeoperationrequest/v1alpha1/cnsvolumeoperationrequest_types.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#2647 handle credential change during add/remove from listview
  pkg/common/cns-lib/volume/listview.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.1.2-candidate

#2649 WCP testcase to test successful drain of node during Maintainence mode of a host
  tests/e2e/config_secret.go
  tests/e2e/config_secret_utils.go
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/statefulsets.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2652 Change error message when datastore is not found in candidate datastore list
  pkg/csi/service/common/vsphereutil.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2660 Fix API validation issue
  pkg/internalapis/cnsvolumeoperationrequest/config/cns.vmware.com_cnsvolumeoperationrequests.yaml
  pkg/internalapis/cnsvolumeoperationrequest/v1alpha1/cnsvolumeoperationrequest_types.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2656 Fix e2e test for file-vanilla
  tests/e2e/file_volume_statefulsets.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2663 tag v3.1.2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2664 tag v2.6.4 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2665 update test with increase timeout and avoid create deployment (#2656)
  tests/e2e/file_volume_statefulsets.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2669 Cherry-pick listview bug fixes for expired tasks and credential change
  go.mod
  go.sum
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/manager.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes
