Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-02, with the labels that each got.

#2184 Have a separate volume lock for each VC
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/syncer_test.go
  pkg/syncer/types.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2188 Fix error messages to start with non-capitalized letters
  cmd/syncer/main.go
  cmd/vsphere-csi/main.go
Labels: size/XS, approved, cncf-cla: yes

#2189 Create a separate client lock for each VC.
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2190 Add fsType parameter in static provisioning PV example
  example/vanilla-k8s-RWO-filesystem-volumes/example-static-rwo-volume.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2187 support shared datastores across datacenters
  pkg/common/cns-lib/volume/util.go
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/csi/service/common/vsphereutil.go
Labels: size/L, approved, cncf-cla: yes

#2198 Update static check tool to latest version
  hack/check-staticcheck.sh
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/svmotion_detached_volume.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/vsan_stretched_cluster.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2185 Fix the PR: 3082728,add NodeUpdate function to initNodeIDToNameMap
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2182 Changes to handle NodeExpandVolume() API correctly for raw-block volumes
  pkg/csi/service/node.go
  pkg/csi/service/osutils/linux_os_utils.go
  pkg/csi/service/osutils/windows_os_utils.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2199 fix preferredDatastore calculation on multi vCenter setup
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/common/placementengine/types.go
  pkg/csi/service/common/topology.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2202 set topologyRequirement for volTaskAlreadyRegistered case
  pkg/csi/service/vanilla/controller.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2152 List volume automation
  tests/e2e/statefulsets.go
  tests/e2e/util.go
  tests/e2e/vsphere.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2192 Remove service mode check for consistent fss checking across all CSI containers
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: approved, size/M, cncf-cla: yes

#2201 Made changes in fstype validation e2e TC based on XFS filesystem support
  tests/e2e/e2e_common.go
  tests/e2e/vsphere_volume_fstype.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2209 Added list volume config parameters
  tests/e2e/config.go
  tests/e2e/util.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2207 Fetch tag information for preferred datastores, using REST call, without connecting to vCenter directly.
  pkg/csi/service/common/topology.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2210 update readme file
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm, size/M, cncf-cla: yes

#2195 Skip creating new vc client upon config secret change
  cmd/syncer/main.go
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/config/config.go
  pkg/common/config/types.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/topology.go
  pkg/csi/service/common/util.go
  pkg/csi/service/driver.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/types/envvars.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#2215 List vol presently not enabled by default on SVC
  tests/e2e/statefulsets.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2162 Disable Disk Decommission FSS references as it is enabled by default
  manifests/supervisorcluster/1.15/cns-csi.yaml
  manifests/supervisorcluster/1.16/cns-csi.yaml
  manifests/supervisorcluster/1.17/cns-csi.yaml
  manifests/supervisorcluster/1.18/cns-csi.yaml
  manifests/supervisorcluster/1.19/cns-csi.yaml
  manifests/supervisorcluster/1.20/cns-csi.yaml
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  pipeline/dev/patch.yaml
  pkg/csi/service/common/constants.go
  pkg/syncer/storagepool/service.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#1892 [Fix-gc-rwx-test]: Fix Parallel claim of available resource test
  tests/e2e/gc_rwx_basic.go
  tests/e2e/gc_rwx_multi_gc.go
  tests/e2e/gc_rwx_multi_ns_gc.go
  tests/e2e/gc_rwx_operation_storm.go
  tests/e2e/gc_rwx_parallel_claim.go
  tests/e2e/gc_rwx_readonly.go
  tests/e2e/gc_rwx_reclaim_policy.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_statefulsets.go
  tests/e2e/gc_rwx_static_provision.go
  tests/e2e/gc_rwx_syncer.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2208 New TC for statefulset creation and scale up, scale down scenario testing with XFS filesystem
  tests/e2e/statefulset_xfs.go
  tests/e2e/vsphere_volume_fstype.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2219 Upgraded dependecies to fix CVE
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2216 Add missing RBAC permissions to vSphere CSI webhook cluster role
  manifests/vanilla/validatingwebhook.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2223 updated dependencies to fix cves
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2225 updated dependencies to fix cves
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2217 TC to verify static volume provisioning workflow with XFS filesystem
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/labelupdates.go
  tests/e2e/util.go
  tests/e2e/vmc_delete_tkg.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere_volume_expansion.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2221 restart CSI controller and syncer container when new vCenter is observed in the config secret
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2224 Pass vCenter server associated with volume to be stored in CnsVolumeOperationRequest CR
  pkg/internalapis/cnsvolumeoperationrequest/util.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2158 Update fsnotify ginkgo ginkgo and other libraries
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2222 enable listview-tasks, csi-internal-generated-cluster-id and csi-windows-support
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2227 Update ginkgo in e2e test begin script
  hack/run-e2e-test.sh
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2230 bump up CSI sidecar containers for CSI 3.0 release
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2232 update driver images for tag v3.0.0-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2233 correct RC image for v3.0.0-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#2212 New TC for raw block volume support
  tests/e2e/raw_block_volume.go
  tests/e2e/util.go
Labels: needs-ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#2229 tag 2.7.1 Update driver and syncer images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2228 tag 2.6.3 update driver and syncer images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2237 Update CSI images to 2.6.3-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#2239 fix push manifest issue and removing EOL windows versions
  hack/release.sh
Labels: size/XS, approved, cncf-cla: yes

#2240 fix push manifest issue and removing EOL windows versions
  hack/release.sh
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#2234 Avoid unnecessary map creation for webhook server, removing unneccessary RBAC.
  cmd/syncer/main.go
  cmd/vsphere-csi/main.go
  manifests/vanilla/validatingwebhook.yaml
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/utils.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes, release-3.0.0-candidate

#2204 Create clientmutex as part of VC object
  pkg/common/cns-lib/volume/listview_test.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.0.0-candidate

#2218 Add static provisioning testcase for raw block volume support
  tests/e2e/raw_block_volume.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2243 Update e2e script to run block vanilla parallelized tests separately
  hack/run-e2e-test.sh
  tests/e2e/data_persistence.go
Labels: size/XS, approved, cncf-cla: yes

#2244 Cherry-Pick change for Avoid unnecessary map creation for webhook server, reducing the RBAC requirements
  cmd/syncer/main.go
  cmd/vsphere-csi/main.go
  manifests/vanilla/validatingwebhook.yaml
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/utils.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2235 Storing failed delete volume & delete snapsot operation details in CnsVolumeOperationRequest CR
  pkg/common/cns-lib/volume/manager.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.0.0-candidate

#2247 Create clientmutex as part of VC object
  pkg/common/cns-lib/volume/listview_test.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/cns-lib/vsphere/virtualcentermanager.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, cncf-cla: yes

#2246 Storing failed delete volume and delete snapshot operation details in CnsVolumeOperationRequest CR
  pkg/common/cns-lib/volume/manager.go
Labels: size/S, approved, cncf-cla: yes
