Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-06, with the labels that each got.

#2399 Add test to validate alpha feature pv-to-backingdiskobjectid-mapping
  pkg/common/unittestcommon/utils.go
  tests/e2e/vsphere_volume_with_alpha_feature.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2362 Allow topology to be configured day 2 operation
  go.mod
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology_test.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2411 move clientMutex lock to public VC Connect method from private VC connect method - release-2.7
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2414 Cross-port PVCSI Detach Volume no-op changes to release-3.0
  pkg/csi/service/wcpguest/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2415 tag v2.7.2-rc.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2400 Fix use of GetNodeByName when using node's VMUUID (#2387)
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/manager_test.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2412 Allow topology to be configured day 2 operation (#2362)
  go.mod
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology_test.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2396 Remove use-csinode-id FSS
  cmd/syncer/main.go
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/manager_test.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/node.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller_test.go
  tests/e2e/e2e_common.go
  tests/e2e/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2418 fix: list-volume fails in multi-vcenter environment if all nodes are …
  pkg/csi/service/vanilla/controller_helper.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2421 Cherry Pick PV to backing disk ID
  pkg/syncer/metadatasyncer.go
  pkg/syncer/pv_to_backingdiskobjectid_mapping.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2402 Removing busyBoxImage reference from test code
  tests/e2e/docs/guest_cluster_setup.md
  tests/e2e/docs/multimaster_cluster_setup.md
  tests/e2e/docs/supervisor_cluster_setup.md
  tests/e2e/docs/topology_aware_vanilla_setup.md
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/docs/vmc_tkg_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/statefulset_with_topology.go
  tests/e2e/suite_test.go
  tests/e2e/topology_aware_node_poweroff.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2424 cherrypick PR 2402 from master to release-3.0
  tests/e2e/docs/guest_cluster_setup.md
  tests/e2e/docs/multimaster_cluster_setup.md
  tests/e2e/docs/supervisor_cluster_setup.md
  tests/e2e/docs/topology_aware_vanilla_setup.md
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/docs/vmc_tkg_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/statefulset_with_topology.go
  tests/e2e/suite_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2425 Cherry-Pick Adding Script to generate data for upgrade based scenario (#2392)
  tests/e2e/preupgrade_datasetup.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2426 Removed local declarations of busy box image (#2402)
  tests/e2e/docs/guest_cluster_setup.md
  tests/e2e/docs/multimaster_cluster_setup.md
  tests/e2e/docs/supervisor_cluster_setup.md
  tests/e2e/docs/topology_aware_vanilla_setup.md
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/docs/vmc_tkg_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/suite_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2422 Pod image fix for CICD pipeline
  pipeline/e2e-tests-staging.sh
  pipeline/e2e-tests.sh
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2417 Update Photon OS to 5.0 image
  images/driver-base/Dockerfile
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2413 Update govmomi version to v0.30.4
  go.mod
  go.sum
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2427 Removed local declarations of busy box image (#2402)
  tests/e2e/docs/guest_cluster_setup.md
  tests/e2e/docs/multimaster_cluster_setup.md
  tests/e2e/docs/supervisor_cluster_setup.md
  tests/e2e/docs/topology_aware_vanilla_setup.md
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/docs/vmc_tkg_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/suite_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2429 cherry-pick-to-release-3.0 - Allow NTFS fsType to be uppercase (#2305)
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
Labels: approved, size/M, cncf-cla: yes

#2430 tag v3.0.2-rc.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2434 fss: enable listview-tasks on supervisor from 1.23 to 1.26
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  pkg/common/unittestcommon/utils.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2404 Determine cluster distribution server version & type using kubernetes API server version
  cmd/syncer/main.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2435 Introduce csi-snapshotter sidecar in cns-csi yamls
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  pkg/csi/service/wcp/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2388 Upgrade sidecar containers to latest releases
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#2440 tag v2.7.2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2438 Fixing -> tar: removing leading '/' from member names, issue with kubectl cp
  tests/e2e/policy_driven_vol_allocation.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2441 Set Photon version to 4.0
  images/driver-base/Dockerfile
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2442 Update csi-snapshotter version in cns-csi yamls
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2437 For CICD jobs - Cleanup namespace created by test framework mainly in static provisioning and volume expansion tests
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/vsphere_volume_expansion.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2443 fix: GenerateDatastoreMapForBlockVolumes fails if there are no entities
  pkg/csi/service/common/authmanager.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.0.2-candidate

#2447 fix: GenerateDatastoreMapForBlockVolumes fails if there are no ManagedObjectReferences (#2443)
  pkg/csi/service/common/authmanager.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2448 Tag 3.0 RC2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2444 Run vSphere CSI controller pod with non-root user
  manifests/guestcluster/1.24/pvcsi.yaml
  manifests/guestcluster/1.25/pvcsi.yaml
  manifests/guestcluster/1.26/pvcsi.yaml
  manifests/guestcluster/1.27/pvcsi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2450 Use correct function in testcase to fetch VM UUID in case of guest cluster setup
  tests/e2e/raw_block_volume.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2455 [cherrypick 2454 to release-3.0] Fetch vcHost and cnsVolMgr in case migrated volumes to process further
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2456 tag v3.0.2-rc.2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2452 update doc links to 3.0 version
  README.md
Labels: size/S, approved, lgtm, cncf-cla: yes
