Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-01, with the labels that each got.

#2128 Use faulttype to determine the attach/detach operation succeeded or not.
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2141 better error message when snapshot restore size does not match
  pkg/csi/service/vanilla/controller.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2145 fix listvolume for migrated volumes
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, ok-to-test, size/M, cncf-cla: yes

#2146 Add VC name in full sync logs
  pkg/syncer/fullsync.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2150 Disable List Volume FSS on WCP till a fix for PR: 3082728 is implemented
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2149 Revert 29be045 - Ensure Supervisor PVC failure provisioning error is immediately reflected on GC (#1749)
  pkg/csi/service/wcpguest/controller_helper.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2153 Add new fault type category "invalidconfig".
  pkg/common/fault/constants.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2129 Handle ManagedObjectNotFound error in case of detach volume operation
  pkg/common/cns-lib/volume/manager.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2161 support file volume creation on non-topology enabled single vCenter deployment with multi-vcenter-csi-topology gate enabled
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2159 Customise Leader Election for Syncer container
  cmd/syncer/main.go
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/guestcluster/1.24/pvcsi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2151 Bumping up sidecars
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2167 Log update
  pkg/csi/service/vanilla/controller.go
Labels: size/XS, approved, cncf-cla: yes

#2164 Leader election customisation for vanilla deployments
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2168 fix push manifest issue and removing EOL windows versions
  hack/release.sh
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2170 Add datastore configuration for migrated volumes.
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/config/types.go
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2163 Make separate CNS creation and deletion maps for VCs during full Sync
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/syncer_test.go
  pkg/syncer/types.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2173 Changes for fstype validation
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
  pkg/csi/service/node.go
  pkg/csi/service/osutils/linux_os_utils.go
  pkg/csi/service/osutils/os_utils.go
  pkg/csi/service/osutils/windows_os_utils.go
  tests/e2e/vsphere_file_volume_basic.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2171 Nimbus generated passwords read for VC ESXi and K8s VM from env. export variables
  tests/e2e/config_change_test.go
  tests/e2e/config_secret.go
  tests/e2e/config_secret_utils.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_disruptive.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/topology_operation_strom_cases.go
  tests/e2e/topology_site_down_cases.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: needs-ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#2174 Add more debug log in function "GetAllAccessibleDatastores".
  pkg/common/cns-lib/vsphere/virtualmachine.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2175 Implemented deploy images stage in the pipeline to deploy the built images to a testbed to run E2E tests
  .gitlab-ci.yml
  manifests/supervisorcluster/1.22/kustomization.yaml
  pipeline/deploy.sh
  pipeline/dev/kustomization.yaml
  pipeline/dev/patch.yaml
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2156 improve windows log debuggability
  pkg/csi/service/mounter/mounter_windows.go
  pkg/csi/service/osutils/windows_os_utils.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2176 Update csi snapshot deployment script to use qualified version for snapshot-controller
  manifests/vanilla/deploy-csi-snapshot-components.sh
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2177 Added e2e-tests-dev, deploy-images-staging, e2e-tests-staging, system-tests-staging, and perf-tests-staging jobs.
  .gitlab-ci.yml
  pipeline/deploy-staging.sh
  pipeline/e2e-tests-staging.sh
  pipeline/e2e-tests.sh
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2178 fix panic in storagepool.ResetVC(ctx, vcenter) func
  pkg/syncer/storagepool/service.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2179 Fix CVE-2022-41717
  go.mod
  go.sum
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2180 supply spbm policy id while creating volume on multi vc setup
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2183 Nimbus password changes for VC,VC UI, ESX and K8s VM
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: size/S, needs-ok-to-test, approved, lgtm, cncf-cla: yes
