Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#2676 Update sidecar versions to latest releases
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2679 Add StoragePolicyID and StorageClassName to CnsVolumeOperationRequestStatus
  pkg/internalapis/cnsvolumeoperationrequest/config/cns.vmware.com_cnsvolumeoperationrequests.yaml
  pkg/internalapis/cnsvolumeoperationrequest/v1alpha1/cnsvolumeoperationrequest_types.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2674 [PodVMOnStretchedSupervisor] Store StoragePolicyInfo in CnsVolumeInfo CR
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  pkg/csi/service/wcp/controller.go
  pkg/internalapis/cnsvolumeinfo/cnsvolumeinfoservice.go
  pkg/internalapis/cnsvolumeinfo/config/cns.vmware.com_cnsvolumeinfoes.yaml
  pkg/internalapis/cnsvolumeinfo/v1alpha1/cnsvolumeinfo_types.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2671 Update CRDs to sync with gitlab repo.
  pkg/apis/cnsoperator/storagepolicy/v1alpha1/doc.go
  pkg/apis/cnsoperator/storagepolicy/v1alpha1/storagepolicyquota_types.go
  pkg/apis/cnsoperator/storagepolicy/v1alpha1/storagepolicyusage_types.go
  pkg/apis/cnsoperator/storagepolicy/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2672 remove TargetvSANFileShareDatastoreURLs from tests
  tests/e2e/config.go
  tests/e2e/config_secret.go
  tests/e2e/config_secret_utils.go
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/multi_vc_utils.go
  tests/e2e/prevent_duplicate_cluster_ids.go
  tests/e2e/util.go
  tests/e2e/vsphere_file_volume_basic.go
  tests/e2e/vsphere_file_volume_storagepolicy.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#2688 Add more logs when creating CnsRegisterVolume CRD.
  pkg/syncer/cnsoperator/manager/init.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2684 Add PVC Namespace in CnsVolumeInfo & CnsVolumeOperationRequest API definitions
  pkg/internalapis/cnsvolumeinfo/config/cns.vmware.com_cnsvolumeinfoes.yaml
  pkg/internalapis/cnsvolumeinfo/v1alpha1/cnsvolumeinfo_types.go
  pkg/internalapis/cnsvolumeoperationrequest/config/cns.vmware.com_cnsvolumeoperationrequests.yaml
  pkg/internalapis/cnsvolumeoperationrequest/v1alpha1/cnsvolumeoperationrequest_types.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2689 Fix StoragePolicUsage CRD fields in yaml definition
  pkg/apis/cnsoperator/config/cns.vmware.com_storagepolicyusages.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2683 [PodVMOnStretchedSupervisor] Use --extra-create-metadata argument in provisioner to fetch PVC Name & Namespace info
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcp/controller_helper.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2675 remove 2.3 and 2.4 from README.md
  README.md
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2691 [PodVMOnStretchedSupervisor] Add RBAC rules for storagepolicyusages CR in Supervisor yamls
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2690 [PodVMOnStretchedSupervisor] Store pvc namespace & storage class name in CnsVolumeInfo CR
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/internalapis/cnsvolumeinfo/cnsvolumeinfoservice.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2667 [PodVMOnStretchedSupervisor] CnsVolumeOperationRequest CR update handler
  pkg/apis/cnsoperator/config/cns.vmware.com_storagepolicyusages.yaml
  pkg/apis/cnsoperator/storagepolicy/v1alpha1/storagepolicyusage_types.go
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/resize_reconciler.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2682 Create CNSVolumeInfo CR with VolumeID and Storage Policy ID association in Static Volume Provisioning workflow.
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2699 Fix event logging upon test failure which was resulting in NPE
  go.mod
  go.sum
  hack/run-e2e-test.sh
  tests/e2e/suite_test.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2692 Bumping up kubernetes version to 1.25.16 for release-3.0
  go.mod
  go.sum
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2693 [PodVMOnStretchedSupervisor] Quota changes for CreateVolume
  pkg/apis/migration/migration.go
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
  pkg/internalapis/cnsvolumeoperationrequest/util.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2700 Add nil pointer checks for CnsVolumeOperationRequest objects are present for existing volumes
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2702 Use StoragePolicyId json string during CreateVolume
  pkg/common/cns-lib/volume/manager.go
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
  pkg/internalapis/cnsvolumeoperationrequest/util.go
Labels: size/S, approved, do-not-merge/hold, lgtm, cncf-cla: yes

#2703 Set podVMOnStretchSupervisor FSS early in Driver Init
  pkg/csi/service/wcp/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2661 Changes to fix issue - PVC resize in pvcsi reports success before actual resize in supervisor completes
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2706 Add CnsVolumeOperationCR Create & Delete handler
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2705 Quota changes for ExpandVolume.
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/internalapis/cnsvolumeinfo/cnsvolumeinfoservice.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2708 Fix a bug in patching storage policy usage CR method invocation
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2698 Add informer in syncer to watch for StoragePolicyQuota instance and create associated StoragePolicyUsage instances, if not created already.
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  pkg/apis/cnsoperator/register.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2709 Populate status fields for storagepolicyusage during CR Add handler
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2711 Quota changes for delete. Minor changes for Create, Expand calls.
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  pkg/apis/cnsoperator/storagepolicy/v1alpha1/storagepolicyusage_types.go
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/wcp/controller.go
  pkg/internalapis/cnsvolumeinfo/cnsvolumeinfoservice.go
  pkg/internalapis/cnsvolumeinfo/config/cns.vmware.com_cnsvolumeinfoes.yaml
  pkg/internalapis/cnsvolumeinfo/v1alpha1/cnsvolumeinfo_types.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2714 CVE-2023-48795: bump golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
Labels: kind/bug, size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2685 Add compute resource entity to consider a standalone host for volume provisioning
  pkg/csi/service/common/topology.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2712 Check for static volume accessibility in all AZs
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/types/types.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/util.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2715 Change reserved field to the difference between new volume size current volume capacity
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/wcp/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2717 collect SVC ns events when test fails in tests/e2e/statefulsets.go
  tests/e2e/statefulsets.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2697 Update StoragePolicyUsage CR for statically provisioned volumes
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2686 Bump OpenTelemetry libs
  go.mod
  go.sum
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2716 Update logging and comments for SPUsage CR informer, and add watch cnsvolumeoperation rbac rule
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2722 Update StoragePolicyUsage used capacity from Syncer's PV Delete informer event
  pkg/csi/service/wcp/controller.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2718 Fetch vcenter object based on volumeOperationRequest details if available
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2721 Fix volumeinfo service initialization for WCP flavor
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2724 Set owner reference for CNSVolumeInfo objects in PV informer events
  pkg/csi/service/common/vsphereutil.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2730 Revert "Set owner reference for CNSVolumeInfo objects in PV informer …
  pkg/csi/service/common/vsphereutil.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2733 Multi VC - Do not error out when list of candidate datastores is zero. Check other VCs also.
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2736 fix RWM volume creation when topology-aware-file-volume fss is disabled
  pkg/csi/service/vanilla/controller.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2725 Generate events on PV when volume cannot be created for static volumes
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2727 Skip CnsVolumeOperationRequest CR added event that are received during container restart
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2731 Skip storage policy usage field updates when values tends to sub-zero
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2696 Storagepolicyusage CR sync during Syncer Init & Full Sync
  pkg/internalapis/cnsvolumeinfo/cnsvolumeinfoservice.go
  pkg/internalapis/cnsvolumeinfo/v1alpha1/cnsvolumeinfo_types.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2726 Allow volume metadata cleanup of file volumes in multi vc deployments
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, cncf-cla: yes
