Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-08, with the labels that each got.

#2479 collect events from svc test namespace and add GinkgoRecover() to go routines with asserts
  tests/e2e/csi_cns_telemetry_statefulsets.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_file_share_negative.go
  tests/e2e/gc_full_sync.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/gc_rwx_basic.go
  tests/e2e/gc_rwx_deployments.go
  tests/e2e/gc_rwx_destructive.go
  tests/e2e/gc_rwx_multi_gc.go
  tests/e2e/gc_rwx_multi_ns_gc.go
  tests/e2e/gc_rwx_non_vsan_datastore.go
  tests/e2e/gc_rwx_operation_storm.go
  tests/e2e/gc_rwx_parallel_claim.go
  tests/e2e/gc_rwx_readonly.go
  tests/e2e/gc_rwx_reclaim_policy.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_service_down.go
  tests/e2e/gc_rwx_statefulsets.go
  tests/e2e/gc_rwx_static_provision.go
  tests/e2e/gc_rwx_syncer.go
  tests/e2e/gc_rwx_tkg_scale.go
  tests/e2e/gc_rwx_volume_health.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/labelupdates.go
  tests/e2e/multi_master_k8s.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/raw_block_volume.go
  tests/e2e/storagepolicy.go
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_site_down.go
  tests/e2e/util.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_shared_datastore.go
  tests/e2e/vsphere_volume_disksize.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2486 Block Vanilla and TKG tag fix for snapshot testcases
  tests/e2e/csi_snapshot_basic.go
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#2483 Multi-VC Preferential-Topology And Snapshot-Topology different test coverage automation
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/multi_vc.go
  tests/e2e/multi_vc_multi_replica.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/multi_vc_utils.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_disruptive.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/svmotion_volumes.go
  tests/e2e/topology_snapshot.go
  tests/e2e/vsphere.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2485 Ensure all CNS operations have a context timeout set
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2453 Snapshot new testcases automation for TKG
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/e2e_common.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/raw_block_volume.go
  tests/e2e/util.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2494 Bump golang.org/x/net/html to fix CVE-2023-3978
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2487 Fix shared datastore selection for vanilla
  pkg/common/cns-lib/vsphere/cluster_compute_resource.go
  pkg/common/cns-lib/vsphere/hostsystem.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/common/topology.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#2491 Multi-VC config secret tests coverage
  tests/e2e/config_change_test.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/e2e_common.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/multi_vc.go
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/multi_vc_multi_replica.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/multi_vc_utils.go
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_disruptive.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/topology_operation_strom_cases.go
  tests/e2e/topology_site_down_cases.go
  tests/e2e/topology_snapshot.go
  tests/e2e/util.go
  tests/e2e/volume_provisioning_with_level5_topology.go
  tests/e2e/vsphere.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2496 Snapshot automation code changes to support Guest Cluster
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/e2e_common.go
Labels: needs-ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#2489 supervisor: re-read config before creating vc client
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2497 fix: return err instead of nil in ListVolumes
  pkg/csi/service/wcp/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2500 Code fix for config secret test failures
  tests/e2e/config_secret.go
  tests/e2e/prevent_duplicate_cluster_ids.go
  tests/e2e/volume_provisioning_with_topology.go
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#2502 Bugfix for supporting folder type during volume provisioning in topology
  pkg/common/config/config.go
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/common/topology.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2503 tag v3.1.0-rc.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2480 Fix triggersync CR reconcilation
  pkg/syncer/cnsoperator/controller/triggercsifullsync/triggercsifullsync_controller.go
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2505 supervisor: handle pnid change for listview
  pkg/common/cns-lib/volume/listview.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2514 Generate webhook cert with 180 days validity
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/deploy-vsphere-csi-validation-webhook.sh
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2510 Storage policy compatibility should be given higher preference than preferential datastores
  pkg/csi/service/common/placementengine/placement.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes, release-3.1.0-candidate

#2515 Cherry pick PRs release 3.1
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/deploy-vsphere-csi-validation-webhook.sh
  pkg/csi/service/common/placementengine/placement.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2516 tag v3.1.0-rc.2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2511 Bump github.com/elazarl/goproxy to fix CVE-2023-37788
  go.mod
  go.sum
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2521 Multi-VC disruptive Site-down test scenarios automation
  tests/e2e/e2e_common.go
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/multi_vc_operation_storm.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/multi_vc_site_down.go
  tests/e2e/multi_vc_utils.go
  tests/e2e/preferential_topology_disruptive.go
  tests/e2e/preferential_topology_utils.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2523 Static provisioning and List-volume test coverage on a multi-vc setup
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/multi_vc.go
  tests/e2e/multi_vc_multi_replica.go
  tests/e2e/multi_vc_operation_storm.go
  tests/e2e/multi_vc_site_down.go
  tests/e2e/multi_vc_utils.go
  tests/e2e/multi_vc_vsphere.go
  tests/e2e/prevent_duplicate_cluster_ids.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2526 Service Yaml path fix
  tests/e2e/suite_test.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2525 Bugfix: Error out ControllerExpandVolume when volume is not found during a resize operation
  pkg/csi/service/common/vsphereutil.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.1.0-candidate

#2528 Update leader election lease arguments to reduce delay in syncer startup
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes, release-3.1.0-candidate

#2527 Bugfix: Error out ControllerExpandVolume when volume is not found during a resize operation
  pkg/csi/service/common/vsphereutil.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2529 Cherry-pick : Update leader election lease arguments to reduce delay in syncer startup
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes
