Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-04, with the labels that each got.

#2318 Cherrypick PR 2149 to release-2.7 to revert changes related to PVC creation perf regression
  pkg/csi/service/wcpguest/controller_helper.go
Labels: approved, size/M, cncf-cla: yes

#2319 Cherrypick PR 2192 - Remove service mode check for consistent fss checking across all CSI containers
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: approved, size/M, cncf-cla: yes

#2320 Add pvcsi 1.24 & 1.25 yamls
  manifests/guestcluster/1.24/pvcsi.yaml
  manifests/guestcluster/1.25/pvcsi.yaml
Labels: approved, size/XXL, cncf-cla: yes

#2321 Set initialDelaySeconds to 30 seconds and periodSeconds to 180 for livenessprobe and enable leader election for syncer
  cmd/syncer/main.go
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/guestcluster/1.24/pvcsi.yaml
  manifests/guestcluster/1.25/pvcsi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
Labels: approved, size/M, cncf-cla: yes

#2293 Classify InvalidHostState & HostNotConnected faults as non-storage faults
  pkg/common/cns-lib/volume/util.go
  pkg/common/fault/constants.go
  pkg/common/fault/util.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2325 Release tag v2.7.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2300 Skip creating new client for listview in case of ReloadConfig
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/listview_if.go
  pkg/common/cns-lib/volume/manager.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2272 fix: add task to map first, listview later
  pkg/common/cns-lib/volume/listview.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2317 CSI driver changes to enable webhook on guest cluster
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/admissionhandler/pvcsi_admissionhandler.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2326 Fix [CVE-2023-27561](https://github.com/advisories/GHSA-vpvm-3wq2-2wvm)
  go.mod
  go.sum
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2330 Add PSA label to CSI namespace for 1.25 PVCSI deployment yaml
  manifests/guestcluster/1.25/pvcsi.yaml
Labels: size/XS, approved, cncf-cla: yes

#2331 Add PVCSI 1.25 deployment yaml
  manifests/guestcluster/1.25/pvcsi.yaml
Labels: approved, size/XL, cncf-cla: yes

#2292 [Fix-Snapshot-tests] : Fixing snapshot intermittent test failures
  tests/e2e/csi_cns_telemetry_vc_reboot.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_file_volume.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/raw_block_volume.go
  tests/e2e/topology_snapshot.go
  tests/e2e/util.go
  tests/e2e/vsphere.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2334 [CSI Snapshot]Fix variable shadowing issue
  manifests/guestcluster/1.22/pvcsi.yaml
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/guestcluster/1.24/pvcsi.yaml
  manifests/guestcluster/1.25/pvcsi.yaml
  pkg/csi/service/common/common_controller_helper.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2332 Adding Polling to check if pvc deletion is succesfull
  tests/e2e/labelupdates.go
  tests/e2e/util.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2335 Fix NotAuthenticated issue in snapshot test
  tests/e2e/util.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2333 Update logic for disabling snapshot creation directly initiated on supervisor cluster
  manifests/supervisorcluster/1.21/cns-csi.yaml
  manifests/supervisorcluster/1.22/cns-csi.yaml
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/syncer/admissionhandler/validatesnapshotoperationsupervisorrequest.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2337 Fix NotAuthenticated issue in E2E tests
  tests/e2e/vsphere.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2309 Prevent duplicate cluster ID test automation
  tests/e2e/config_secret.go
  tests/e2e/config_secret_utils.go
  tests/e2e/e2e_common.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/prevent_duplicate_cluster_ids.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2314 TKGS-HA statefulset podAffinity, PodAntiAffinity and VC reboot tests
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/util.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#2066 Volume allocation tests for vsan direct
  tests/e2e/docs/supervisor_cluster_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/storage_policy_utils.go
  tests/e2e/util.go
Labels: approved, lgtm, lifecycle/stale, ok-to-test, size/XL, cncf-cla: yes

#2344 Fix minor bugs in raw block volume testcase, causing failures intermittently.
  tests/e2e/nodes_scaleup_scaledown.go
  tests/e2e/raw_block_volume.go
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#2327 Wait for 2 full sync cycles to delete volumeInfo CRs
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/types.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2348 Initialise volume migration service for full sync in single VC setup
  pkg/syncer/fullsync.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.0.1-candidate

#2236 TC to verify VCP to CSI migration workflow with xfs filesystem
  tests/e2e/vcp_to_csi_syncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2349 Cherry pick PR 2348 and 2327
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/types.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2345 Fix kubelet and kube-scheduler package versions
  go.mod
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2350 tag images for v3.0.1-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2351 Cherry-pick go mod package cleanup - PR #2345
  go.mod
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2316 Return Success when CNS DeleteVolume returns NotFound fault
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2355 simplify not found fault handling during delete volume
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#2353 Return volume content source in CreateVolumeResponse whenever applicable
  pkg/csi/service/wcp/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2352 [CSI Snapshot] Check for Status field before access and introduce snapshot timeout
  manifests/guestcluster/1.23/pvcsi.yaml
  manifests/guestcluster/1.24/pvcsi.yaml
  manifests/guestcluster/1.25/pvcsi.yaml
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2264 Update Go to 1.20
  go.mod
  hack/release.sh
  images/ci/Dockerfile
  images/driver/Dockerfile
  images/syncer/Dockerfile
  images/windows/driver/Dockerfile
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2322 CNS Relocate API tests
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/svmotion_detached_volume.go
  tests/e2e/svmotion_volumes.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2339 Prevent Cluster ID Automation Part2
  tests/e2e/prevent_duplicate_cluster_ids.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2329 TKGS-HA static provisioning across GC
  tests/e2e/tkgs_ha.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2356 During snapshot restore operation, fetch datacenter details correctly as per vsphere-config-secret values for different cluster flavors
  pkg/common/utils/utils.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/vsphereutil.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2363 tag v3.0.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes
