Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-10, with the labels that each got.

#2576 Bump up govmomi to 0.32.0
  go.mod
  go.sum
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.1.1-candidate

#2365 Static provisioning and fstype related testcases automation
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/labelupdates.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/svmotion_volumes.go
  tests/e2e/util.go
  tests/e2e/vsphere_file_volume_basic_mount.go
  tests/e2e/vsphere_volume_disksize.go
  tests/e2e/vsphere_volume_fstype.go
Labels: needs-ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#2582 vanilla: add guard for uninitialized volumeMigrationService in case of multi-vc
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.1.1-candidate, release-3.0.3-candidate

#2551 Add e2e tests for vmService VMs with PVC
  go.mod
  go.sum
  tests/e2e/util.go
  tests/e2e/vm_service_utils.go
  tests/e2e/vmservice_vm.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#2586 fix go.sum issue which is failing precheckin pipelines
  go.sum
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2583 cherry-pick: add guard for uninitialized volumeMigrationService in case of multi-vc (#2582)
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2584 cherry-pick: add guard for uninitialized volumeMigrationService in case of multi-vc (#2582)
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2590 tag CSI images to v3.0.3-rc.2
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2589 Add myself as a reviewer and approver
  OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2591 tag CSI images to v3.1.1-rc.2
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2598 VMC TKG API changes
  tests/e2e/e2e_common.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2592 fix: handle gap in govmomi error handling for expired tasks
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/manager.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2597 Prevent node cache update during attach & detach
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.1.1-candidate, release-3.0.3-candidate, release-2.7.3-candidate

#2595 Validate vCenter username and crash CSI driver if username is not a fully qualified domain name
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/syncer_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2600 Cherry-pick : Prevent node cache update during attach & detach (#2597)
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2601 Cherry-pick : Prevent node cache update during attach & detach (#2597)
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/manager_test.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/common/topology.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2604 tag v3.1.1-rc.3 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2602 Rename interface method names and prevent node cache update during attach & detach
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2603 Tkg snapshot multi guest cluster testcase
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_utils.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2580 add support for multiple clusters per az in supervisor
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2607 tag CSI images to v2.7.3-rc.2
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2609 CVE-2023-44487: bump golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2581 register static volume on stretched supervisor
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2569 Check volumeAttachment status is set to true in CSIAttach for WCP
  pkg/csi/service/wcp/controller.go
Labels: size/S, approved, cncf-cla: yes

#2612 Replace usage of golang.org/x/net/context with context from std library
  pkg/csi/service/common/util.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/node.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2613 tag v3.1.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2615 tag v3.0.3 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2614 tag v2.7.3 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2610 Change name of CNSVolumeInfo CR for file volumes
  pkg/internalapis/cnsvolumeinfo/cnsvolumeinfoservice.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2618 Bump up golang ci lint
  hack/check-golangci-lint.sh
Labels: size/XS, approved, cncf-cla: yes

#2622 Bump up snapshotter to v6.3.1
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, ok-to-test, cncf-cla: yes

#2616 [CSI 2.6.x] Cross-port telemetry enhancements and the nodes cache fix during attach/detach
  cmd/syncer/main.go
  hack/check-staticcheck.sh
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/vsan_stretched_cluster.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2617 [CSI 2.6] Bug Fix for device is already deleted while unmount volume
  pkg/csi/service/osutils/linux_os_utils.go
Labels: approved, lgtm, size/M, cncf-cla: yes
