Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-09, with the labels that each got.

#2531 Cherry-pick : Bump github.com/elazarl/goproxy to fix CVE-2023-37788
  go.mod
  go.sum
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2530 Update rc image tags for 3.1 manifests
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2538 fix GetHostsForSegment to return correct list of hosts for all segments
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/common/topology.go
Labels: size/L, approved, lgtm, cncf-cla: yes, release-3.1.0-candidate

#2540 Match topology key in example yaml files with the vSphere CSI official docs
  example/vanilla-k8s-RWO-filesystem-volumes/example-sc-WaitForFirstConsumer-restricted.yaml
  example/vanilla-k8s-RWO-filesystem-volumes/example-sc-multiple-zones.yaml
  example/vanilla-k8s-RWO-filesystem-volumes/example-sc-single-zone.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes, release-3.1.0-candidate

#2541 Cherry pick pr-2538 pr-2540 release 3.1
  example/vanilla-k8s-RWO-filesystem-volumes/example-sc-WaitForFirstConsumer-restricted.yaml
  example/vanilla-k8s-RWO-filesystem-volumes/example-sc-multiple-zones.yaml
  example/vanilla-k8s-RWO-filesystem-volumes/example-sc-single-zone.yaml
  pkg/csi/service/common/placementengine/placement.go
  pkg/csi/service/common/topology.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2542 Remove fail fast mechanism during compatible datastore computation in case of multiple topology segments
  pkg/csi/service/common/placementengine/placement.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.1.0-candidate

#2543 cherry pick pr-2542 to release-3.1
  pkg/csi/service/common/placementengine/placement.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2544 Update rc image to 3.1.0-rc.4
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2520 Add code for metrics gathering
  pkg/common/cns-lib/vsphere/cns.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/prometheus/metrics.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2548 Return error for IsDiskAttached when vmDevices are empty
  pkg/common/cns-lib/volume/util.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.1.0-candidate

#2546 skip adding node to cache during attach or detach operation
  pkg/common/cns-lib/node/manager.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2549 Cherry-pick : Return error for IsDiskAttached when vmDevices are empty (#2548)
  pkg/common/cns-lib/volume/util.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2550 tag CSI images as v3.1.0-rc.5
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2539 Fix expected ClusterDistribution value in e2e tests & restart CSI Driver whenever ClusterDistribution is modified
  tests/e2e/csi_cns_telemetry.go
Labels: approved, size/M, cncf-cla: yes

#2513 Snapshot Negative testcases for TKG
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/e2e_common.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2536 Topology code fixes
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/volume_provisioning_with_topology.go
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#2554 Tag CSI images for 3.1.0 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2461 Policy driven changes for volume allocation in vsan direct
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/util.go
  tests/e2e/vsphere_volume_expansion.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2557 TKG testcases automation for Snapshot
  tests/e2e/csi_snapshot_basic.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2555 Upgrade sidecars to latest versions
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2559 Ginkgo labels assignment to topology testcases
  tests/e2e/e2e_common.go
  tests/e2e/invalid_topology_values.go
  tests/e2e/multi_vc.go
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/multi_vc_multi_replica.go
  tests/e2e/multi_vc_operation_storm.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/multi_vc_site_down.go
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_disruptive.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/statefulset_with_topology.go
  tests/e2e/topology_aware_node_poweroff.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/topology_new_node_with_different_labels.go
  tests/e2e/topology_operation_strom_cases.go
  tests/e2e/topology_site_down_cases.go
  tests/e2e/topology_snapshot.go
  tests/e2e/volume_provisioning_with_level5_topology.go
  tests/e2e/volume_provisioning_with_topology.go
Labels: needs-ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#2558 vanilla: return volume path as part of ListVolumes response for migrated in-tree volumes
  pkg/apis/migration/migration.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes, release-3.1.1-candidate

#2535 New Test Cases for Resize of VCPtoCSI Migrated Volumes
  tests/e2e/docs/vanilla_cluster_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/statefulsets.go
  tests/e2e/vcp_to_csi_create_delete.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2568 Cross-port recent bug fixes to 3.1 branch
  pkg/apis/migration/migration.go
  pkg/common/cns-lib/node/manager.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/vanilla/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2572 tag v3.1.1-rc.1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2560 Run vSphere CSI controller pod with non-root user on supervisor cluster
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2573 [CSI 2.7.3] Cross-port telemetry enhancements and the nodes cache fix during attach/detach.
  cmd/syncer/main.go
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2561 [CSI 3.0.3] Cross-port telemetry enhancements, CSI Migration bug fix related to AttachVolumes and also the nodes cache fix during attach/detach.
  cmd/syncer/main.go
  pkg/apis/migration/migration.go
  pkg/common/cns-lib/node/manager.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/vanilla/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2574 tag CSI images to v3.0.3-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2575 tag CSI images to v2.7.3-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2519 Volume Snapshot scenarios for TKGS HA
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/raw_block_volume.go
  tests/e2e/tkgs_ha.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2577 fss for PodVMOnStretchedSupervisor
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  pkg/csi/service/common/constants.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes
