Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-07, with the labels that each got.

#2464 add: cns-csi.yaml for 1.27
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.27/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2467 tag images for v3.0.2 release
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2468 wcp: specify recommended tls 1.2 ciphers for webhook
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2462 List volume test for WCP and File vanilla
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/statefulsets.go
  tests/e2e/util.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#2463 Adding Ginkgo labels to testcases specific to its type
  tests/e2e/config_secret.go
  tests/e2e/e2e_common.go
  tests/e2e/preferential_topology.go
  tests/e2e/volume_provisioning_with_level5_topology.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2472 remove securityContext for supervisor
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2469 vanilla: specify recommended tls 1.2 ciphers for webhook
  pkg/syncer/admissionhandler/admissionhandler.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2457 Multi vCenters different test scenarios automation
  tests/e2e/e2e_common.go
  tests/e2e/multi_vc.go
  tests/e2e/multi_vc_bootstrap.go
  tests/e2e/multi_vc_connection.go
  tests/e2e/multi_vc_utils.go
  tests/e2e/multi_vc_vsphere.go
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_disruptive.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/tkgs_ha.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/topology_operation_strom_cases.go
  tests/e2e/topology_site_down_cases.go
  tests/e2e/topology_snapshot.go
  tests/e2e/util.go
  tests/e2e/volume_provisioning_with_level5_topology.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2470 Delete stale CnsVSphereVolumeMigration CR only when PV is not found in k8s
  pkg/apis/migration/migration.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2446 Remove "volume.beta.kubernetes.io/storage-class" references from test code
  tests/e2e/csi_cns_telemetry_statefulsets.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/gc_rwx_destructive.go
  tests/e2e/gc_rwx_statefulsets.go
  tests/e2e/gc_rwx_tkg_scale.go
  tests/e2e/labelupdates.go
  tests/e2e/nodes_scaleup_scaledown.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/preupgrade_datasetup.go
  tests/e2e/raw_block_volume.go
  tests/e2e/staging_env_basic.go
  tests/e2e/statefulset_xfs.go
  tests/e2e/statefulsets.go
  tests/e2e/testing-manifests/statefulset/nginx/statefulset.yaml
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_site_down.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/volume_provisioning_with_level5_topology.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2474 Avoid GET call for CSINodeTopology instance in GC nodes
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2431 Fix VC session leaks
  cmd/syncer/main.go
  cmd/vsphere-csi/main.go
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/listview_if.go
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/utils/utils.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2460 Add cluster identifier to user agent of the vc sessions
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/config/config.go
  pkg/syncer/util.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2477 Enable block-volume-snapshot FSS and add csi-snapshotter sidecar in pvCSI yaml
  manifests/guestcluster/1.24/pvcsi.yaml
  manifests/guestcluster/1.25/pvcsi.yaml
  manifests/guestcluster/1.26/pvcsi.yaml
  manifests/guestcluster/1.27/pvcsi.yaml
  pkg/csi/service/wcpguest/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2466 GC snapshot automation code
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/raw_block_volume.go
  tests/e2e/util.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2481 Use Node name as NodeId in Guest Clusters
  pkg/csi/service/node.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes
