Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2023-05, with the labels that each got.

#2366 edit info log to print vc host only
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/listview_test.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2359 CNS Relocate API tests automation
  tests/e2e/policy_driven_vol_allocation.go
Labels: needs-ok-to-test, approved, lgtm, size/XL, cncf-cla: yes

#2369 Skip PVC annotation validations for PVC deletes
  pkg/syncer/admissionhandler/validatepvc.go
  pkg/syncer/admissionhandler/validatepvcannotationfortkgsha.go
  pkg/syncer/admissionhandler/validatepvcannotationforvolumehealth.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2375 removing GAed features doc from Github repo
  docs/book/features/csi_driver_on_windows.md
  docs/book/features/raw_block_volume.md
  docs/book/features/volume_snapshot.md
  docs/book/features/vsphere_csi_migration.md
Labels: approved, lgtm, size/XL, cncf-cla: yes

#2378 [CICD]: Enable staging E2E tests
  .gitlab-ci.yml
  pipeline/e2e-tests-staging.sh
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2383 Revert "Fix code to get node from k8s apis (#2374)"
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/manager_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2382 [CICD]: Improvisation to CICD scripts & introducing cleanup-dev stage to release testbeds
  .gitlab-ci.yml
  pipeline/deploy.sh
  pipeline/e2e-tests.sh
  pipeline/release-testbed.sh
  pipeline/send_slack_notification.sh
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2384 Changes in TKG API for Cluster Creation in VMC
  tests/e2e/e2e_common.go
  tests/e2e/testing-manifests/tkg/tkg.yaml
  tests/e2e/util.go
  tests/e2e/vmc_create_gc.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2386 Populate supervisor FSS values for node plugin in guest cluster
  manifests/guestcluster/1.25/pvcsi.yaml
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2390 Fixing comments in the code.
  .gitlab-ci.yml
  hack/release.sh
  images/ci/e2e/Dockerfile
Labels: size/S, approved, lgtm, cncf-cla: yes

#2391 [CICD]: Update deploy-dev stage to update only syncer and container images
  pipeline/deploy.sh
Labels: size/S, needs-ok-to-test, approved, lgtm, cncf-cla: yes

#2398 Set volumesnapshotname variable in GC CreateVolume to input snapshot-ID in all cases
  pkg/csi/service/wcpguest/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2387 Fix use of GetNodeByName when using node's VMUUID
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/node/manager_test.go
  pkg/common/cns-lib/node/nodes.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2401 enable list-volume fss for supervisor cluster
  manifests/supervisorcluster/1.23/cns-csi.yaml
  manifests/supervisorcluster/1.24/cns-csi.yaml
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2403 increase timeouts in some volume allocation tests to account for slow infra
  tests/e2e/policy_driven_vol_allocation.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2379 Support PV to BackingDisk ID mapping for multi VC deployment
  pkg/syncer/metadatasyncer.go
  pkg/syncer/pv_to_backingdiskobjectid_mapping.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes, release-3.0.2-candidate

#2395 fix: list-volume fails in multi-vcenter environment
  pkg/csi/service/vanilla/controller_helper.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.0.2-candidate

#2406 Add pvcsi 1.26 & 1.27 k8s yaml
  manifests/guestcluster/1.26/pvcsi.yaml
  manifests/guestcluster/1.27/pvcsi.yaml
Labels: approved, size/XXL, cncf-cla: yes

#2408 Cherry-pick pvcsi 1.25, 1.26 & 1.27 deployment yamls
  manifests/guestcluster/1.25/pvcsi.yaml
  manifests/guestcluster/1.26/pvcsi.yaml
  manifests/guestcluster/1.27/pvcsi.yaml
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: approved, size/XXL, cncf-cla: yes
