Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2024-10, with the labels that each got.

#3074 fix createfilevolume for workload-management-isolation
  pkg/csi/service/wcp/controller.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, WorkloadDomainIsolation

#3073 Fix syncing the aggregated snapshot size between CNSVolumeInfo and CNS query result
  go.mod
  go.sum
  pkg/common/cns-lib/vsphere/utils.go
  pkg/csi/service/common/authmanager.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/intended_state.go
  pkg/syncer/storagepool/listener.go
  pkg/syncer/storagepool/util.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3075 Periodic Sync to periodically calculate and patch storagequota "Reserved" values
  cmd/syncer/main.go
  go.mod
  go.sum
  manifests/supervisorcluster/1.30/cns-csi.yaml
  pkg/apis/cnsoperator/register.go
  pkg/apis/cnsoperator/storagequotaperiodicsync/v1alpha1/groupversion_info.go
  pkg/apis/cnsoperator/storagequotaperiodicsync/v1alpha1/storagequotaperiodicsync_types.go
  pkg/apis/cnsoperator/storagequotaperiodicsync/v1alpha1/zz_generated.deepcopy.go
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#3077 Enable Time Interval Update for StorageQuota Periodic Sync
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3064 Handle vc reboot session invalid for listview
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/listview_if.go
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/vanilla/controller_topology_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3080 Check for FSS value instead of WCP capability in pvCSI controller for Workload Domain Isolation feature
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/wcpguest/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation

#3062 Snapshot support on supervisor
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/e2e_common.go
  tests/e2e/multi_vc.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_disruptive.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/raw_block_volume.go
  tests/e2e/snapshot_stretched_supervisor.go
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/tkgs_ha.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/topology_snapshot.go
  tests/e2e/util.go
  tests/e2e/vmservice_utils.go
  tests/e2e/volume_provisioning_with_level5_topology.go
Labels: approved, size/XXL, lgtm, cncf-cla: yes

#3085 Fix upgrade issue in GetCapacity implementation
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/wcpguest/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation

#3084 Update go.mod to 1.22.8
  go.mod
  hack/release.sh
  images/ci/Dockerfile
  images/driver/Dockerfile
  images/syncer/Dockerfile
  images/windows/driver/Dockerfile
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3088 Storage policy resource quota sc name fix
  tests/e2e/snapshot_vmservice_vm.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3090 Fix vmservice extension name
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3092 Writing data into the volume from Pod code fix
  tests/e2e/util.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#3094 Bump up provisioner tag in WCP YAML to include recent bugfixes
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3096 Add nil checks when accessing VolumeSnapshot status
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3095 upgrade grpc-go to fix CVE-2024-7246
  go.mod
  go.sum
  pkg/csi/service/wcp/controller_helper.go
Labels: size/L, approved, lgtm, cncf-cla: yes
