Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2024-03, with the labels that each got.

#2813 Add Supervisor 1.29 YAML file
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.29/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2809 Supervisor: upgrade sidecars provisioner, resizer, snapshotter, attacher and livenessprobe
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2817 tag vSphere CSI Driver images for v3.2.0
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2818 [E2E-Test-Fix]: Fixing NotAuthenticated issue in tests
  tests/e2e/util.go
  tests/e2e/vsphere.go
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#2821 bump up govmomi to v0.36.1
  go.mod
  go.sum
Labels: size/S, approved, lgtm, cncf-cla: yes

#2825 remove usage of deprecated API WaitForResult
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/manager.go
  pkg/syncer/storagepool/listener.go
  pkg/syncer/storagepool/migrationController.go
  tests/e2e/multi_vc_utils.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/vcp_to_csi_create_delete.go
  tests/e2e/vsphere.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2820 CVE-2024-24786: bump google.golang.org/protobuf to v1.33.0
  go.mod
  go.sum
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2822 [File Vanilla e2e test fix]: Fixing intermittent test issues in File Vanilla Pipelines
  tests/e2e/bootstrap.go
  tests/e2e/connection.go
  tests/e2e/csi_cns_telemetry.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/csi_static_provisioning_file_basic.go
  tests/e2e/tkgs_ha.go
  tests/e2e/util.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2830 fixed nil error causing error while marshaling
  pkg/csi/service/wcp/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2811 Use lock per VolumeId during NodeUnstageVolume operation to avoid conflicts during volume unmount
  pkg/common/cns-lib/node/volume_operation_lock.go
  pkg/csi/service/driver.go
  pkg/csi/service/node.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2832 Add pvcsi 1.29 k8s yaml
  manifests/guestcluster/1.29/pvcsi.yaml
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2834 Initialize volume locks in driver init
  pkg/csi/service/driver.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2837 Handle StoragePolicyUsageCR cleanup in StoragePolicyQuotaCR delete event
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2838 (do-not-merge) Fix GetTKGVMIP() logic in VDS for vm-op v1alpha1
  pkg/syncer/cnsoperator/util/util.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2833 Change VM Op VM Update call to Patch
  pkg/csi/service/wcpguest/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes
