Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2024-05, with the labels that each got.

#2866 Create/delete StoragePolicyUsage CR for VolumeSnapshot resource kind on create/delete of StoragePolicyQuota CR
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2870 Update CSI snapshotter version to latest in supervisor cns-csi.yaml, to include CVE fixes
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2865 CSI unit tests framework improvement
  Makefile
  pkg/common/cns-lib/node/manager.go
  pkg/common/cns-lib/vsphere/cns_test.go
  pkg/common/cns-lib/vsphere/tagmanager_test_utils.go
  pkg/common/cns-lib/vsphere/virtualmachine_test.go
  pkg/common/unittestcommon/types.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/vanilla/controller_topology_test.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/syncer_test.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#2876 Bump up sidecar versions to latest releases
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2868 For windows mount point, check directory mode for symlink check instead of CSI proxy isSymLink() function, to handle corrupted mount point in case node reboot
  pkg/csi/service/mounter/mounter_windows.go
  pkg/csi/service/osutils/windows_os_utils.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2880 Update k8s cluster distribution map to record EKS & AKS clusters
  cmd/syncer/main.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.3.0-candidate

#2877 remove x509sha1 support and overriding tlsmaxrsasize
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.3.0-candidate

#2885 Cherry-pick PR: Update k8s cluster distributors list (#2880)
  cmd/syncer/main.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2886 [cherry-pick-release-3.3] remove x509sha1 support and overriding tlsmaxrsasize (#2877)
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2887 Tag CSI images to v3.3.0-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2884 vc reboot test fix
  tests/e2e/csi_cns_telemetry_vc_reboot.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/tkgs_ha.go
  tests/e2e/util.go
  tests/e2e/vc_reboot_volume_lifecycle.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2593 GetDevMounts: eval symlinks found in mount table
  pkg/csi/service/osutils/linux_os_utils.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.3.0-candidate

#2891 [cherrypick - release-3.3] GetDevMounts: eval symlinks found in mount table (#2593)
  pkg/csi/service/osutils/linux_os_utils.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2892 tag v3.3.0-rc.2 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#2895 Ensure creation of StoragePolicyUsage CR in fullSync
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2897 Add pvcsi 1.30 deployment yaml
  manifests/guestcluster/1.30/pvcsi.yaml
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#2857 Update Snapshot-specific CnsVolumeOperationDetails in CSI CreateSnapshot
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2896 Unit test changes related to StoragePolicy in vSphere CSI plugin
  go.mod
  go.sum
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2890 Increase csi-attacher worker threads to 100 for Supervisor
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2906 Add Pre-Upgrade Data creation tests to test framework
  tests/e2e/preupgrade_datasetup.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#2905 vc reboot fix
  tests/e2e/util.go
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#2893 RWX Topology automation code for HCI-Mesh and No-HCI Mesh Level5 and Level2 Topology setups
  tests/e2e/e2e_common.go
  tests/e2e/hci_mesh_rwx_singlevc_topology.go
  tests/e2e/multi_vc.go
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/multi_vc_multi_replica.go
  tests/e2e/multi_vc_operation_storm.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/multi_vc_site_down.go
  tests/e2e/multi_vc_utils.go
  tests/e2e/no_hci_mesh_rwx_multivc_topology.go
  tests/e2e/no_hci_mesh_rwx_singlevc_topology.go
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_disruptive.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/rwx_topology_utils.go
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_site_down.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/topology_operation_strom_cases.go
  tests/e2e/topology_site_down_cases.go
  tests/e2e/topology_snapshot.go
  tests/e2e/util.go
  tests/e2e/vmservice_vm.go
  tests/e2e/volume_provisioning_with_level5_topology.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#2900 Removing myself from OWNERS file in tests/e2e
  tests/e2e/OWNERS
Labels: size/XS, approved, lgtm, cncf-cla: yes
