Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2024-08, with the labels that each got.

#2979 Put CnsUnregisterVolume controller init behind FSS check
  pkg/syncer/cnsoperator/controller/cnsunregistervolume/cnsunregistervolume_controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2972 Add implementation for CnsUnregisterVolume controller
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  pkg/apis/cnsoperator/cnsunregistervolume/v1alpha1/cnsunregistervolume_types.go
  pkg/apis/cnsoperator/config/cnsunregistervolume_crd.yaml
  pkg/syncer/cnsoperator/controller/cnsunregistervolume/cnsunregistervolume_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2977 Add RBAC for workload domain isolation feature
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller_test.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2984 Fix aggregated snapshot size formatting and other fixes
  pkg/common/cns-lib/volume/manager.go
  pkg/csi/service/common/util.go
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2978 use pagination to query all volumes using clusterid
  pkg/apis/migration/migration.go
  pkg/common/utils/utils.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/pv_to_backingdiskobjectid_mapping.go
  pkg/syncer/volume_health.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2888 Reconcile storagepolicyquota in syncer
  pkg/kubernetes/dynamicInformers.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storage_policy_quota_reconciler.go
  pkg/syncer/types.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2998 remove netlify build
  hack/build-gitbooks.sh
  netlify.toml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2992 re-create listview object every time a session becomes invalid
  pkg/common/cns-lib/volume/listview.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2999 check CSI migration fss once for vanilla cluster flavor
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2996 Add new parameter "fileVolumeActivated" in vSphere CSI secret to indicate whether file service is enabled or not
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/config/types.go
  tests/e2e/config.go
  tests/e2e/util.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2993 Set CNS dev version for CNS Client and Vim Client
  pkg/syncer/storagepool/service.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2994 fix getPVWithVolumeID to get PV from cached volume ID to PV map
  pkg/common/utils/utils.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
Labels: size/L, approved, cncf-cla: yes, 50k Volumes Support

#3004 Update CSI snapshotter version to latest in supervisor cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3001 Fix firstOperationDetails and latestOperationDetails population in CnsVolumeOperationRequest
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3003 Set CSI attacher reconcile sync to 10 minutes
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, 50k Volumes Support

#2987 Provisioning-volume-exceeding-quota
  tests/e2e/storagepolicy.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2995 Add cleanup routine for CnsUnregisterVolume instances
  pkg/syncer/cnsoperator/manager/cleanupcustomresources.go
  pkg/syncer/cnsoperator/manager/init.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3005 fix fullSyncGetQueryResults function to use batch of volumeIds for query
  pkg/common/utils/utils.go
  pkg/syncer/types.go
  pkg/syncer/util.go
Labels: approved, lgtm, size/M, cncf-cla: yes, 50k Volumes Support

#3014 disable netlify build
  netlify.toml
Labels: size/XS, approved, cncf-cla: yes

#3013 add cloudbuild config for vsphere csi
  cloudbuild.yaml
  hack/release.sh
Labels: approved, lgtm, size/M, cncf-cla: yes

#2985 WorkloadDomainIsolation: Volume provisioning support for single & multi zone supervisor
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/k8sorchestrator/wcp_node.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcp/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation
