Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2024-09, with the labels that each got.

#3009 Allow provision RWM volume on the requested zone provided by topology requirements in WCP
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_test.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes, WorkloadDomainIsolation

#3011 Bug fix: static volume provision fails with panic while updating storagepolicyusage
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3025 Revert "fix getPVWithVolumeID to get PV from cached volume ID to PV map"
  pkg/csi/service/wcp/controller.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3017 WorkloadDomainIsolation: Static volume support on supervisor
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation

#3026 Re-create CSINodes for Supervisor worker nodes to publish zone topology label as topology keys.
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  pkg/csi/service/common/commonco/k8sorchestrator/wcp_node.go
Labels: approved, lgtm, size/M, cncf-cla: yes, WorkloadDomainIsolation

#3012 Add validations in CnsUnregisterVolume controller
  pkg/syncer/cnsoperator/controller/cnsunregistervolume/cnsunregistervolume_controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3033 Bump up CSI provisioner in WCP to support WorkloadDomainIsolation feature
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3031 set node affinity rules on the TKG PV using volume-accessible-topology annotation on supervisor PVC
  manifests/guestcluster/1.28/pvcsi.yaml
  manifests/guestcluster/1.29/pvcsi.yaml
  manifests/guestcluster/1.30/pvcsi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  pkg/csi/service/common/constants.go
  pkg/syncer/pvcsi_fullsync.go
  pkg/syncer/pvcsi_fullsync_test.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, cncf-cla: yes, WorkloadDomainIsolation

#3037 update CI latest images for vanilla
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#3042 upgrade staticcheck and fix staticcheck linter issues
  hack/check-staticcheck.sh
  pkg/apis/storagepool/apis.go
  pkg/common/cns-lib/node/nodes.go
  pkg/common/cns-lib/volume/util.go
  pkg/common/cns-lib/vsphere/datacenter.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/config/config.go
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/osutils/linux_os_utils.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/syncer/k8scloudoperator/placement.go
  pkg/syncer/storagepool/intended_state.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/vcp_to_csi_create_delete.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#3038 Always allow VolumeSnapshot operations on Supervisor
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/validatesnapshotoperation.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#2983 Allow Storagetopologytype as Hostlocal
  pkg/csi/service/wcp/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3034 WorkloadDomainIsolation: Storage capacity support to prevent volume provisioning in prohibited zones
  manifests/guestcluster/1.28/pvcsi.yaml
  manifests/guestcluster/1.29/pvcsi.yaml
  manifests/guestcluster/1.30/pvcsi.yaml
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/wcpguest/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation

#3046 fix: set volumeid for file volume response from cns response
  pkg/csi/service/wcp/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3047 fixes for 50k volume support
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  pkg/common/utils/utils.go
  pkg/syncer/util.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes, 50k Volumes Support

#3044 Add new field ReservationId in CnsVolumeOperationRequest CR under QuotaDetails
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
  pkg/internalapis/cnsvolumeoperationrequest/config/cns.vmware.com_cnsvolumeoperationrequests.yaml
  pkg/internalapis/cnsvolumeoperationrequest/util.go
  pkg/internalapis/cnsvolumeoperationrequest/v1alpha1/cnsvolumeoperationrequest_types.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3039 Add yaml files for Supervisor 1.30
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.30/kustomization.yaml
Labels: approved, lgtm, size/XL, cncf-cla: yes

#3048 Remove reconcile-sync time of 10 min from csi-attacher sidecar
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2917 vsan stretch TKG sanity testcase automation
  tests/e2e/e2e_common.go
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/gc_rwx_basic.go
  tests/e2e/gc_rwx_deployments.go
  tests/e2e/gc_rwx_destructive.go
  tests/e2e/gc_rwx_multi_gc.go
  tests/e2e/gc_rwx_multi_ns_gc.go
  tests/e2e/gc_rwx_operation_storm.go
  tests/e2e/gc_rwx_readonly.go
  tests/e2e/gc_rwx_reclaim_policy.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_statefulsets.go
  tests/e2e/gc_rwx_static_provision.go
  tests/e2e/gc_rwx_syncer.go
  tests/e2e/gc_rwx_tkg_scale.go
  tests/e2e/hci.go
  tests/e2e/multi_vc.go
  tests/e2e/prevent_duplicate_cluster_ids.go
  tests/e2e/statefulsets.go
  tests/e2e/util.go
  tests/e2e/vm_service_vsan_stretch_cluster.go
  tests/e2e/vmservice_utils.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: needs-ok-to-test, approved, do-not-merge/hold, size/XXL, cncf-cla: yes

#3049 Upgrade csi-provisioner to v5.0.2 in Supervisor manifests
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2960 Add RWX file volume support for vpc
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  pkg/csi/service/common/constants.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/util/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3055 remove base image referenced from cloud-provider-vsphere registry
  images/driver-base/Dockerfile
  images/driver-base/Makefile
  images/driver/Dockerfile
  images/syncer/Dockerfile
Labels: approved, lgtm, size/M, cncf-cla: yes

#3056 remove CI, release, PR build types
  hack/check-shell.sh
  hack/make.sh
  hack/match-release-tag.sh
  hack/release.sh
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#3057 multi-svc-test-fix
  tests/e2e/e2e_common.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3059 publish new images in readme file
  README.md
  hack/check-mdlint.sh
Labels: approved, lgtm, size/M, cncf-cla: yes

#3061 Wait for PVC & VolumeSnapshot deletion on supervisor
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/wcpguest/controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3066 fix cns register volume controller regression caused by PR-3017
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
Labels: size/S, approved, lgtm, cncf-cla: yes, WorkloadDomainIsolation

#3072 Bump up WCP provisioner image to v5.0.2_vmware.2
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3065 Set dev.version on CNS clients and Vim clients for fetching aggregatedSnapshotCapacity from CNS APIs
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/vsphere/cns.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/vanilla/controller_topology_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/diskDecommissionController.go
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/storagepool/service.go
  pkg/syncer/syncer_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes
