Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2024-11, with the labels that each got.

#3083 add fallback option for session related scenarios
  pkg/common/cns-lib/volume/listview.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3098 enable supervisor fss when supervisor capability is enabled
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation

#3097 Bump govmomi to support using MOID and moref on specs
  go.mod
  go.sum
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3099 Upgrade attacher, resizer, livenessprobe to resolve CVEs
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3071 Add tkc cluster labels on Supervisor PVC objects to help identify orphan Supervisor PVCs
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/syncer/pvcsi_fullsync.go
Labels: approved, size/M, cncf-cla: yes

#3100 add dynamic workload isolation fss enablement for PVCSI
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation

#3101 Check for change in WCP capabilities and restart syncer container
  pkg/kubernetes/informers.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation

#3103 restart guest controller when workload domain isolation fss is enabled
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation

#3104 Bump up provisioner tag to v5.0.2_vmware.4
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3105 Add GOTOOLCHAIN=auto for gcb-docker-gcloud to pickup go.mod version
  cloudbuild.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2990 Add pvcsi 1.31 & 1.32 yamls
  manifests/guestcluster/1.31/pvcsi.yaml
  manifests/guestcluster/1.32/pvcsi.yaml
Labels: approved, size/XXL, cncf-cla: yes

#3117 Bump up WCP provisioner version to include latest bugfixes
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3116 Query configmap if capability found disabled in the cached config-map
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation

#3119 fix mdlint image
  hack/check-mdlint.sh
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3106 Encryption of block volumes using EncryptionClasses
  cmd/syncer/main.go
  go.mod
  go.sum
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  pkg/common/cns-lib/crypto/client.go
  pkg/common/cns-lib/crypto/constants.go
  pkg/common/cns-lib/crypto/internal/storageclass.go
  pkg/common/cns-lib/crypto/kubernetes.go
  pkg/common/cns-lib/crypto/util.go
  pkg/common/cns-lib/volume/manager.go
  pkg/common/config/config.go
  pkg/common/prometheus/metrics.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/types.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/types/envvars.go
  pkg/kubernetes/informers.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/mutatepvccrypto.go
  pkg/syncer/admissionhandler/validatepvccrypto.go
  pkg/syncer/byokoperator/controller/common/options.go
  pkg/syncer/byokoperator/controller/controller.go
  pkg/syncer/byokoperator/controller/persistentvolumeclaim/persistentvolumeclaim_controller.go
  pkg/syncer/byokoperator/controller/persistentvolumeclaim/util.go
  pkg/syncer/byokoperator/controller/storageclass/storageclass_controller.go
  pkg/syncer/byokoperator/manager.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller_test.go
  pkg/syncer/cnsoperator/manager/init.go
  tests/e2e/crypto.go
  tests/e2e/crypto_utils.go
  tests/e2e/docs/supervisor_cluster_setup.md
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vmservice_utils.go
  tests/e2e/vsphere.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#3111 Fix Info log string concatenation in authmanager.go
  pkg/csi/service/common/authmanager.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3114 Inlude VolumeSnapshot with no Status set in Quota periodic sync calculation
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3120 Bumping up csi sidecar version for k8s 1.31
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes
