Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2024-02, with the labels that each got.

#2781 vanilla: disallow disabling GA'ed features
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator_test.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2749 Bugfix for Multi-VC: Avoid sending non-compatible datastores to CNS during CreateVolume
  pkg/csi/service/common/placementengine/placement.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2776 Optimize topology aware CreateVolume performance in WCP
  pkg/common/cns-lib/vsphere/utils.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/types/types.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_test.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/util.go
  pkg/syncer/storagepool/listener.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2766 Clean up go.mod direct dependencies and update k8s library to 1.27.10
  go.mod
  go.sum
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcpguest/controller.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/util.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller_test.go
  pkg/syncer/cnsoperator/util/util.go
  pkg/syncer/util.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2779 Update frequently used go libs to latest releases
  go.mod
  go.sum
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2780 Use WCP FSS configmap in CSI driver for features dependent on WCP service
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/constants.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2785 3.2 RC1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2786 Changing topology key for 2-Level Topology Setup
  tests/e2e/e2e_common.go
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#2789 Upgrade controller-gen to v0.14.0
  Makefile
  pkg/apis/storagepool/config/cns.vmware.com_storagepools.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2791 PodVM on stretched supervisor support: Bump up WCP provisioner
  manifests/supervisorcluster/1.25/cns-csi.yaml
  manifests/supervisorcluster/1.26/cns-csi.yaml
  manifests/supervisorcluster/1.27/cns-csi.yaml
  manifests/supervisorcluster/1.28/cns-csi.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#2788 fix: handle expired session for listview
  pkg/common/cns-lib/volume/listview.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes, release-3.2.0-candidate

#2793 Enable TopologyAwareFileVolume FSS
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: size/XS, approved, lgtm, cncf-cla: yes, release-3.2.0-candidate

#2782 Update resizer & snapshotter to latest release
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2795 Cherrypick 3.2 candidate commits and create RC2 images
  Makefile
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/apis/storagepool/config/cns.vmware.com_storagepools.yaml
  pkg/common/cns-lib/volume/listview.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#2794 [cherry-pick: release-3.1] fix: handle expired session for listview (#2788)
  Makefile
  pkg/apis/storagepool/config/cns.vmware.com_storagepools.yaml
  pkg/common/cns-lib/volume/listview.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2796 remove starting docker from makefile
  Makefile
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2798 remove starting docker from makefile (#2796)
  Makefile
Labels: size/XS, approved, lgtm, cncf-cla: yes

#2801 Debug log the FSS value in WCP cluster capabilities
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#2804 fix panic in getVMByInstanceUUIDInDatacenter func
  pkg/common/cns-lib/vsphere/virtualmachine.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#2805 detach disk from podvm if spherelet taking long time to delete powered off pod VM
  pkg/csi/service/wcp/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes
