Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2025-07, with the labels that each got.

#3366 Workload domain isolation disruptive test scenarios
  tests/e2e/mgmt_wrkld_domain_isolation_disruptive.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#3378 Adding nimbus util for nimbus related operations
  tests/e2e/nimbus/nimbus_utils.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#3379 Added a negative test case for cluster distribution
  tests/e2e/csi_cns_telemetry.go
  tests/e2e/util.go
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#3375 enhance clean up of CNSVolumeOperations instances to delete instances with latest TaskInvocationTimestamp older than 15 minutes
  pkg/common/config/config.go
  pkg/internalapis/cnsvolumeoperationrequest/cnsvolumeoperationrequest.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3382 Add vc package for vc related functions
  tests/e2e/vcutil/vc_util.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#3383 Adjusted timing and resolving test issue in topology and static volum…
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/topology_multi_replica.go
Labels: size/S, needs-ok-to-test, approved, lgtm, cncf-cla: yes

#3371 WLDI : Test cases for vsan-max configuration
  tests/e2e/e2e_common.go
  tests/e2e/mgmt_wrkld_domain_isolation_utils.go
  tests/e2e/nimbus_utils.go
  tests/e2e/vsan_max_tkg_wldi.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#3410 vSAN Max vSAN Stretch workload domain isolation usecase
  tests/e2e/vsan_max_tkg_wldi.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3384 Add support for creating volume from snapshot on different datastore
  go.mod
  go.sum
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/common/vsphereutil_test.go
  pkg/csi/service/wcp/controller.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3409 Remove FSS async-query-volume
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/common/unittestcommon/utils.go
  pkg/common/utils/utils.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/util.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3360 Prevent VKS CnsFileAccessConfig CR deletion
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/validate_cnffileaccessconfig.go
  pkg/syncer/admissionhandler/validate_cnsfileaccessconfig.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3346 Block shared disks from being attached to pod VMs
  pkg/csi/service/wcp/controller.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3388 Chore - Refactor Virtual Machine utils
  pkg/common/utils/utils.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcpguest/controller.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsunregistervolume/cnsunregistervolume_controller.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#3418 Performance Improvement - Optimize the volume attachment workflow
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3421 Performance Improvement - Optimize WCP controller publish volume
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcp/controller_helper_test.go
  pkg/syncer/cnsoperator/controller/cnsunregistervolume/cnsunregistervolume_controller.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.pb.go
  pkg/syncer/k8scloudoperator/k8scloudoperator.proto
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3351 CSI LinkedClone support
  manifests/guestcluster/1.31/pvcsi.yaml
  manifests/guestcluster/1.32/pvcsi.yaml
  manifests/guestcluster/1.33/pvcsi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/common/cns-lib/vsphere/cns.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/types.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/internalapis/cnsvolumeinfo/cnsvolumeinfoservice.go
  pkg/internalapis/cnsvolumeinfo/config/cns.vmware.com_cnsvolumeinfoes.yaml
  pkg/internalapis/cnsvolumeinfo/v1alpha1/cnsvolumeinfo_types.go
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/pvcsi_admissionhandler.go
  pkg/syncer/admissionhandler/validatepvc.go
  pkg/syncer/admissionhandler/validatesnapshotoperation.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#3424 Get the datastore accessible topology from the snapshot
  pkg/csi/service/wcp/controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3414 Do not reconcile for updating volume health annotation on TKG PVC if found deleted, even if TKG PV retained, for given supervisor PVC
  pkg/syncer/volume_health_reconciler.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3413 Support CreateVolume in Zones with Multiple vSphere Clusters
  go.mod
  go.sum
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/types/types.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/common/vsphereutil_test.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_topology_test.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcp/controller_helper.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#3427 fix checkPVCCondition to compare size
  pkg/csi/service/wcpguest/controller_helper.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3436 validate CNSRegistreVolume to disallow registering volume not accessible to active clusters on namespace
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#3431 Use VolFromSnapshotOnTargetDs FSS
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/csi/service/common/constants.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3435 Performance Improvement - Reduce `unstructured` usages from Storage Pools
  pkg/apis/storagepool/cns/v1alpha1/storagepool_types.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/k8scloudoperator/placement.go
  pkg/syncer/storagepool/diskDecommissionController.go
  pkg/syncer/storagepool/intended_state.go
  pkg/syncer/storagepool/listener.go
  pkg/syncer/storagepool/migrationController.go
  pkg/syncer/storagepool/util.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#3419 Implement session manager client on CSI
  docs/book/vc_shared_sessions.md
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/vc_session_manager.go
  pkg/common/cns-lib/vsphere/vc_session_manager_test.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/config/config.go
  pkg/common/config/config_test.go
  pkg/common/config/types.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/vsphereutil.go
  pkg/csi/service/common/vsphereutil_test.go
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#3392 Remove volume-extend fss
  manifests/guestcluster/1.33/pvcsi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcp/controller.go
  pkg/csi/service/wcpguest/controller.go
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3381 Updated owners file
  OWNERS
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3400 Remove FSS max-pvscsi-targets-per-vm
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/node.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3444 start zone informers and skip storagepool for multiple zone per cluster
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/k8sorchestrator/wcp_node.go
  pkg/csi/service/common/util.go
  pkg/csi/service/common/util_test.go
  pkg/csi/service/wcp/controller.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller_test.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/storagepool/service.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3456 Bump up provisioner version to 5.0.2_vmware.8 for Supervisor flavor
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3458 tag images with v3.5.0-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3459 tag images with v3.5.1-rc.1
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#3455 Missed updates to yaml files from PR3392/3397/3409
  manifests/guestcluster/1.32/pvcsi.yaml
  manifests/guestcluster/1.34/pvcsi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3320 Add new CnsNodeVmBatchAttachment CRD and its reconciliation
  go.mod
  go.sum
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/apis/cnsoperator/cnsnodevmbatchattachment/v1alpha1/cnsnodebatchvmattachment_types.go
  pkg/apis/cnsoperator/cnsnodevmbatchattachment/v1alpha1/doc.go
  pkg/apis/cnsoperator/cnsnodevmbatchattachment/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cnsoperator/config/cns.vmware.com_cnsnodevmattachments.yaml
  pkg/apis/cnsoperator/config/cns.vmware.com_cnsnodevmbatchattachments.yaml
  pkg/apis/cnsoperator/config/config.go
  pkg/apis/cnsoperator/register.go
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/util.go
  pkg/common/fault/constants.go
  pkg/common/prometheus/metrics.go
  pkg/common/unittestcommon/types.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/vsphereutil_test.go
  pkg/syncer/cnsoperator/controller/add_cnsnodevmbatchattachment.go
  pkg/syncer/cnsoperator/controller/cnsnodevmbatchattachment/cnsnodevmbatchattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsnodevmbatchattachment/cnsnodevmbatchattachment_helper.go
  pkg/syncer/cnsoperator/controller/cnsnodevmbatchattachment/cnsnodevmbatchattachment_test.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller_test.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/cnsoperator/util/util.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#3460 Update RBAC for K8s version 1.32 for volumesnapshots to allow namespace reconciler to watch volumesnapshots
  manifests/supervisorcluster/1.32/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes
