Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2025-10, with the labels that each got.

#3588 Wait until topology annotation gets added on supervisor PVCs while adding node affinity rules on PVs in guest cluster
  pkg/syncer/pvcsi_fullsync.go
  pkg/syncer/pvcsi_fullsync_test.go
  pkg/syncer/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3584 listview task monitoring enhancements
  pkg/common/cns-lib/volume/listview.go
  pkg/common/cns-lib/volume/manager.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#3641 Improve logging for vitualmachine snapshot controller
  pkg/syncer/cnsoperator/controller/virtualmachinesnapshot/virtualmachinesnapshot_controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3643 EF UTS test code fixes for TKG
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/util.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#3639 Initiate storage-quota Periodic syncs only after metasyncer is Initialized
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3640 vm-snapshot test fix
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/volume_health_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3646 Test fix for VCreboot : PR-3591504
  tests/e2e/util.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3648 EF UTS Production test cases fixes
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/util.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#3635 WFFC vmservice vm
  tests/e2e/e2e_common.go
  tests/e2e/util.go
  tests/e2e/vmservice_late_binding.go
  tests/e2e/vmservice_utils.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#3649 adding ef-f-wcp labels
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/statefulsets.go
  tests/e2e/volume_expansion_utils.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#3653 Fixing testcode for EF UTS production
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_metadata_syncer.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#3638 Chore - Enable profiling by default
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3655 Ensure consistent CSI transaction enablement using global controller initialization
  pkg/csi/service/vanilla/controller.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#3647 Enhancement - Optimise CNSFileAccessConfig reconciliation workflow
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/apis/cnsoperator/config/cnsfileaccessconfig_crd.yaml
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes
