Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2025-01, with the labels that each got.

#3141 Test fix for GC
  tests/e2e/csi_snapshot_basic.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#3020 vsan stretch testcase automation for TKG, WCP and VMService VMs
  go.sum
  tests/e2e/crypto.go
  tests/e2e/crypto_snapshot.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/hci.go
  tests/e2e/hci_mesh_rwx_disruptive.go
  tests/e2e/multi_vc_operation_storm.go
  tests/e2e/multi_vc_site_down.go
  tests/e2e/no_hci_mesh_rwx_multivc_disruptive.go
  tests/e2e/no_hci_mesh_rwx_singlevc_topology_disruptive.go
  tests/e2e/preferential_topology_disruptive.go
  tests/e2e/rwx_topology_utils.go
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/topology_operation_strom_cases.go
  tests/e2e/topology_site_down_cases.go
  tests/e2e/util.go
  tests/e2e/vm_service_vsan_stretch_cluster.go
  tests/e2e/vmservice_utils.go
  tests/e2e/vmservice_vm.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#3126 Bump up photon version to 5.0
  hack/release.sh
  images/driver/Dockerfile
  images/syncer/Dockerfile
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3137 Upgrade external-snapshotter to version v8.2.0
  go.mod
  go.sum
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/admissionhandler/validatepvc.go
  pkg/syncer/admissionhandler/validatepvc_test.go
  pkg/syncer/admissionhandler/validatesnapshotoperation.go
  pkg/syncer/admissionhandler/validatesnapshotoperation_test.go
  tests/e2e/crypto_snapshot.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_file_volume.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/raw_block_volume.go
  tests/e2e/snapshot_stretched_supervisor.go
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/svmotion_volumes.go
  tests/e2e/tkgs_ha.go
  tests/e2e/topology_snapshot.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3143 Update csi-snapshotter version to v8.2.0 for supervisor CSI deployment
  manifests/supervisorcluster/1.28/cns-csi.yaml
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3155 Remove supervisor pvc labels during pvcsi pvc delete
  pkg/syncer/metadatasyncer.go
  pkg/syncer/pvcsi_metadatasyncer.go
Labels: size/S, approved, cncf-cla: yes

#3157 Update csi-snapshotter image to v8.2.0 for Guest cluster
  manifests/guestcluster/1.32/pvcsi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3156 Validate the volume type while calculate AggregatedSnapshotCapacity
  pkg/syncer/fullsync.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3159 remove validation for topologyrequirement for vdpp-on-stretched-supervisor
  pkg/csi/service/wcp/controller.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, WorkloadDomainIsolation

#3161 [3.2]Update the registry url in manifest/vanilla
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, cncf-cla: yes

#3162 Remove supervisor pvc labels during pvcsi pvc delete (#3155)
  pkg/syncer/metadatasyncer.go
  pkg/syncer/pvcsi_metadatasyncer.go
Labels: size/S, approved, cncf-cla: yes

#3163 Crossport PR #3157 & PR #3137
  go.mod
  go.sum
  manifests/guestcluster/1.32/pvcsi.yaml
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
  manifests/vanilla/deploy-csi-snapshot-components.sh
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/common/common_controller_helper.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/admissionhandler/validatepvc.go
  pkg/syncer/admissionhandler/validatepvc_test.go
  pkg/syncer/admissionhandler/validatesnapshotoperation.go
  pkg/syncer/admissionhandler/validatesnapshotoperation_test.go
  tests/e2e/crypto_snapshot.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_file_volume.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/preferential_topology_snapshot.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/raw_block_volume.go
  tests/e2e/snapshot_stretched_supervisor.go
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/svmotion_volumes.go
  tests/e2e/tkgs_ha.go
  tests/e2e/topology_snapshot.go
Labels: size/L, approved, cncf-cla: yes

#3158 management workload domain isolation automation
  tests/e2e/e2e_common.go
  tests/e2e/mgmt_wrkld_domain_isolation.go
  tests/e2e/mgmt_wrkld_domain_isolation_utils.go
  tests/e2e/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3173 Restore the manifest related to snapshot validating webhook, as this is referred by older release branches
  manifests/vanilla/csi-snapshot-validatingwebhook.yaml
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#3174 revert volumdIDLimitPerQuery limit to 1k from 10k
  pkg/syncer/util.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3175 fix for replacing cluster id with new supervisor id
  go.mod
  go.sum
  pkg/syncer/fullsync.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3168 Fix xfs mount issue with xfsprogs 6.0.0 version
  pkg/csi/service/osutils/linux_os_utils.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3169 tkg-win automation
  tests/e2e/csi_cns_telemetry_statefulsets.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/svmotion_volumes.go
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/util.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes

#3179 Cherry-pick (#3168): Fix xfs mount issue with xfsprogs 6.0.0 version
  pkg/csi/service/osutils/linux_os_utils.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3182 Use diff prop collectors for two WaitForUpdates calls
  pkg/common/cns-lib/volume/listview.go
  pkg/syncer/storagepool/listener.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes
