Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2025-05, with the labels that each got.

#3271 Update pvc label in case tanzukubernetescluster-uid is changed
  pkg/syncer/pvcsi_fullsync.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3272 Cherry pick: Update pvc lable in case tanzukubernetescluster-uid is changed (#3271)
  pkg/syncer/pvcsi_fullsync.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3266 Fix the regression introduced in #3234
  pkg/csi/service/driver.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3262 Fix panic on DeletedFinalStateUnknown
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#3269 fullsync fix: Fix Syncer panics due to incorrect PVC configuration
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3282 set securityContext for all containers in cns-csi controller pod
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
Labels: approved, lgtm, size/M, cncf-cla: yes

#3281 CSI sidecar bump up
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, cncf-cla: yes

#3292 vanilla test fix for k8s upgrade 1.33
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/operationstorm.go
  tests/e2e/storagepolicy.go
  tests/e2e/vsphere_shared_datastore.go
Labels: size/S, needs-ok-to-test, approved, lgtm, cncf-cla: yes

#3260 Code fixes for Vm Service VM for static volume creation
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/util.go
  tests/e2e/vmservice_vm.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#3298 ginkgo-labels on testcases - Part1
  tests/e2e/e2e_common.go
  tests/e2e/hci.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/labelupdates.go
  tests/e2e/medadatasyncer_test_for_file_volume.go
  tests/e2e/mgmt_wrkld_domain_isolation.go
  tests/e2e/mgmt_wrkld_domain_isolation_tkg.go
  tests/e2e/mgmt_wrkld_domain_isolation_vmservice.go
  tests/e2e/multi_master_k8s.go
  tests/e2e/multi_svc_test.go
  tests/e2e/multi_vc.go
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/multi_vc_multi_replica.go
  tests/e2e/multi_vc_operation_storm.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/multi_vc_site_down.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#3306 Cherry pick commits upto 86b30329
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/common/utils/utils.go
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/hci.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/labelupdates.go
  tests/e2e/medadatasyncer_test_for_file_volume.go
  tests/e2e/mgmt_wrkld_domain_isolation.go
  tests/e2e/mgmt_wrkld_domain_isolation_tkg.go
  tests/e2e/mgmt_wrkld_domain_isolation_vmservice.go
  tests/e2e/multi_master_k8s.go
  tests/e2e/multi_svc_test.go
  tests/e2e/multi_vc.go
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/multi_vc_multi_replica.go
  tests/e2e/multi_vc_operation_storm.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/multi_vc_site_down.go
  tests/e2e/operationstorm.go
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/storagepolicy.go
  tests/e2e/util.go
  tests/e2e/vmservice_vm.go
  tests/e2e/vsphere_shared_datastore.go
Labels: approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#3303 Add Labels to test-cases
  tests/e2e/binding_modes_with_topology.go
  tests/e2e/config_change_test.go
  tests/e2e/crypto.go
  tests/e2e/crypto_snapshot.go
  tests/e2e/csi_cns_telemetry.go
  tests/e2e/csi_cns_telemetry_statefulsets.go
  tests/e2e/csi_cns_telemetry_vc_reboot.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_file_volume.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/csi_static_provisioning_basic.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#3311 Tag 3.5 RC1 images
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3310 Labels update for TKG read write many testcases
  tests/e2e/gc_rwx_basic.go
  tests/e2e/gc_rwx_deployments.go
  tests/e2e/gc_rwx_destructive.go
  tests/e2e/gc_rwx_multi_gc.go
  tests/e2e/gc_rwx_multi_ns_gc.go
  tests/e2e/gc_rwx_non_vsan_datastore.go
  tests/e2e/gc_rwx_operation_storm.go
  tests/e2e/gc_rwx_parallel_claim.go
  tests/e2e/gc_rwx_readonly.go
  tests/e2e/gc_rwx_reclaim_policy.go
  tests/e2e/gc_rwx_security_context.go
  tests/e2e/gc_rwx_service_down.go
  tests/e2e/gc_rwx_statefulsets.go
  tests/e2e/gc_rwx_static_provision.go
  tests/e2e/gc_rwx_syncer.go
  tests/e2e/gc_rwx_tkg_scale.go
  tests/e2e/gc_rwx_volume_health.go
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#3304 Enhance CNS Unregister Volume API to refer to K8s metadata instead of CNS metadata
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/commonco/coagnostic.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator_helper.go
  pkg/syncer/cnsoperator/controller/cnsunregistervolume/cnsunregistervolume_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3313 Cherry-pick PR: fix the winodws volume mountpath validation (#3312)
  pkg/csi/service/mounter/mounter_windows.go
  pkg/csi/service/osutils/windows_os_utils.go
Labels: approved, size/M, cncf-cla: yes

#3307 Decoupling shared utility functions from test files
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/pod_utils.go
  tests/e2e/raw_block_volume.go
  tests/e2e/staging_env_basic.go
  tests/e2e/statefulset_xfs.go
  tests/e2e/statefulsets.go
  tests/e2e/sts_utils.go
  tests/e2e/util.go
  tests/e2e/vmservice_utils.go
  tests/e2e/volume_expansion_utils.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#3305 Added Vc version details for the test cases in the labels
  tests/e2e/csi_static_provisioning_file_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/devops_tests.go
  tests/e2e/ds_rename.go
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/fullsync_test_for_file_volume.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_file_share_negative.go
  tests/e2e/gc_full_sync.go
  tests/e2e/gc_metadata_syncer.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes
