Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2025-09, with the labels that each got.

#3507 Code changes to support running vm service vm tests with Immediate and LateBinding storage policies
  tests/e2e/e2e_common.go
  tests/e2e/vmservice_vm.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3399 Remove FSS multi-vcenter-csi-topology
  pkg/common/unittestcommon/types.go
  pkg/common/unittestcommon/utils.go
  pkg/csi/service/common/authmanager.go
  pkg/csi/service/common/commonco/k8sorchestrator/k8sorchestrator.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/constants.go
  pkg/csi/service/vanilla/controller.go
  pkg/csi/service/vanilla/controller_helper.go
  pkg/csi/service/vanilla/controller_test.go
  pkg/csi/service/vanilla/controller_topology_test.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/cnsoperator/controller/triggercsifullsync/triggercsifullsync_controller.go
  pkg/syncer/cnsoperator/manager/init.go
  pkg/syncer/fullsync.go
  pkg/syncer/metadatasyncer.go
  pkg/syncer/syncer_test.go
  pkg/syncer/util.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#3520 Use dedicated service account for vSphere CSI webhook and update RBAC bindings
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3519 Change service type to ClusterIP for vsphere-csi-controller service
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3472 Improve RWX volumes with VM service VMs performace during webhook validation
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/validate_cnsfileaccessconfig.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3522 Disable CGO_ENABLED in CSI build
  Makefile
  images/ci/Dockerfile
  images/driver/Dockerfile
  images/syncer/Dockerfile
  images/windows/driver/Dockerfile
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3529 fix GetActiveClustersForNamespaceInRequestedZones to not skip zone not marked for deletion
  pkg/common/cns-lib/volume/util.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3524 Fix the LinkedClone FSS check and capability checks for pvcsi webhook
  pkg/csi/service/wcpguest/controller.go
  pkg/syncer/admissionhandler/admissionhandler.go
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3476 RWX VMService VM testcases and utils automation
  tests/e2e/constants/env_constants.go
  tests/e2e/constants/kubernetes.go
  tests/e2e/constants/test_suite_level.go
  tests/e2e/constants/vsan_constants.go
  tests/e2e/constants/vsphere_constants.go
  tests/e2e/csisnapshot/util.go
  tests/e2e/helpers/util.go
  tests/e2e/k8testutil/util.go
  tests/e2e/multiSvc/multi_svc_test.go
  tests/e2e/vcutil/vc_util.go
  tests/e2e/vmservice_vm/rwx_vmsvc_utils.go
  tests/e2e/vmservice_vm/rwx_vmsvc_vm_positive.go
  tests/e2e/vmservice_vm/vmservice_utils.go
Labels: needs-ok-to-test, approved, size/XXL, lgtm, cncf-cla: yes

#3532 Use the PVCClaim in vm spec instead of volumeName to fetch volumes
  pkg/syncer/cnsoperator/controller/virtualmachinesnapshot/virtualmachinesnapshot_controller.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3525 vSAN Stretch code changes to support running vm service vm tests with Immediate and LateBinding storage policies
  tests/e2e/vm_service_vsan_stretch_cluster.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3562 cf-wcp label update test
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/labelupdates.go
  tests/e2e/medadatasyncer_test_for_file_volume.go
  tests/e2e/volume_health_test.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#3568 Test code to describe CNSRegisterVolume
  tests/e2e/util.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#3569 Adding vKS testcases to EF column in UTS
  tests/e2e/csi_cns_telemetry_statefulsets.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/gc_block_resize_retain_policy.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_file_share_negative.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/raw_block_volume.go
  tests/e2e/storagepolicy.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere_shared_datastore.go
  tests/e2e/vsphere_volume_disksize.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3556 Add validation to ensure storageClassName on existing PVC matches the imported volume
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3561 Enhancement - Optimise CNSNodeVMAttachment reconciliation workflow
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/apis/cnsoperator/config/cns.vmware.com_cnsnodevmattachments.yaml
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3572 Add cf labels to block vanilla tests
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/labelupdates.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/raw_block_volume.go
  tests/e2e/svmotion_volumes.go
  tests/e2e/vsphere_shared_datastore.go
  tests/e2e/vsphere_volume_disksize.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
  tests/e2e/vsphere_volume_fstype.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#3570 Use capability for file volumes with VM service VMs feature
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/csi/service/common/constants.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3578 Timeout fixes for PV and VSC deletion
  tests/e2e/csi_snapshot_utils.go
  tests/e2e/e2e_common.go
  tests/e2e/vsphere.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3579 fix testdataFile variable value assignment
  tests/e2e/policy_driven_vol_allocation.go
Labels: needs-ok-to-test, size/XS, approved, lgtm, cncf-cla: yes

#3566 Removing resource quota util from gc code
  tests/e2e/gc_metadata_syncer.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3585 Fix - Grant privilege to update CNSUnregisterVolume/Status to the ClusterRole
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3586 Adding tkg snapshot usecases in EF UTS column
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/raw_block_volume.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3580 fix GetActiveClustersForNamespaceInRequestedZones to return correct set of active clusters for the namespace
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3591 Adding ef labels to file vanilla tests
  tests/e2e/csi_static_provisioning_file_basic.go
  tests/e2e/file_volume_statefulsets.go
  tests/e2e/fullsync_test_for_file_volume.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere_file_volume_basic.go
  tests/e2e/vsphere_file_volume_basic_mount.go
  tests/e2e/vsphere_file_volume_storagepolicy.go
  tests/e2e/vsphere_volume_expansion.go
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#3587 WCP tests for PQ and EF
  tests/e2e/config_change_test.go
  tests/e2e/crypto.go
  tests/e2e/crypto_snapshot.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/statefulsets.go
  tests/e2e/storagepolicy.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/vmservice_vm.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere_shared_datastore.go
  tests/e2e/vsphere_volume_disksize.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3593 ef tag addition for block vanilla tests
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/data_persistence.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/labelupdates.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/raw_block_volume.go
  tests/e2e/statefulset_xfs.go
  tests/e2e/statefulsets.go
  tests/e2e/storagepolicy.go
  tests/e2e/svmotion_volumes.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere_shared_datastore.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fstype.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#3592 Allow VolumeSnapshot and PVC deletion if the namespace is under deletion
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/validatepvc.go
  pkg/syncer/admissionhandler/validatepvc_test.go
  pkg/syncer/admissionhandler/validatesnapshotoperation.go
  pkg/syncer/admissionhandler/validatesnapshotoperation_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#3596 Removing duplicate testcases from EF and CF UTS column
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/raw_block_volume.go
  tests/e2e/storagepolicy.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere_shared_datastore.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#3581 Concatenate error when delete PV fails
  pkg/syncer/cnsoperator/controller/cnsregistervolume/cnsregistervolume_controller.go
Labels: size/XS, approved, lgtm, cncf-cla: yes

#3597 fix createSnapshotWithTransaction workflow
  pkg/common/cns-lib/volume/manager.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#3595 Surface NotSupported error message during AttachVolume call
  pkg/common/cns-lib/volume/manager.go
  pkg/common/cns-lib/volume/manager_test.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3610 vmservice - remove IP check if private network
  tests/e2e/vmservice_vm.go
Labels: approved, ok-to-test, size/M, cncf-cla: yes

#3620 wcp-snapshot test fix
  tests/e2e/csi_snapshot_basic.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3619 pq tag on block vanilla tests
  tests/e2e/csi_cns_telemetry.go
  tests/e2e/csi_cns_telemetry_statefulsets.go
  tests/e2e/csi_cns_telemetry_vc_reboot.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/multi_master_k8s.go
  tests/e2e/nodes_scaleup_scaledown.go
  tests/e2e/operationstorm.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/statefulsets.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/vsphere_volume_expansion.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3611 Allow devops users to attach GC RWX file volume with VM service VMs
  manifests/supervisorcluster/1.29/cns-csi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  manifests/supervisorcluster/1.32/cns-csi.yaml
  pkg/syncer/admissionhandler/cnscsi_admissionhandler.go
  pkg/syncer/admissionhandler/validate_cnsfileaccessconfig.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller_test.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3627 Adding wcp-vsan-stretch-vmsvc-tests to pq
  tests/e2e/vm_service_vsan_stretch_cluster.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#3624 Adding disruptive testcases to PQ UTS section
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_cns_nodevm_attachment.go
  tests/e2e/gc_full_sync.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/operationstorm.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/raw_block_volume.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere_volume_expansion.go
Labels: size/L, approved, lgtm, cncf-cla: yes
