Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2025-04, with the labels that each got.

#3237 Workload domain isolation - pvc creation with requested topology annotation
  tests/e2e/e2e_common.go
  tests/e2e/mgmt_wrkld_domain_isolation.go
  tests/e2e/mgmt_wrkld_domain_isolation_utils.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3238 Prevent cluster admin from deleting Supervisor PVC/Snapshots in use by TKC cluster
  go.mod
  go.sum
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/types/types.go
  pkg/syncer/fullsync.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3240 Crossport commits to main into release-3.5
  hack/release.sh
  pkg/common/cns-lib/vsphere/tagmanager.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/cns-lib/vsphere/virtualmachine.go
  pkg/common/unittestcommon/utils.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/topology.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/metadatasyncer.go
  tests/e2e/config_change_test.go
  tests/e2e/connection.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/labelupdates.go
  tests/e2e/mgmt_wrkld_domain_isolation.go
  tests/e2e/mgmt_wrkld_domain_isolation_utils.go
  tests/e2e/multi_master_k8s.go
  tests/e2e/statefulsets.go
  tests/e2e/storagepolicy.go
  tests/e2e/tkgs_ha.go
  tests/e2e/util.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/vmservice_vm.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsphere.go
  tests/e2e/vsphere_shared_datastore.go
  tests/e2e/vsphere_volume_disksize.go
  tests/e2e/vsphere_volume_expansion.go
  tests/e2e/vsphere_volume_fsgroup.go
Labels: approved, size/XXL, cncf-cla: yes

#3217 Fix Windows vanilla deployment - add missing service account
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3241 Upgrade to vm-operator v1alpha3 api for pvCSI
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_test.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/util.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsunregistervolume/cnsunregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller_test.go
  pkg/syncer/cnsoperator/util/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3239 Go code fixes to correctly read public and private port numbers for different hosts and VMs.
  tests/e2e/config_change_test.go
  tests/e2e/connection.go
  tests/e2e/crypto.go
  tests/e2e/csi_cns_telemetry_vc_reboot.go
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_snapshot_negative.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/ds_rename.go
  tests/e2e/e2e_common.go
  tests/e2e/fullsync_test_for_block_volume.go
  tests/e2e/fullsync_test_for_file_volume.go
  tests/e2e/gc_block_volume_expansion.go
  tests/e2e/gc_metadata_syncer.go
  tests/e2e/gc_rwx_service_down.go
  tests/e2e/gc_rwx_syncer.go
  tests/e2e/gc_rwx_volume_health.go
  tests/e2e/hci_mesh_rwx_disruptive.go
  tests/e2e/improved_csi_idempotency.go
  tests/e2e/mgmt_wrkld_domain_isolation.go
  tests/e2e/multi_master_k8s.go
  tests/e2e/multi_svc_test.go
  tests/e2e/multi_vc.go
  tests/e2e/multi_vc_config_secret.go
  tests/e2e/multi_vc_preferential_topology.go
  tests/e2e/no_hci_mesh_rwx_multivc_topology.go
  tests/e2e/policy_driven_vol_allocation.go
  tests/e2e/preferential_topology.go
  tests/e2e/preferential_topology_utils.go
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/statefulsets.go
  tests/e2e/suite_test.go
  tests/e2e/tkgs_ha.go
  tests/e2e/tkgs_ha_utils.go
  tests/e2e/topology_multi_replica.go
  tests/e2e/util.go
  tests/e2e/vc_reboot_volume_lifecycle.go
  tests/e2e/vcp_to_csi_attach_detach.go
  tests/e2e/vcp_to_csi_create_delete.go
  tests/e2e/vcp_to_csi_full_sync.go
  tests/e2e/vcp_to_csi_syncer.go
  tests/e2e/vm_service_vsan_stretch_cluster.go
  tests/e2e/vmservice_vm.go
  tests/e2e/volume_health_test.go
  tests/e2e/vsan_stretched_cluster.go
  tests/e2e/vsan_stretched_cluster_utils.go
  tests/e2e/vsphere_volume_expansion.go
Labels: approved, size/XL, cncf-cla: yes

#3247 Release 3.4 version
  manifests/vanilla/validatingwebhook.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3244 Workload domain isolation automation code for VM Service VM
  tests/e2e/mgmt_wrkld_domain_isolation.go
  tests/e2e/mgmt_wrkld_domain_isolation_utils.go
  tests/e2e/mgmt_wrkld_domain_isolation_vmservice.go
  tests/e2e/util.go
  tests/e2e/vmservice_utils.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#3242 Add guest cluster details on pre-existing PVC/VolumeSnapshots in fullsync after GC upgrade
  manifests/guestcluster/1.29/pvcsi.yaml
  manifests/guestcluster/1.30/pvcsi.yaml
  manifests/guestcluster/1.31/pvcsi.yaml
  manifests/guestcluster/1.32/pvcsi.yaml
  manifests/guestcluster/1.33/pvcsi.yaml
  manifests/supervisorcluster/1.30/cns-csi.yaml
  manifests/supervisorcluster/1.31/cns-csi.yaml
  pkg/csi/service/common/constants.go
  pkg/csi/service/wcpguest/controller.go
  pkg/csi/service/wcpguest/controller_helper.go
  pkg/syncer/cnsoperator/types/types.go
  pkg/syncer/fullsync.go
  pkg/syncer/pvcsi_fullsync.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3254 Reading multi vc ips export variables at runtime
  tests/e2e/e2e_common.go
Labels: size/S, approved, lgtm, cncf-cla: yes

#3251 WLDI - Dynamic and Pre-Provisioned snapshots in VKC
  tests/e2e/mgmt_wrkld_domain_isolation_tkg.go
  tests/e2e/mgmt_wrkld_domain_isolation_utils.go
  tests/e2e/util.go
Labels: needs-ok-to-test, size/L, approved, lgtm, cncf-cla: yes

#3253 Workload domain isolation automation code for VM Service VM
  tests/e2e/e2e_common.go
  tests/e2e/mgmt_wrkld_domain_isolation_vmservice.go
  tests/e2e/util.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3249 Test code fixes for pvc creation timeout and vm service ns creation
  tests/e2e/binding_modes_with_topology.go
  tests/e2e/e2e_common.go
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/svmotion_volumes.go
  tests/e2e/util.go
  tests/e2e/vmservice_vm.go
  tests/e2e/volume_provisioning_with_topology.go
  tests/e2e/vsphere_shared_datastore.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3234 Chore - Fix double trace IDs in the logs when initialising k8s orchestrator
  pkg/csi/service/driver.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3259 Add backward compatibility for vm-operator api version v1alpha1
  pkg/common/utils/utils.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcpguest/controller.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/util.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsunregistervolume/cnsunregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/cnsoperator/util/util.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3265 Cherry pick upto 59b057c2
  pkg/common/utils/utils.go
  pkg/csi/service/driver.go
  pkg/csi/service/wcp/controller_helper.go
  pkg/csi/service/wcpguest/controller.go
  pkg/kubernetes/kubernetes.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/cnsfileaccessconfig_controller.go
  pkg/syncer/cnsoperator/controller/cnsfileaccessconfig/util.go
  pkg/syncer/cnsoperator/controller/cnsnodevmattachment/cnsnodevmattachment_controller.go
  pkg/syncer/cnsoperator/controller/cnsunregistervolume/cnsunregistervolume_controller.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
  pkg/syncer/cnsoperator/util/util.go
  tests/e2e/binding_modes_with_topology.go
  tests/e2e/e2e_common.go
  tests/e2e/mgmt_wrkld_domain_isolation_tkg.go
  tests/e2e/mgmt_wrkld_domain_isolation_utils.go
  tests/e2e/mgmt_wrkld_domain_isolation_vmservice.go
  tests/e2e/provision_with_multiple_zones.go
  tests/e2e/snapshot_vmservice_vm.go
  tests/e2e/svmotion_volumes.go
  tests/e2e/util.go
  tests/e2e/vmservice_vm.go
  tests/e2e/volume_provisioning_with_topology.go
  tests/e2e/vsphere_shared_datastore.go
Labels: approved, size/XXL, lgtm, ok-to-test, cncf-cla: yes
