Repository kubernetes-sigs/vsphere-csi-driver, pull requests merged in 2025-03, with the labels that each got.

#3150 CVE-2024-45338: bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3205 fix static check failures upgrade to version to 2025.1
  hack/check-staticcheck.sh
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3202 Storage Pool - avoid extensive info logging
  pkg/syncer/storagepool/intended_state.go
  pkg/syncer/storagepool/util.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3181 Clean up the cnsvolumemetadata crs after tkc upgrade to non-legacy releases
  pkg/common/config/config.go
  pkg/syncer/pvcsi_fullsync.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3164 Upgrade CSI Proxy and enable privileged containers for windows
  go.mod
  go.sum
  manifests/guestcluster/1.33/pvcsi.yaml
  manifests/vanilla/vsphere-csi-driver.yaml
  pkg/csi/service/mounter/mounter_windows.go
Labels: kind/feature, approved, lgtm, ok-to-test, size/XL, cncf-cla: yes

#3209 Storage Pool - avoid extensive info logging
  pkg/syncer/storagepool/intended_state.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3212 Periodic sync - avoid extensive info logging
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3215 Periodic sync - avoid extensive info logging
  pkg/syncer/metadatasyncer.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3210 WCP test fix
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/statefulsets.go
  tests/e2e/tkgs_ha.go
  tests/e2e/util.go
  tests/e2e/vmservice_vm.go
Labels: size/L, approved, lgtm, cncf-cla: yes

#3214 Fix unnecessary error log in syncer during PodAdded event
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes, release-3.4.0-candidate

#3213 Remove unused flag from connect session
  pkg/common/cns-lib/vsphere/virtualcenter.go
Labels: size/S, approved, lgtm, ok-to-test, cncf-cla: yes

#3199 workload management domain isolation automation part2
  tests/e2e/csi_snapshot_basic.go
  tests/e2e/csi_static_provisioning_basic.go
  tests/e2e/e2e_common.go
  tests/e2e/mgmt_wrkld_domain_isolation.go
  tests/e2e/mgmt_wrkld_domain_isolation_utils.go
  tests/e2e/statefulsets.go
  tests/e2e/tkgs_ha.go
  tests/e2e/vmservice_vm.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#3221 Refactor tag manager rest client
  hack/release.sh
  pkg/common/cns-lib/vsphere/tagmanager.go
  pkg/common/cns-lib/vsphere/utils.go
  pkg/common/cns-lib/vsphere/virtualcenter.go
  pkg/common/cns-lib/vsphere/virtualmachine.go
  pkg/common/unittestcommon/utils.go
  pkg/common/utils/utils_test.go
  pkg/csi/service/common/commonco/k8sorchestrator/topology.go
  pkg/csi/service/common/topology.go
  pkg/syncer/cnsoperator/controller/csinodetopology/csinodetopology_controller.go
Labels: size/L, approved, lgtm, ok-to-test, cncf-cla: yes

#3223 WLDI - Test to create a stateful set on a shared storage policy on zonal namespace
  tests/e2e/mgmt_wrkld_domain_isolation.go
Labels: needs-ok-to-test, approved, lgtm, size/M, cncf-cla: yes

#3236 check for nil readytouse value from volumesnapshot status
  pkg/syncer/metadatasyncer.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes

#3220 Cherry pick relevant PRs to release-3.4
  go.mod
  go.sum
  hack/check-staticcheck.sh
  pkg/syncer/metadatasyncer.go
Labels: approved, lgtm, ok-to-test, size/M, cncf-cla: yes

#3231 Remove hardcoded vmodl version in e2e tests
  tests/e2e/connection.go
  tests/e2e/vsphere.go
Labels: size/XS, approved, lgtm, ok-to-test, cncf-cla: yes
